### PR TITLE
[WIP] macOS updates

### PR DESCRIPTION
**Pull request by danomatika**
This PR is meant to collect some commits which update the build on macOS for the upcoming Pd 0.52 release. A couple of things I can think of are:

* [x] Update Tcl/Tk build script to support arm64
* [x] Use Tcl/Tk [8.6.12](https://core.tcl-lang.org/tk/timeline?r=core-8-6-12-rc) once it's released (now released)
* [x] ~~Add signing and notarization helper script, ie. you only need to provide developer signature & .app~~ (do this in a separate PR later)
* [ ] Update precompiled Wish in `mac/stuff` and/or...
* [ ] ...update workflow regarding compiling Wish.app based on system (10.6 or newer 10.13+)
* [ ] Link to newer jack distribution on builds for new systems (10.13+) while keep weak linking on old systems
* [x] Hope/pray that macOS 12 doesn't break anything (using Tk 8.6.12, so should be ok)

Current macOS issues:

* [ ] #1384
* [ ] #1190
* [x] #1374
* [x] #1306
* [ ] #1303
* [x] #1251
* [x] #1094
* [x] #576
* [x] #514
* [x] #353
* [x] #239

Anything else I can remember...

* [x] Hope/pray that multi monitor window positioning is no longer broken when reopening a patch (can't find issue right now)... **this seems fine**

### CODE REVIEW

**Comment by umlaeute** [comment]
Tcl/Tk 8.6.12 has been released a few days ago :tada: 

on a related note:

for whatever reasons my Tcl/Tk-8.6.10 builds (compiled on macOS-10.15/Catalina) fail to run on macOS-10.12.
Pd-GUI just crashes with an error (`__objc_empty_cache: symbol not found`). This symbol is only referenced in *.../Tk.framework/Versions/8.6/Tk*.

Wish is built with `mac/tcltk-wish.sh 8.6.10` (and then incorporated into the Pd-app with `mac/osx-app.sh --wish Wish-8.6.10.app`.

I've tested the build on the following systems:
- macOS-10.12 (Sierra): fails :boom:
- ~~macOS-10.12 (High Sierra)~~ (i currently don't have access to that system)
- macOS-10.14 (Mojave) :tada:
- macOS-10.15 (Catalina) :tada:


any ideas what might go wrong?
i haven't tweaked the Tcl/Tk build system at all, but it seems it is invoked with `-mmacosx-version-min=10.6`, so that should be good.

You can find the build-logs at https://git.iem.at/pd/pure-data/-/jobs/32332 (and you can also download the created .app from this page (artifacts -> <kbd>Download</kbd>)
There's also a signed/notarized version available at https://git.iem.at/pd/pure-data/-/jobs/32346 (again: artifacts -> <kbd>Download</kbd>).

iirc the artifact links will only be valid for a week or so.

**Comment by umlaeute** [comment]
i also tried with Tcl/Tk-8.6.12 and the `udpate/macos-build` branch, but the problem persists (as was expected)

**Comment by millerpuckette** [comment]
If I'm reading this correctly I can happily merge this PR for the 0.52 release, correct?

**Comment by umlaeute** [comment]
@miller: yes i think so. the PR so far only contains:
- documentation updates
- script hygiene (removal of bashisms)
- universal-arch detection (based on available XCode)
- fallback-logic if you forgot to add the `.app` suffix for Wish

so merging should be save (although it won't fix many of the issues mentioned by @danomatika in the initial post).

possibly a PR (even WIP) is not the very best place to collect these open issues.

**Comment by danomatika** [comment]
No please don’t merge yet. I was only waiting first for Tk 8.6.12 then I can test the build and make suggestions on handling a few of those points. I am under pressure right now on other projects, so I haven’t been able to be very proactive this release, but I at least want to revisit those issues as many may probably have been fixed in Tk by now.

For instance, I consider the double key binding events on non-english locales a major problem.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by sebshader** [comment]
@umlaeute I feel like the ```ld: warning: URGENT: building for OSX, but linking against dylib (/usr/lib/libpthread.dylib) built for (unknown). Note: This will be an error in the future.```
seems odd.. does reinstalling command line tools make those warnings go away? It seems like the machine is mojave? on my mojave machine I get no such warnings when building tk 8.6.10 (in a fairly current ```master``` branch)

**Comment by umlaeute** [comment]
@danomatika wrote:
> For instance, I consider the double key binding events on non-english locales a major problem.

I agree that there are still (important) things todo.
however, i would also like to have any fixes get into Pd asap, however minor they may seem.
(as in: I see zero (0!) reasons why we shouldn't include a fix for the JACK linking problem in `master` while we are waiting for Tcl/Tk-8.6.12)

so i think that a PR is just the wrong tool for collecting problems that *should be* solved (it's the right tool for collecting problems that **are** solved).
so i went ahead and created a ["Project"](https://github.com/pure-data/pure-data/projects/3) that collects all the issues (and PRs) that hopefully can replace the "collecting issues" aspect of this PR.

**Comment by danomatika** [comment]
I updated the configure `--enable-universal` option to support `arm64`. I can now make a universal app on my macOS 11.6.1 system via:

~~~
./autogen.sh
./configure --universal
make
mac/tcltk-wish.sh --universal 8.6.1
mac/osx-app.sh -w Wish-8.6.12 0.52-0
~~~

The resulting Pd-0.52-0:
~~~
% file Pd-0.52-0.app/Contents/MacOS/Pd
Pd-0.52-0.app/Contents/MacOS/Pd: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
Pd-0.52-0.app/Contents/MacOS/Pd (for architecture x86_64):	Mach-O 64-bit executable x86_64
Pd-0.52-0.app/Contents/MacOS/Pd (for architecture arm64):	Mach-O 64-bit executable arm64
~~~

**Pull request merged**
