### PR TITLE
stable development branch

### PR DESCRIPTION
**Pull request by umlaeute**
(just merged, and here it is again)

this is the permanent branch `develop` that only gets curated, small, no-brainer changes that can be easily merged into master at any time.
(as a general rule-of-thumb we shouldn't include changes to `.pd`-files (including help patches!) in this PR, as it is just too easy to end up with unresolvable file conflicts. use the `documentation` branch for updating the documentation).

it supersedes https://github.com/pure-data/pure-data/pull/2299

---

### core

- rename `PD_CODE_VERSION` back to `PD_VERSION_CODE` (the version-extraction code has been fixed!)

### vendored libraries

- update portaudio updater script (indentation,...)

### docs

- small clarification in `writesf~-help.pd`

### CODE REVIEW

**Comment by umlaeute** [comment]
@danomatika please note that the policy for this branch is "no changes to Pd-files", esp. for help-files.

it's much to easy to step on the toes of our documentation team (@porres be warned that there *are* changes to `writesf~-help.pd`. you probably should sherry-pick https://github.com/pure-data/pure-data/pull/2306/commits/1318525b4f9f02ccc3060eb0d84ef125c93c5113 into `documentation`)

for future reference: i think changes like https://github.com/pure-data/pure-data/pull/2306/commits/1318525b4f9f02ccc3060eb0d84ef125c93c5113 should go directly into the `documentation` branch.

**Comment by danomatika** [comment]
AH sorry. "Pd-file" != "help file/patch" in my brain. I haven't committed to `documentation` but can next time.

**Comment by umlaeute** [comment]
>  "Pd-file" != "help file/patch" 

the problem is really, that merge-conflicts in `.pd` files are virtually impossible to resolve.

I'll update the description to 
> as a general rule-of-thumb we shouldn't include changes to `.pd`-files in this PR,

(though I honestly doubt that this is going to be much help :-) luckily the problem hardly ever appears)

**Comment by danomatika** [comment]
It's likely just me. I knew there was a `documentation` branch but didn't "two and two together" regarding file changes. I have thought of some sort of custom patch diff renderer for these kinds of things, but it's obviously better to just avoid the issue in the first place.

**Comment by porres** [comment]
@umlaeute can't you move https://github.com/pure-data/pure-data/pull/2306/commits/1318525b4f9f02ccc3060eb0d84ef125c93c5113 to 'dcoumentation' branch?

**Comment by porres** [comment]
I now see you asked me to cherry pick, I did it

**Pull request merged**
