### PR TITLE
Fix two typos in samplerate~-help.pd

### PR DESCRIPTION
**Pull request by jamshark70**
"litsen" --> "listen"

[Pd-messages] --> [pd-messages] (this abstraction failed to be created)

### CODE REVIEW

**Comment by porres** [comment]
I have already fixed this in my documentation branch, so please close this https://github.com/porres/pure-data/tree/Documentation

I missed the typo, but I'll fix it here as well

**Comment by umlaeute** [comment]
> I have already fixed this in my documentation branch

with *this* being the capitalisation of `[pd-messages]` (btw, this was reported in https://github.com/pure-data/pure-data/issues/1525)

@porres let's close this *once* you have included the fix in your branch, not before (you mightalso want to add a `Closes: https://github.com/pure-data/pure-data/issues/1568` line to the body of your commit message

**Comment by jamshark70** [comment]
Agreed to close this after porres's fix is in that docs branch :+1:

**Comment by porres** [comment]
the capitalization has been fixed for a while but it seems I didn't link the commit to that issue.

I'm doing many changes in a new branch that I'll merge to the documentation branch and have included the typo fix https://github.com/porres/pure-data/commit/54b177e130db19affb74ec0e7f102c4f03224cb7

this is for adding a reference subpatch for each help file, I should be finished soon

**Comment by porres** [comment]
I now have this as part of my documentation updates in my documentation branch https://github.com/pure-data/pure-data/pull/1517/commits/54b177e130db19affb74ec0e7f102c4f03224cb7

**Comment by umlaeute** [comment]
@porres: could you please add a `Closes: https://github.com/pure-data/pure-data/pull/1568` line to the (top-level?) description of your PR?

**Comment by porres** [comment]
can we please close this PR now?

**Comment by Spacechild1** [comment]
Closed in favor of #1517

**Pull request closed without merging**
