### PR TITLE
pdcontrol features

### PR DESCRIPTION
**Pull request by porres**
This PR implements a additions to [pdcontrol], for starters, I'm adding an argument that expands the functionality of the 'isvisible' method as discussed in https://github.com/pure-data/pure-data/issues/803

### CODE REVIEW

**Comment by porres** [comment]
wow, too many commits, only the last one is the one that does something new and closes https://github.com/pure-data/pure-data/issues/803

**Comment by porres** [comment]
I see many other applications of the commit https://github.com/pure-data/pure-data/pull/820/commits/022303e8785d9a27639739f5c19f54839ae56791 . I think it's a more powerful/configurable alternative solution to https://github.com/pure-data/pure-data/issues/819 but it can also be used for other things, like filtering out mouse events from [cyclone/mousestate] for instance

**Comment by porres** [comment]
I see many other applications of the commit https://github.com/pure-data/pure-data/pull/820/commits/022303e8785d9a27639739f5c19f54839ae56791 . I think it's a more powerful/configurable alternative solution to the key issue in https://github.com/pure-data/pure-data/pull/570 but it can also be used for other things, like filtering out mouse events from [cyclone/mousestate] for instance

**Comment by porres** [comment]
oh nice, I only made it worse

**Comment by Spacechild1** [comment]
Just make a copy of your code, start again from current master and then force push.

**Comment by porres** [comment]
> start again from current master

Like, delete this branch and close the PR so I'd start over from scratch?

> and then force push.

What is "force push" and how do I do it?

**Comment by Spacechild1** [comment]
> Like, delete this branch and close the PR so I'd start over from scratch?

If you don't use git in the terminal, yes, delete your *local* branch and create it again from current master. Otherwise you can use `git reset` (https://git-scm.com/docs/git-reset). You don't necessarily have to close your PR, though (see below).

> What is "force push" and how do I do it?

a force push, well forces a push, i.e. ignores any conflicts and just overwrites everything. generally, you shouldn't do this on public branches which other people use, because their local copies would get out of sync. The command is `git push --force` (see https://git-scm.com/docs/git-push)

If you can't do a force push, delete the remote branch (on Github) and then push your local branch again.

**Comment by Spacechild1** [comment]
I would highly recommend to get familiar with git on the command line. Personally, I found the following very helpful: https://git-scm.com/book/en/v2

**Comment by porres** [comment]
> you can use git reset (https://git-scm.com/docs/git-reset). 
> The command is git push --force (see https://git-scm.com/docs/git-push)

yeah, reading these didn't make sense to me, I tried a few things and I was able to screw other pull requests that were fine (documentation updates) - I now see no other solution then completely delete my repository and start a fresh fork of Pd... but this will screw my other old PRs up as the original repository will not exist anymore...

well, no time to read a book right now - I'll see what I can do

**Comment by Spacechild1** [comment]
you don't have to delete your fork! why do you think that? your other PRs are fine. what you could do is delete your local master branch and recreate it from current upstream master. you old PRs should be not affected and this makes sure that new PRs are clean.

> well, no time to read a book right now

just read the first 3 chapters are you're good. this will help you understand how git works and then many things become clearer. at the same time, download git for the command line and start playing around with it, you won't regret it.

**Comment by porres** [comment]
> your other PRs are fine

nah, this got corrupted... https://github.com/pure-data/pure-data/pull/823

> you don't have to delete your fork! why do you think that?

It's the only workable solution to have new clean PRs that I know so far to do it right now, so I did it. I'm now getting my latest PRs a new version 

> you won't regret it.

I definitely won't :) thanks

**Comment by porres** [comment]
New PR https://github.com/pure-data/pure-data/pull/828

**Comment by Spacechild1** [comment]
> t's the only workable solution to have new clean PRs that I know so far to do it right now, so I did it. 

why don't you ask resp. wait for my answers? now you know that you only have to delete and recreate the master branch to start new clean PRs.

**Comment by porres** [comment]
I'm sorry, I'm really ignorant on this and I don't want to bother you giving me classes on how to do this only for me to fail miserably - but I do appreciate your help. Anyway, new PRs are up and clean now.

> now you know that you only have to delete and recreate the master branch to start new clean PRs.

I actually have no idea on how to do that

**Comment by porres** [comment]
and I'm sorry, but with a few mishaps and terrible things I did, I got pissed with myself and just did what I did, I got tired of banging my head to the wall :) - if there's not a stupid simple way of doing this via github desktop I'll most probably screw things up a few times before I get it right

**Comment by umlaeute** [comment]
@porres sorry.

your contributions are valuable, thanks a lot.

however, your communication is exhausting at least:
> well, no time to read a book right now

so because a single person cannot be made to read a book right now, you force others to read the equivalent of a book in your comments.
those *others* are plural, so in the end more reading is to be done as compared to you sitting down and learning the tools.

> I don't want to bother you giving me classes

but nevertheless you do.

it seems that the issue of not being able to handle `git` is a recurring one.


> i'm really ignorant on this

but that can be easily helped.

please do get yourself familiar with the infrastructure we are using.
start reading the git-book. now.

the time needed to do so is a much better investment than fighting git, communicating your frustration in long threads, having others consume that communication, and making others  repeatedly sum up the same things.

:parasol_on_ground: :book: :christmas_tree:

**Comment by porres** [comment]
Thanks! Believe I know how annoying this must be as I also feel terrible and frustrated I can't do basic things. I feel annoyed too I had a bunch of commits I couldn't get rid of. So much I went for a drastic solution.

It seems the main wall I keep hitting is how to clean this up and delete master for a new one without nuking my repository. I'll definitely learn how to do it, can't wait for it. But googling yesterday about it led me nowhere and I kept screwing things up. For the short term I did this. I got two performances this week, an album I'm recording . So no joke when I said I had no time now, and I see the repository is getting a lot of action and I don't want to miss this window! But soon I leave  for 🎄and hopefully ⛱where it'd be perfect to do some of 📖while at it. My top 1 goal priority for the summer (I'm on the southern hemisphere as most people know)

**Pull request closed without merging**
