### PR TITLE
[pdcontrol] add 'version' method

### PR DESCRIPTION
**Pull request by Lucarda**
adds 'version' method to [pdcontrol]. it outputs the Pd version we are running.

### CODE REVIEW

**Comment by porres** [comment]
I already have one PR for this :) https://github.com/pure-data/pure-data/pull/828/commits/8ed7ee60a019f88ab69d80b24b3fb953975c518b

**Comment by porres** [comment]
and an issue about it https://github.com/pure-data/pure-data/issues/928

**Comment by Lucarda** [comment]
closing in favor of https://github.com/pure-data/pure-data/pull/828 that was done earlier :)

**Comment by Lucarda** [comment]
Reopening as this PR is less bloated.

**Comment by porres** [comment]
> Reopening as this PR is less bloated

What do you mean?

**Comment by Lucarda** [comment]
I meant it has fewer options but I'm closing it anyway.

:)

**Comment by porres** [comment]
> I meant it has fewer options but I'm closing it anyway.

still didn't get it ;) that PR adds more than one change to [pdcontrol], 'version' method included.

anyway, my take was just to spit a list with three items (major, minor, bugfix) which I think is enough.

**Comment by Lucarda** [comment]
> still didn't get it ;) that PR adds more than one change to [pdcontrol], 'version' method included

Yeah because your PR adds more than that change i said it was bloated.

**Pull request closed without merging**
