### PR TITLE
binarymsg.c Emscripten fix for ofxPd

### PR DESCRIPTION
**Pull request by Jonathhhan**

### CODE REVIEW

**Comment by Spacechild1** [comment]
Please provide a PR description so we can know what it is about. In particular, what kind of issue does it address?

**Comment by Jonathhhan** [comment]
@Spacechild1 without #include "m_pd.h" in `binarymsg.c` I get this error:

```
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:13:40: error: unknown type name 'FILE'
   13 | static void pd_tilde_putfloat(float f, FILE *fd)
      |                                        ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:15:5: error: call to undeclared function 'putc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   15 |     putc(A_PDFLOAT, fd);
      |     ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:15:10: error: use of undeclared identifier 'A_FLOAT'
   15 |     putc(A_PDFLOAT, fd);
      |          ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:8:19: note: expanded from macro 'A_PDFLOAT'
    8 | #define A_PDFLOAT A_FLOAT
      |                   ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:16:5: error: call to undeclared function 'fwrite'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   16 |     fwrite(&f, sizeof(f), 1, fd);
      |     ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:16:5: warning: declaration of built-in function 'fwrite' requires inclusion of the header <stdio.h> [-Wbuiltin-requires-header]
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:19:32: error: unknown type name 't_symbol'
   19 | static void pd_tilde_putsymbol(t_symbol *s, FILE *fd)
      |                                ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:19:45: error: unknown type name 'FILE'
   19 | static void pd_tilde_putsymbol(t_symbol *s, FILE *fd)
      |                                             ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:22:5: error: call to undeclared function 'putc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   22 |     putc(A_PDSYMBOL, fd);
      |     ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:22:10: error: use of undeclared identifier 'A_SYMBOL'
   22 |     putc(A_PDSYMBOL, fd);
      |          ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:9:20: note: expanded from macro 'A_PDSYMBOL'
    9 | #define A_PDSYMBOL A_SYMBOL
      |                    ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:28:30: error: unknown type name 'FILE'
   28 | static void pd_tilde_putsemi(FILE *fd)
      |                              ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:30:5: error: call to undeclared function 'putc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   30 |     putc(A_PDSEMI, fd);
      |     ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:30:10: error: use of undeclared identifier 'A_SEMI'
   30 |     putc(A_PDSEMI, fd);
      |          ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:10:18: note: expanded from macro 'A_PDSEMI'
   10 | #define A_PDSEMI A_SEMI
      |                  ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:33:29: error: unknown type name 't_atom'
   33 | static int pd_tilde_getatom(t_atom *ap, FILE *fd)
      |                             ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:33:41: error: unknown type name 'FILE'
   33 | static int pd_tilde_getatom(t_atom *ap, FILE *fd)
      |                                         ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:35:14: error: use of undeclared identifier 'MAXPDSTRING'
   35 |     char buf[MAXPDSTRING];
      |              ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:38:20: error: call to undeclared function 'getc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   38 |         int type = getc(fd), fill;
      |                    ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:42:14: error: use of undeclared identifier 'EOF'
   42 |         case EOF:
      |              ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:44:14: error: use of undeclared identifier 'A_SEMI'
   44 |         case A_PDSEMI:
      |              ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:10:18: note: expanded from macro 'A_PDSEMI'
   10 | #define A_PDSEMI A_SEMI
      |                  ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:45:13: error: call to undeclared function 'SETSEMI'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   45 |             SETSEMI(ap);
      |             ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:47:14: error: use of undeclared identifier 'A_FLOAT'
   47 |         case A_PDFLOAT:
      |              ^
/mnt/c/Users/Jonat/Desktop/openFrameworks-audioWorklet-3/addons/ofxPd/libs/libpd/pure-data/extra/pd~/binarymsg.c:8:19: note: expanded from macro 'A_PDFLOAT'
    8 | #define A_PDFLOAT A_FLOAT
      |                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
```

**Comment by umlaeute** [comment]
@Jonathhhan then you might be doing it wrong:
`binarymsg.c` is *included* by other C-files, e.g https://github.com/pure-data/pure-data/blob/27c52e44082ae650380b7a73015b7e436a4fa92d/extra/pd~/pdsched.c#L22 and https://github.com/pure-data/pure-data/blob/27c52e44082ae650380b7a73015b7e436a4fa92d/extra/pd~/pd~.c#L148

since these "other C-files" already include `m_pd.h`, there's no need to duplicate this.
arguably, the `binarymsg.c` could be called `binarymsg.h` to make it clear that this file is not to be compiled into an object file directly


---
also note that a "PR description" should go into the top-post of the PR, so it is easy to find on first glance (and anyone late to the party does not have to look for it in the thread).
you can edit your original post to fill in the missing info.

**Comment by umlaeute** [comment]
i'm closing this PR, as the the proposed fix is wrong (it includes `m_pd.h` when compiling `pd~` for Max/MSP).

(that's *beside* what i wrote above about being *unnecessary* in the first place)

**Comment by Jonathhhan** [comment]
@umlaeute thanks. It actually works, if I rename `binarymsg.c` to `binarymsg.h`.

**Comment by umlaeute** [comment]
well, probably your buildsystem just builds *all* C-files (`*.c`), which - in this case - is not the right thing to do.
this would mean that the build system is broken (but i cannot check because i do not even now which build-system you are using)

**Comment by Spacechild1** [comment]
> arguably, the binarymsg.c could be called binarymsg.h to make it clear that this file is not to be compiled into an object file directly

+1 Including .c files is just confusing, so I would definitely opt for renaming `binarymsg.c` to `binarymsg.h`. Should we just go ahead and do this on develop?

**Comment by Jonathhhan** [comment]
@Spacechild1 I can confirm that it was my mistake, because I put binarymsg.c in the wrong location.
If placed right, it gets excluded by: 	
```
# this is included directly in pd~.c, don't build twice
ADDON_SOURCES_EXCLUDE = libs/libpd/pure-data/extra/pd~/binarymsg.c
```
https://github.com/danomatika/ofxPd/blob/master/addon_config.mk

**Pull request closed without merging**
