### PR TITLE
Resize several objects together

### PR DESCRIPTION
**Pull request by pierreguillot**
- Allow several objects to be resized together based on the selection.
- The resizing doesn't use incrementation anymore but it computes the new size with the position at clicking - it offers a better precision and this is the only solution to resize several objets because the width is based on the number of characters. 
- Set the minimum width to 4 and the minimum height to  6 for the GOP otherwise it is impossible to select it anymore.
- Use shift to restrain the height of GOP by the width

The subject has been discussed here #82 (see the GIF to have an overview). It goes beyond the issue so if you prefer I can create another PR that only solve this specific issue.

### CODE REVIEW

**Comment by danomatika** [comment]
Can you merge this with the current master?

**Comment by pierreguillot** [comment]
I can give a try. I'm pretty busy but I hope I can do this this week-end would it be OK?

**Comment by millerpuckette** [comment]
I'm not sure I'll be able to get it into 0.49 at this point - I'm down to fixing
the last bogs (and waiting for one last font tweak).

cheers
Miller

**Comment by pierreguillot** [comment]
Alright, I'll wait for 0.49 and then, I'll try to fix the conflicts with the up-to-date master branch.

**Comment by millerpuckette** [comment]
I tried to apply this fixing the conflict but multi-resize didn't seem to work for me.

**Comment by millerpuckette** [comment]
(and now github thinks it's merged although it's not really.)

**Comment by danomatika** [comment]
One option is to ask the original PR authors to update their branch to current master, then the merge should be clean. It take a little extra time but spreads the work load at least.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by Spacechild1** [comment]
@pierreguillot I saw that this PR got merged, but I resizing of multiple objects doesn't seem to work for me at all on latest master... Specifically, I don't get a resize cursor when hovering over selected objects. Can you check?

**Comment by pierreguillot** [comment]
@Spacechild1 Miller said that he didn't manage to merge but Github thinks it's merged - perhaps because one commit was merged. The changes get inconsistent before being merged in the master branch. The code must be updated regarding the changes made on master (it was 2 years ago), I'll try to do that ASAP and I'll create another MR. So feel free to keep this one closed but perhaps you could keep the issue #82 open because the problem is not fixed.

**Comment by Spacechild1** [comment]
> I'll try to do that ASAP and I'll create another MR.

Cool!

> So feel free to keep this one closed but perhaps you could keep the issue #82 open because the problem is not fixed.

Regarding #82 : I've actually tried and couldn't reproduce the problem anymore, so I assumed it has been fixed already. Can you double check as well?

**Pull request merged**
