### PR TITLE
"Save as" defaults to the original filename

### PR DESCRIPTION
**Pull request by umlaeute**
as discussed at lengths on the mailinglist...

however, while answering #746, i found the commit that introduced the current behaviour: b6b19c7afbdba37701d38cd4cac98dc31fb116ea

it seems that after all this was intentional. quoting from the commit message:
> "save as" no longer sends an initial file name to the `tk_getSaveFile` function
> 
> this seems to have stopped working in tcl 8.5 on Macintosh (the
> `initialfile` gets incorporated into the `initialdir` and the dialog gets badly
> confused.)  Workaround is simply not to supply it.

this PR has been tested on linux with Tcl/Tk-8.6, but not on any other system.
Given the comment, i would highly recommend testing this PR on various ("all") deployments, before accepting it.

### CODE REVIEW

**Comment by danomatika** [comment]
Ok on macOS 10.14 and Pd 0.50-0 w/ embedded Tk 8.5.19.

**Comment by danomatika** [comment]
Actually, I'm wrong. The filename received by `pdtk_canvas_saveas` is ok, but the save panel still show's "Untitled.pd".

**Comment by umlaeute** [comment]
I can confirm the non-functioning of my patch on OSX (10.12 and 10.14), with the default Tcl/Tk that comes with Pd-0.50 (Tcl/Tk-8.5.19).

With this Tcl/Tk version, `tk_getSaveFile` ignores the `initialfile` completely, and i'm not sure i fully understand what `initialdir` dir.

Using the Tcl/Tk that comes with Mojava (`$ echo 'puts $tk_version' | wish` returns *8.6*) it works as expected.
Starting Pd via `wish pd-gui.tcl` makes the `Save As...` dialog work (although other things seem to be broken, like rendering patches...)

So I guess this is just another bug in Tcl/Tk on OSX.

**Comment by umlaeute** [comment]
now that Pd-0.51 ships with Tcl/Tk-8.6, this PR seems to work nicely.

@millerpuckette i think this is ready for inclusion. if you do want to support the broken Tk8.5 on macOS, we *could* special handle this case explicitely. just tell me ;-)

**Comment by umlaeute** [comment]
hand-applied with 27cf05e

**Pull request closed without merging**
