### PR TITLE
Bumped to deken/v0.3.0 which supports the new .dek package format.

### PR DESCRIPTION
**Pull request by umlaeute**
- new fileformat
- support for double precision Pd (clarification of the "bits" field)
- uninstall-before-install
- bells
- deken-specific preferences
- proxy/https support (if the relevant system libraries are installed)
- whistles and hoops

### CODE REVIEW

**Comment by umlaeute** [comment]
@danomatika it would be nice to have the deken-preferences in Pd's common preferences menu...

**Comment by porres** [comment]
Hi, I wrote this to the list, but maybe here is better. About one of the "bells" -  _**set installation path (suggesting Pd's default search paths, and offering to create those that are missing)**_ - I see a problem. In short, see: this: https://github.com/pure-data/pure-data/pull/139 and how we should consider only the "extra" folder as **the** standard folder. And also how the new external folder since 0.48-0 already fixes this issue and makes this kinda pointless now. Given that, I'm even suggesting a Pull Request to clear this up for good, it's here: https://github.com/pure-data/pure-data/pull/183

See also: https://github.com/pure-data/pure-data/issues/184 which discusses the behaviour of [declare] and how we could just use "-path" and forget about "-stdpath" 

Now, I don't know how the plugin works, but I may assume it gets these paths from Pd, so maybe if my Pull Request gets accepted, no change needs to be made in the Deken plugin and it'll just stop showing them... cause as it is, this is adding unnecessary complexity and confusion.

**Comment by porres** [comment]
> Now, I don't know how the plugin works, but I may assume it gets these paths from Pd, so maybe if my Pull Request gets accepted, no change needs to be made in the Deken plugin and it'll just stop showing them... 

So, I tested it, and it is true. And I also closed that Pull Request and opened a new one here https://github.com/pure-data/pure-data/pull/321

**Comment by umlaeute** [comment]
included in `update/0.48-2` #336

**Pull request closed without merging**
