### PR TITLE
[0.52-test2] Fix crasher on list and symbol gatoms

### LINKED ISSUE #1453: [0.52-test2] list atom crashes Windows.
Pd @ 90ad800 Windows amd64.

Steps to reproduce:

1. create a list atom
2. type `hello world` and press enter.
3. re-enter to edit it and add `10`

   * `hello world 10`
   * press enter : &#128165;

#### GDB back trace:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
rtext_key (x=0x202c9ae4ee0, keynum=0, keysym=0x3) at g_rtext.c:660
660         else if (!strcmp(keysym->s_name, "Home"))
(gdb) bt
#0  rtext_key (x=0x202c9ae4ee0, keynum=0, keysym=0x3) at g_rtext.c:660
#1  0x00007ffa1d1064d7 in gatom_key (z=<optimized out>,
    keysym=<optimized out>, f=<optimized out>) at g_text.c:803
#2  0x00007ffa1d0ed53b in rtext_key (x=0x202c9ae4ee0, keynum=keynum@entry=10,
    keysym=keysym@entry=0x202c9aea660) at g_rtext.c:594
#3  0x00007ffa1d0d1421 in canvas_key (x=0x202c9ae4510, av=<optimized out>,
    ac=<optimized out>, s=<optimized out>) at g_editor.c:3057
#4  0x00007ffa1d11d963 in binbuf_eval (x=<optimized out>,
    target=0x202c9ae4a80, target@entry=0x0, argc=-1073741637, argc@entry=0,
    argv=0x7f7e1ff3c0, argv@entry=0x0) at m_binbuf.c:790
#5  0x00007ffa1d12a22d in socketreceiver_read (fd=736, x=0x202c9ae7f50)
    at s_inter.c:658
#6  socketreceiver_read (x=0x202c9ae7f50, fd=736) at s_inter.c:590
#7  0x00007ffa1d1295d0 in sys_domicrosleep (microsec=microsec@entry=0)
    at s_inter.c:226
#8  0x00007ffa1d12b08b in sys_pollgui () at s_inter.c:976
#9  0x00007ffa1d1260df in sched_idletask () at m_sched.c:299
#10 0x00007ffa1d126b6c in m_pollingscheduler () at m_sched.c:375
#11 m_mainloop () at m_sched.c:432
#12 0x00007ff62b8a13b1 in ?? ()
#13 0x00007ff62b8a14c6 in ?? ()
#14 0x00007ffa69467c24 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#15 0x00007ffa6a1ad4d1 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#16 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

The below pic shows weird chars when entering the first `hello world` : This only shows up when Pd is started by **GDB**

list-atom

### PR DESCRIPTION
**Pull request by Lucarda**
fixes crasher on gatoms [list] and [symbol].

fixes #1453

### CODE REVIEW

**Comment by umlaeute** [comment]
im merging this into `develop`, but have amended dec5fab to unset `a_doubleclicked` at the beginning of the `c=='\n'` clause rather than at the end (similar to the final `else` clause).
while there, i also fixed the indentation

**Comment by Lucarda** [comment]
> i'm merging this into develop, but have amended dec5fab to unset a_doubleclicked ..

Suddenly this PR is full of unrelated commits. Is this Ok?

**Comment by umlaeute** [comment]
> Suddenly this PR is full of unrelated commits. Is this Ok?

i think this is just a side-effect of me retargetting this PR to `develop` (instead of `master`).
not sure why this happened.

**Comment by Spacechild1** [comment]
I think it's because `develop` is behind `master`.

**Comment by Lucarda** [comment]
I can redo the PR if needed.

**Comment by umlaeute** [comment]
no need.
i've pushed your changes to `develop` (but using a `git rebase` rather than a `git merge`, so github doesn't know about it - esp. with my amendments)

**Pull request closed without merging**
