### PR TITLE
fix libpd ios build by wrapping dlopen call with HAVE_LIBDL

### PR DESCRIPTION
**Pull request by danomatika**
This fixes an oversight when a new function was added to s_loader.c: iOS doesn't support dlopen, so we need to wrap it with `HAVE_LIBDL`.

### CODE REVIEW

**Comment by danomatika** [comment]
@millerpuckette If this is approved by the others, can you merge? It's a block for making a libpd release as, currently, building on iOS is broken.

**Review by umlaeute — APPROVED** [review]
lgtm.

**Comment by umlaeute** [comment]
merged into the `develop` branch.

**Comment by danomatika** [comment]
Aw, `master` would be better. ;)

**Pull request merged**
