### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [pure-data/Interface](https://hosted.weblate.org/projects/pure-data/pure-data/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by porres** [comment]
did you use my latest translation work here?

**Comment by umlaeute** [comment]
No.

**Comment by umlaeute** [comment]
I just fixed some "cosmetic" issues (like trailing colons where there should be none), and an obvious error (introduced by some gettext automatisation, iirc) that would translate "ZIP files" as "Pd files"

**Comment by Lucarda** [comment]
@umlaeute  I logged in with my github account to https://hosted.weblate.org/projects/pure-data/pure-data/es/ and did some few more translations. It all went good as "user experience".

Did webplate notified you of the changes I'd made via the web interface?

**Comment by umlaeute** [comment]
@Lucarda weblate automatically makes PRs (like this one), but afaict it waits up to 24h to accumulate some commits (and to allow the editing frenzy to settle down)

**Comment by Lucarda** [comment]
&#128077;

**Pull request merged**
