### PR TITLE
New standard font size (set to 12 instead of 10)

### PR DESCRIPTION
**Pull request by porres**
closes https://github.com/pure-data/pure-data/issues/703

### CODE REVIEW

**Comment by porres** [comment]
only the last commit is the one we need, I don't know why the others came up

**Comment by millerpuckette** [comment]
I did it by hand (I seem not to be able to cherry-pick commits out of PRs)

**Comment by porres** [comment]
ok, thanks!

**Comment by danomatika** [comment]
>only the last commit is the one we need, I don't know why the others came up

Your branch was most-likely out of date. You probably needed to pull master and merge it with your branch before doing the PR, either that or you branched in the wrong place, ie. from another branch.

>(I seem not to be able to cherry-pick commits out of PRs)

Unless you [pull Alex's branch](https://stackoverflow.com/questions/5884784/how-to-pull-remote-branch-from-somebody-elses-repo), you won't have the commit locally in order to cherry-pick.

If the branch is clean, it's often easy to merge by using the Github Merge button and then pulling from GitHub to your machine.

**Pull request closed without merging**
