### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by umlaeute**
## Update existing translations

- Italian (100%)
- Japanese (100%)
- Portuguese - Portugal (87%)
- Ukrainian (95%)

some translations were already complete, but have now improved translations:
- Spanish
- Portuguese - Brazil

#### minor updates

a couple of languages received updates that only concerned punctuation (e.g. adding a trailing colon)

- Bulgarian
- Basque
- French
- Chinese (Traditional)

#### housekeeping updates

a number of other language files have been touched, but there the changes are cosmetic only (mostly creating constistent settings for  the translation teams)

## Remove stub translations

some translations haven't been updated in the last 15 or so years, and had less than 4% translated to begin with.
other have been created recently, but with zero (0!) actual translations.

We'd be lying in our pockets if we claimed that these translations are useful for anybody, so I've removed them:

- Afrikaans
- Arabic
- Belarussian
- Finnish
- Hebrew
- Armenian
- Turkish

### CODE REVIEW

**Comment by umlaeute** [comment]
@millerpuckette you might want to include these for 0.53-1.

(If you have a better idea on how to handle the merging workflow, i'm all open for it; so far i have kept myself from merging these translation updates into `develop`, as the promise of `develop` is about bugfixes; but if it makes your life simpler, we could probably just include the translations there as well. I see little conflict potential in the `po/` folder, which usually is not touched at all)

**Comment by millerpuckette** [comment]
Better to keep them separate so I can at least try to keep track of changes in the code - if there are lots of non-code changes in the update PRs they will get even harder for me to track..  I didn't see this but am happy to merge it.

**Comment by umlaeute** [comment]
> Better to keep them separate 

fine with me.

>  I didn't see this

that's because i only create the PR this morning (seeing that there was no open PR with the translation fixes).

in general the translation PR will always come from the `l10n` ("*localisation*") branch, just like the develop-PR is always coming from the `develop` branch. so if i forgot to open the PRs you *could* manually check these branches (but I totally understand that this is yet another unwanted item on the TODO-before-release list, so I'll try to keep the PRs open)

**Comment by millerpuckette** [comment]
Aha - so I should just always check both update and l10n branches as well as PRs, so that perhaps you don't have to keep generating PRs for those.

**Pull request merged**
