### PR TITLE
update "portmedia" (portaudio & portmidi)

### PR DESCRIPTION
**Pull request by danomatika**
**ready to test**

This PR updates to newer versions of portaudio and portmedia and adds helper scripts to make this much easier in the future. This will also add any need custom patches (hopefully not).

Update script functionality example:

    cd portaudio
    ./update.sh <--- downloads & places portaudio sources from git master
    ./update.sh 1237fdfsf34h <--- specify a branch/tag/commit

See the current portaudio git revision in the new `portaudio/portaudio/src/common/pa_gitrevision.h` header. 

Also, we cleaned a lot of unneeded files a couple years ago. This PR also removes unneeded/unused host apis and some other random txt files.

TODOs:

* [x] portaudio update script
* [x] update portaudio and handle new/removed files
* [x] Do we need any custom portaudio patches? ... NO
* [x] portmidi update script
* [x] update portmidi and handle new/removed files ... none new, removed unneeded cruft
* [x] Do we need any custom portmidi patches? ... YES

### CODE REVIEW

**Comment by danomatika** [comment]
We don't need a custom patch for portaudio as handling device unplugs on macOS was [already added](https://app.assembla.com/spaces/portaudio/git/commits/src/hostapi/coreaudio/src/hostapi/coreaudio/src/hostapi/coreaudio/src/hostapi/coreaudio/src/hostapi/coreaudio/pa_mac_core46c|2574).

**Comment by danomatika** [comment]
Ok, portmidi update script and generated patch are done. This PR is now ready for testing.

**Comment by millerpuckette** [comment]
Cool.. I presume this is to be merged into master, not into my portaudio branch, yes?

**Comment by danomatika** [comment]
Yeah, I haven't looked at your branch yet as I/we ended up inadvertently working concurrently. I chalk that up to a 9 hour latency and my desire to keep tracking any custom changes to 3rd party libraries sane.

**Comment by millerpuckette** [comment]
Yeah, sanity aint a bad branch.  Maybe that should have been the name instead of Pd...

**Comment by danomatika** [comment]
Ok, files removed and `make distcheck` passes. Also, the CI builds seem to be ok as well, so at least no compiler errors.

**Comment by millerpuckette** [comment]
I'm running it on a PC and working so far.  (only tried 32 bit, the more difficult case).

**Comment by danomatika** [comment]
Closing as this appears to be merged.

**Comment by danomatika** [comment]
Wait, never mind. There are a few commits that didn't making, mainly those removing files that are no longer needed.

**Comment by danomatika** [comment]
Nevermind, again. Everything seems to be in. The commit I was referring to was in the one branch we didn't end up needing so I'll bring this into the `update/0.49` branch instead.

**Comment by umlaeute** [comment]
can the `update/portmedia` branch be closed?

**Comment by danomatika** [comment]
yup

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Pull request closed without merging**
