### PR TITLE
Make code used in libpd compile using MSVC

### PR DESCRIPTION
**Pull request by eldruin**
Libpd includes some sources from the pure-data repository.
These need a couple adaptions in order for them to build correctly when using Microsoft Visual C compiler.
The commit messages should be descriptive enough.
Please let me know about any further improvements I could try under MSVC.

### CODE REVIEW

**Comment by danomatika** [comment]
Cool to see VS actually working. The last time I tried about 5 years ago, it was so many errors due to unsupported C version it seemed hopeless.

**Comment by pierreguillot** [comment]
Since your fix is for multi-instance support I pull your branch in this PR #288. And I suggest you to use the commits that I made if you want to avoid some crashes.

**Comment by millerpuckette** [comment]
About the second commit (Fix compiler error C2492 on MSVC) - could I just say
extern PERTHREAD ...
and not make the new macro?

**Comment by pierreguillot** [comment]
It's merged into master, you can close the issue.

**Pull request closed without merging**
