### PR TITLE
icon update

### PR DESCRIPTION
**Pull request by danomatika**
(This is a re-uploaded PR of #194 to keep history clean from intermediate icon files.)

Updated icons for all platforms:

* macOS: pd.icns & pd-file.icns (much higher resolution)
* Windows: pd.ico (now with multiple sizes)
* Linux: pd.gif (512x512) & puredata.xpm (hand-tuned to match others)

This will give Pd a consistent icon between systems.

On Linux, pd-gui.tcl now checks if the gif is available in the sys_guidir and loads it as the application icon. I added pd.gif to the tcl/Makefile.am but I'm not sure what is the best way to hand things on Linux since the desktop environment might load icons in a different manner, ie. Debian uses the xpm. Maybe there should be a configure flag to disable installing the gif? This is a question for @umlaeute.

Also, tcl/Makefile.am now only installs the relevant icon file based on the platform (.ico for Windows and .gif for Linux).

Removed `src/pd.ico` as it's already loaded from the tcl location in `pd-gui.tcl`. The `src/makefile.mingw` was updated to reflect this.

The design is based on the Pd-extended icon proportions while maintaining the minimal look of the vanilla icon. It was generated from an actual patch using the sag export plugin, tweaked in Inkscape, and saved as an SVG. The font is DejaVu Sans Mono bold for better readability and the line weights are thicker than normal. The icon repo is [pd-icon](https://github.com/pure-data/pd-icon).

Pd icon

~~~
                                
                                
   .........                    
   .##...##.                    
   .#.###.#.                    
   ..#####..                    
   ..#####..                    
   ..#####..                    
   ..#####..                    
   .#.###.#.                    
   .##...##.                    
   .........                    
    .                           
    .                           
   ..........................   
   ....$$$$$$$$$$$$$$$$$$....   
   .$$$$$$$$$$$$$$$$$$$$$$$$.   
   .$$$$$$$$$$$$$$$$$$$$$$$$.   
   .$.....$$$$$$$..$$$$$$$$$.   
   .$..$$..$$$$$$..$$$$$$$$$.   
   .$..$$..$$$$$$..$$$$$$$$$.   
   .$..$$..$$$.....$$$$$$$$$.   
   .$.....$$$..$$..$$$$$$$$$.   
   .$..$$$$$$..$$..$$$$$$$$$.   
   .$..$$$$$$..$$..$$$$$$$$$.   
   .$..$$$$$$$.....$$$$$$$$$.   
   .$$$$$$$$$$$$$$$$$$$$$$$$.   
   .$$$$$$$$$$$$$$$$$$$$$$$$.   
   ....$$$$$$$$$$$$$$$$$$$$$.   
   ..........................   
                                
~~~

### CODE REVIEW

**Comment by porres** [comment]
looks good ;) - thanks

**Comment by umlaeute** [comment]
Quoting Dan Wilcox <notifications@github.com>:
> On Linux, pd-gui.tcl now checks if the gif is available in the  
> sys_guidir and loads it as the application icon. I added pd.gif to  
> the tcl/Makefile.am but I'm not sure what is the best way to hand  
> things on Linux since the desktop environment might load icons in a  
> different manner, ie. Debian uses the xpm. Maybe there should be a  
> configure flag to disable installing the gif? This is a question for  
> @umlaeute.

for Debian the most important part would be to have the "source code"  
of the images available so all the formats for the different  
platforms/uses can be generated from those (e.g. have an SVG that can  
be converted to GIF, XPM, ICNS,...).

it's pretty easy during the package generation to exclude/include files.

>     M debian/puredata.xpm (78)

the second most important thing from both a Debian perspective and my  
personal one is to remove the debian/ folder completely, as it is not  
used for the Debian packages *at all*;
and so its only purpose is bitrotting (it's already removed from the  
'git archive' by means of .gitattribues), keeping innocent developers  
busy and lure self-compiling users into the false hope that they can  
build debs directly from the Pd sources.
please don't spend your time updating files in that folder.

gfasdrm
IOhannes

**Comment by danomatika** [comment]
>for Debian the most important part would be to have the "source code"
of the images available

I have the sources in the [pd-icon](https://github.com/pure-data/pd-icon) repo for now. They could be moved here. All images can be generated, except for the xpm which I adjusted by hand.

>the second most important thing from both a Debian perspective and my
personal one is to remove the debian/ folder completely

Ok, let's do it. It was there so I assumed it was what you used...

**Comment by danomatika** [comment]
If this adopted, I'd also recommend using the unified icon on http://puredata.info. The homepage itself has 3 different icons:

  * upper left [pd~]
  * favicon
  * Pd vanilla download button

It could be argued the first two represent the website ore than vanilla, but I'd argue vanilla is the core of the community and the various forks. At the very least, the vanilla download icon can be updated.

**Comment by danomatika** [comment]
This branch has been brought up to date.

**Comment by danomatika** [comment]
This branch is now up to date.

**Comment by millerpuckette** [comment]
This had spurious changes to src/Makefile.am and something in debian which I assume weren't needed.  Otherwsie merged.

**Comment by danomatika** [comment]
I'll check the makefile. I think the main thing was installing the gif on Linux.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
In looking through this, I'm not seeing most of the changes reflected in the master branch, so I'm not sure if the manual merge worked this time. The main thing I see is that *none* of the new icons are actually there! The makefile changes mainly revolve around moving all the GUI icons into the `tcl` directory, ie. src/pd.ico -> tcl/pd.ico and then conditionally installing them based on the platform.

In any case, I made a new PR for the missing/remaining changes: #428

**Pull request closed without merging**
