### PR TITLE
document new "equal" message in pointer-help.pd

### PR DESCRIPTION
**Pull request by Spacechild1**
@millerpuckette I forgot to document the new "equal" message in https://github.com/pure-data/pure-data/pull/436 ...

### CODE REVIEW

**Comment by porres** [comment]
I can get to that, give me some time :)

**Comment by Spacechild1** [comment]
yes, please!

**Comment by porres** [comment]
Oh, I thought this was an issue, haha, well, I could check it too :) as that now is also conflicting!

**Comment by porres** [comment]
So, I thought I was generating a new PR for the master, but it seemed I made one for you? So, anyway, I guess I also solved the conflicting issues, let me know

**Comment by porres** [comment]
Wow, github is still quite confusing to me, but anyway, here's a new PR that replaces this and solves the conflicts! https://github.com/pure-data/pure-data/pull/823

**Pull request closed without merging**
