### PR TITLE
Nicer to read Pd Manual  (closed moved to #232)

### PR DESCRIPTION
**Pull request by Lucarda**
********* **This PR is deprecated and moved to [#232](https://github.com/pure-data/pure-data/pull/232)** *******************

- Changed doctype to HTML5
- New CSS ("pdmanual.css", old code commented)
- Some "< p >" were added and some minor fixes.
- Images are centered.
- Nicer to read with Sans Serif font
- Better integration with traditional HTML.
- [Click here to preview](http://lucarda.com.ar/x/manual/)

********* **This PR is deprecated and moved to [#232](https://github.com/pure-data/pure-data/pull/232)** *******************
.

### CODE REVIEW

**Comment by Lucarda** [comment]
**keeping track of these that have to be fixed if merged, on the 0.48.0 release notes part:**
  
  
 <P> "soundfiler" now has a right outlet which outputs a list with the
 sample rate, header size, number of channels, byte depth, and endianness.
 
   
 <P> "float" now understands symbol messages that look like floats.  The help
 files for "float", "value" and "send" were updated to reflect this.



  Thanks to Dan Wilcox.
  Thanks to danomatica.

IOhannes
Iohannes

~/Doculemnts/Pd
~/Documents/Pd

canceling
cancelling

**Comment by jreso** [comment]
I think it would be nice to base our work on this PR #171. A modern approach, one file, multiple outputs. I proposed also some css styles [here](http://reso-nance.org/public/pd-doc/). I can put them in one single file. The idea is to be pleasant and readable on mobile devices.

We could also take newer screenshots, but may be after the PR #227 is valid.

**Comment by Lucarda** [comment]
> I think it would be nice to base our work on this PR #171. A modern approach, one file, multiple outputs.

IMO the Pandoc thing is somehow unnecessary to make a single file. It will take 30 minutes to make a one file .html with any text editor. The 6 files are very nice and clean html code so is not and issue to make it one file. I also think there's no benefit in making it one long-to-scroll file.

As for “multiple outputs” that's another story. Anyway it will be converted from an html source.

**Comment by Lucarda** [comment]
********* **This PR is deprecated and moved to [#232](https://github.com/pure-data/pure-data/pull/232)** *******************

**Pull request closed without merging**
