### PR TITLE
fix nbx/gatom issues

### PR DESCRIPTION
**Pull request by porres**
closes https://github.com/pure-data/pure-data/issues/851 - see comment --> https://github.com/pure-data/pure-data/issues/851#issuecomment-629194457
closes https://github.com/pure-data/pure-data/issues/1690
closes https://github.com/pure-data/pure-data/issues/1708

### CODE REVIEW

**Comment by porres** [comment]
ping @umlaeute did you consider this PR into "merge-iemgui"? Any issues? cheers

**Comment by porres** [comment]
So far, I think I've managed to successfully keep the inlet/outlet functionality of gatom boxes. This is one of the items in https://github.com/pure-data/pure-data/issues/1641

Next on that list I would like to try and allow send & receive symbols to be the same (with feedback suppression)

**Comment by porres** [comment]
Oh dear, I guess I've made a bit of a mess. I was first including commits for the iemguis-merge branch, but some commits here are actually more in regards to "gatoms" and I didn't realize I kept pushing commits to iemguis-merge.

Please @umlaeute, tell me what you think it's best.

Sidenote, I'm using "move" for the new code bits, and I also used that on another PR --> https://github.com/pure-data/pure-data/pull/1635

**Comment by umlaeute** [comment]
sorry, i've lost track of this PR.

the good news is, that miller has merged #1570 and #1633 (which would break many GUI-related PRs), so now is a good time to start anew :-)

**Pull request closed without merging**
