### PR TITLE
updates from test3 feedback

### PR DESCRIPTION
**Pull request by danomatika**
* [x] update to latest deken
* [x] fix missing Audio on/off translation strings
* [x] recent files menu not populating on macOS
* [x] deken search button width too small for translations
* [ ] remove midiin & sysexin Windows warnings in x_midi.c (& update help file)?
* [ ] add Windows autotools build info to INSTALL.txt (Dan is working on this now)

### CODE REVIEW

**Comment by porres** [comment]
probably more related to deken, but nonetheless a translation issue:

"show all" gets cropped in other languages, such as in portuguese with "mostrar todos". Make it a little bigger?

Another remark is that there is a text saying "To get a list of all available externals, try an empty search" - but this seems obvious with the "show all" button, when the search field is empty.

**Comment by porres** [comment]
Another thing I'm having an issue with translating is "Send a Pd message". I think this is wrong, and the original should be "Send Pd a message", cause that's what it does, right?

Another suggestion is to mark this in the File Menu as "Message to Pd..." instead of just "Message..." - this would make it much clearer

**Comment by danomatika** [comment]
The recent files not being saved issue should be fixed in the latest commit. This was a mac issue but would probably be good to test on other platforms to make sure.

**Comment by danomatika** [comment]
> On Jul 20, 2017, at 11:12 PM, Alexandre Torres Porres <notifications@github.com> wrote:
> probably more related to deken, but nonetheless a translation issue:
> 
> "show all" gets cropped in other languages, such as in portuguese with "mostrar todos". Make it a little bigger?
> 
Fixed.
> Another remark is that there is a text saying "To get a list of all available externals, try an empty search" - but this seems obvious with the "show all" button, when the search field is empty.
> 

Open an issue on the pure-data/deken repo for this.

--------
Dan Wilcox
@danomatika <http://twitter.com/danomatika>
danomatika.com <http://danomatika.com/>
robotcowboy.com <http://robotcowboy.com/>

**Comment by danomatika** [comment]
> On Jul 20, 2017, at 11:18 PM, Alexandre Torres Porres <notifications@github.com> wrote:
> 
> Another thing I'm having an issue with translating is "Send a Pd message". I think this is wrong, and the original should be "Send Pd a message", cause that's what it does, right?
> 
> Another suggestion is to mark this in the File Menu as "Message to Pd..." instead of just "Message..." - this would make it much clearer
> 

I think these are fine. The menu item is pretty clear once you open the window once. The wording of "Send a Pd message" works both ways since that box is for sending the same messages as what you can send from a message box following a semicolon, so you're sending a "Pd message to Pd" :)

--------
Dan Wilcox
@danomatika <http://twitter.com/danomatika>
danomatika.com <http://danomatika.com/>
robotcowboy.com <http://robotcowboy.com/>

**Comment by porres** [comment]
sorry, I got the "message" thing really wrong

**Comment by porres** [comment]
> Open an issue on the pure-data/deken repo for this.
done: https://github.com/pure-data/deken/issues/154

**Pull request merged**
