### PR TITLE
fixing log float arg

### PR DESCRIPTION
**Pull request by porres**

### CODE REVIEW

**Comment by porres** [comment]
ok, i'm still a bit lost here, but i'm trying to propose a fix fir the log~'s argyment which wasn't loading or working at all

**Comment by porres** [comment]
tried to get back to " x->x_f = 0; " but couldn't do it and make a new PR

**Comment by umlaeute** [comment]
quick guide to PRs:

- [x] fork the project
- [x] clone your forked project (to your desktop)
- [ ] add the *upstream* project to your local clone
```
git remote add upstream https://github.com/pure-data/pure-data/
```
- [ ] start a *new* branch for *each* feature on top of `upstream/master`
```
git checkout -b fix-log-argument upstream/master
```
- [ ] commit your changes; **only** commit changes that are relevant for this specific feature/bugfix/...
- [ ] push the changes to a *separate branch* on  *your fork*
```
git push upstream fix-log-argument
```
- [ ] create a Pull Request via the webinterface
- [ ] in your local copy, switch back to `master`, and **do not touch** the feature-branch (`fix-log-upstream`) any more (unless you discovered that it broke things and you need to fix them)
```
git checkout master
```
- [ ] never ever continue working on unrelated things in that pull-request branch.

if you want to start another PR (for another feature)
- [ ] first make sure to update your local repository to have the current `upstream/master`.
```
git pull --all
```
- [ ] create a new feature branch from current `upstream/master`
```
git checkout -b fix-tan-argument upstream/master
```

**Comment by porres** [comment]
so, I did retry this following such steps

**Comment by Ant1r** [comment]
@umlaeute this guide is cool and could be highlighted somewhere (maybe in the github's wiki); but I think the point 6 needs a fix:

>      push the changes to a separate branch on your fork
> git push upstream fix-log-argument
> 

I think it should be:
 git push **origin** fix-log-argument

am I right ?
Also, couldn't pushing more commits to the feature branch be considered as correct, if this makes the fix/add more elegant (or fixes some typo) ?

**Comment by umlaeute** [comment]
thanks for the correction. fixed.

**Comment by umlaeute** [comment]
and I've put it onto the [wiki](https://github.com/pure-data/pure-data/wiki/Pull-Requests)

**Comment by Ant1r** [comment]
nice!

**Pull request closed without merging**
