### PR TITLE
Bugfixes to go into 0.48-2

### PR DESCRIPTION
**Pull request by umlaeute**
this PR contains a collection of bug-fixes for 0.48-2

### CODE REVIEW

**Comment by porres** [comment]
ho, can you include this to the list? https://github.com/pure-data/pure-data/pull/283

**Comment by porres** [comment]
hey, maybe this one too? :) https://github.com/pure-data/pure-data/pull/286

**Comment by porres** [comment]
hi, in addition to #286 I'd like to also suggest the inclusion of these other minor and simple updates in here: https://github.com/pure-data/pure-data/pull/290 & https://github.com/pure-data/pure-data/pull/292

**Comment by pierreguillot** [comment]
Hi, it would be great if you could include #288. I think it's not a big priority for the Pd application (perhaps more more for libpd) but I'd really like to see these bugs fixed for 0.48-2

**Pull request merged**
