### PR TITLE
in clone-help.pd call an abstraction abstraction, not subpatch

### PR DESCRIPTION
**Pull request by mxa**
renamed the abstraction and to clone-abstraction.pd and call it an abstraction in the clone helpfile.

### CODE REVIEW

**Comment by mxa** [comment]
Wanted to make a clean pull request for e5ca483 but didn't know how to do it.

**Comment by umlaeute** [comment]
@mxa 
- all files **must** be listed in the relevant `Makefile.am` 
   - if you rename files, you must also update the `Makefile.am`
- you shouldn't create PRs from your `master` branch. instead create a separate feature-branch
- TravisCI currently fails because of some pull error (probably because i pushed to your `master`; i don't really know); that's supposed to be unrelated to the actual code which i think is now fine...at least a local `make distcheck` succeeds.

**Comment by umlaeute** [comment]
ah no; the TravisCI failures are because i was confused becase of your `master`, therefore pushed to the wrong branch, deleted that branch and now TravisCI cannot find it any more...

**Comment by millerpuckette** [comment]
Should I just apply these changes by hand?  Especially as it involved renaming a file, which merging ought to do correctly but I've been bitten by that one.

**Comment by mxa** [comment]
@millerpuckette probably wise to do this by hand.

**Comment by danomatika** [comment]
I went ahead and applied this manually to #438 via commit 79d58eaf3564e695305a75c68d443ac844bfa9c9.

**Comment by mxa** [comment]
Thank you Dan and Miller.

**Pull request closed without merging**
