### PR TITLE
[getdir]

### PR DESCRIPTION
**Pull request by danomatika**
So just throwing this out there...

This PR integrates the [getdir] object by Guenter Geiger into Pd vanilla.

Being able to get the directory of the patch or it's parent(s) is useful for opening resources relative to an abstraction but also for supplying the directory to pd's open/close messages. This is one of the few externals I still need for use with libpd on mobile, mainly for playlist management for cycling through songs. Having functionality like this included with vanilla or a "core external" is one of the last things I would need to make my setup vanilla-only (one of these others being the sound file info).

This object is very small, works well, and Guenter uses a permissive [license](http://git.puredata.info/cgit/svn2git/libraries/ggee.git/tree/LICENSE.txt) for his [ggee externals](http://git.puredata.info/cgit/svn2git/libraries/ggee.git/tree/).

This may not be the best or most canonical solution, but it has worked well for me for years. It could also be included as an "extra."

### CODE REVIEW

**Comment by porres** [comment]
**A-W-E-S-O-M-E !!!!!**

THANKS

Always hoped for a vanilla solution for that

**Comment by danomatika** [comment]
Just a suggestion, no guarantee.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment]
> no guarantee.

I know :/

**Comment by danomatika** [comment]
Other useful utilities for paths would be something like tcl's file basename, dirname, & rootname. In fact a set of utilities like this could be rolled up into a [path] object ala:

* [path canvas $arg] <- equivalent to [getdir] with optional depth arg
* [path basename] <- file/dir name without parent dir
* [path dirname] <- parent dir
* [path rootname] <- filename without extension
* [path extension] <- only extension
* [path filename] <- alias for makefilename, etc
* [path split] <- split a filename into a list using a separator
* [path join] <- join a list into a filename using a separator
* [path absolute] <- ensure an absolute path
...

Also, there is the ggee [splitfilename] object for the base name/dirname code.

OTOH perhaps a [path] object is basically just a symbol...? I have been able provide *some* functionality for working with paths using [list from symbol] & [list tosymbol], but getting the directory is just not possible in vanilla so far. See the p\_\* objects in [rc-patches/rc](https://github.com/danomatika/rc-patches/tree/master/rc).

**Comment by millerpuckette** [comment]
I think, yes, a general way to deal with canvas properties is needed - this would also save people having to reverse-engineer "donecanvasdialog" and probably eventually a lot of other stuff.

**Comment by megrimm** [comment]
+1 on a [getdir] object. there has been a lot of demand for this over the years on the mailing list and I'm sure would be greatly appreciated...

cheers
m

**Comment by fdch** [comment]
+1 on path object. I actually delved into all g_canvas and made a [mainpath] object myself. It took me a while to figure out with the little i know of c. I was its sole user for a month or so until i found getdir. So it would be very appreciated to access all those nice canvas functions which would make file interaction much faster to patch

**Comment by danomatika** [comment]
Maybe a [canvas] object?

* [canvas dir $depth]: get canvas dir or parent dir
* [canvas name]: get canvas name
* [canvas mouse]: get/send mouse interaction
* [canvas key]: get/send key interaction
* [canvas close]
* ...

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
isn't there a `[canvas]` object in purr-data/pd-l2ork? if so, make sure that they are not incompatible...

**Comment by danomatika** [comment]
Maybe we can adopt the Pd-L2ork [canvasinfo] object? https://github.com/pd-l2ork/pd/blob/master/pd/src/x_interface.c#L174

**Comment by jreso** [comment]
:+1: 
for a [path] object, getting inspired by [ggee/getdir], [tof/path], [hcs/folder_list], [ext13/strippath]
also some UI about finding files like [browser.mmb](https://github.com/dotmmb/mmb/blob/master/browser.mmb.pd)], or my little menu button which list files of a directory.

folders-abs

:+1: 
also for objects with deal files : [file], like [ext13/filesize] and string like [mrpeach/str] i

**Comment by danomatika** [comment]
I'm closing this branch for now. I'd suggest someone opening a general issue for a canvas info / path object and reference this discussion.

**Comment by porres** [comment]
I just went ahead and did this... https://github.com/pure-data/pure-data/pull/617

**Pull request closed without merging**
