### PR TITLE
Fix factorial in expr for negative values

### LINKED ISSUE #284: factorial of negative values in [expr]
screen shot 2018-01-09 at 15 46 39

As said in the image above, this freezes pd for a while and outputs 0...

Now, I don't know what the output should be, maybe minus infinity? 

Anyway, it seems a simple logic could prevent the factorial of negative values to be calculated (thus, preventing it from freezing Pd for a while).

### PR DESCRIPTION
**Pull request by porres**
closes #284

### CODE REVIEW

**Comment by porres** [comment]
again, sorry and please ignore the extra commits, I've reverted back the trigger update from my other pull request and this uses the original trigger code/help file.

**Comment by umlaeute** [comment]
again, please try to clean the PR from the `[trigger]` changes (remove the commits (either via a force push or with a new PR; don't just revert the commits).

as a sidenote: you could use some git visualisation tool (like `gitk`) to easily check your branches before submitting PRs.

**Comment by porres** [comment]
I don't know how to remove commits yet, I can close this and start a new one, cause the way I dealt with it was to delete my fork and start a new one :)

**Comment by umlaeute** [comment]
> I don't know how to remove commits yet,

"force push" a branch that does not not have the offending commits.

**Pull request closed without merging**
