### PR TITLE
file-help.pd: rename multiply-defined text

### LINKED ISSUE #1499: [file-help] multiply defined text
In `file-help.pd`, there are two instances of the same `[text define -k $0-name-split+join-strings]`.
This causes an error to be post to the Pd console two times when testing `[pd split+join]` and `[pd base+ext`]:
```
warning: 1022-name-split+join-strings: multiply defined
warning: 1022-name-split+join-strings: multiply defined
```
Note: these errors are not traceable (i.e ctrl-clickable), which makes it more difficult to locate their origin.

### PR DESCRIPTION
**Pull request by Ant1r**
fixes #1499

### CODE REVIEW

**Comment by porres** [comment]
can you make a PR to my doc updates branch? https://github.com/pure-data/pure-data/pull/1494

**Comment by umlaeute** [comment]
@porres: in any case you could just cherry-pick the changes, no?

**Comment by Ant1r** [comment]
> can you make a PR to my doc updates branch?

anyway, I did it (correctly, I hope).
 porres#17

**Comment by porres** [comment]
merged

**Comment by porres** [comment]
so you can close this :)

**Pull request closed without merging**
