### PR TITLE
move 'verbose' setting from path dialog to startup dialog

### PR DESCRIPTION
**Pull request by Ant1r**
(was previously #226, now redirected to master)
 IMHO 'verbose' flag is more a startup flag than a path related setting.
This is only a GUI change, and doesn't modify any variable name for e.g, so it shouldn't impact compatibility, excepting patches or plugins or externals directly calling pdtk_path_dialog or pdtk_startup_dialog (but are they numerous?).

### CODE REVIEW

**Comment by danomatika** [comment]
Since this touches the FUDI messaging between core and GUI, I think this is less likely to be accepted. We don't know what might be relying on that value being with the patch dialog.

To a certain perspective, having the verbose button where it is makes sense in that most of the prints you see involve printing the search paths...

**Comment by Ant1r** [comment]
> We don't know what might be relying on that value

I've no problem if you want to close this PR, but just for my understanding, what could use this value? GUI plugins for instance? Could some externals rely to this too?

**Comment by danomatika** [comment]
>I've no problem if you want to close this PR, but just for my understanding, what could use this value? GUI plugins for instance? Could some externals rely to this too?

I don't know. libpd, for instance, can open a connection to the gui. It's relatively likely that a app using an older version of libpd may try to talk to a newer Pd gui. Even though libpd doesn't really use the GUI's settings, I'm not sure what would happen if you opened and closed the dialog.

**Comment by Ant1r** [comment]
Ok thanks, let's close it. Really not a big deal.

**Comment by danomatika** [comment]
This is something I wanted to fix with a united preferences dialog, but it will have to wait until the next version of Pd.

**Pull request closed without merging**
