### PR TITLE
add missing  [drawtext] / [drawsymbol] objects to documentation

### PR DESCRIPTION
**Pull request by porres**
added references to [drawtext] and [drawsymbol] into help-intro.pd

added [drawtext] in drawtext-help.pd file as it wasn't mentioned anywhere in any help file... and seems like it could be into drawtext-help.pd if any :) - but I didn't add any information on what it does or what's different about, because I just have no idea!

### CODE REVIEW

**Comment by porres** [comment]
this closes https://github.com/pure-data/pure-data/issues/342

**Comment by porres** [comment]
I wouldn't know :/

**Comment by porres** [comment]
but it'd be something that miller could check and act pretty quickly on, not much hassle I suppose

**Comment by danomatika** [comment]
My point is more that I won't merge this into the update branch yet, as I'm not sure the issue is clear yet.

**Comment by millerpuckette** [comment]
merged (with slight alteration)

**Comment by porres** [comment]
cool, I couldn't spot the difference, anyway.

Well, looking into the code, it seems drawtext/drawsymbol/drawnumber are the same thing/object (that is aliases that refer to the same drawnumber_new method). Code: 

static void drawnumber_setup(void)
{
    drawnumber_class = class_new(gensym("drawtext"),
        (t_newmethod)drawnumber_new, (t_method)drawnumber_free,
        sizeof(t_drawnumber), 0, A_GIMME, 0);
    class_setdrawcommand(drawnumber_class);
    class_addfloat(drawnumber_class, drawnumber_float);
    class_addcreator((t_newmethod)drawnumber_new, gensym("drawsymbol"),
        A_GIMME, 0);
    class_addcreator((t_newmethod)drawnumber_new, gensym("drawnumber"),
        A_GIMME, 0);
    class_setparentwidget(drawnumber_class, &drawnumber_widgetbehavior);
}

The fact they're aliases isn't clear in drawtext-help.pd yet, and it makes you think [drawnumber] and [drawsymbol] are different, whereas [drawtext] isn't mentioned.

Maybe I should open a new issue for that

**Pull request merged**
