### PR TITLE
Html doc updates to chapter 4

### PR DESCRIPTION
**Pull request by Lucarda**
This PR includes a new sections on **chapter 4** dealing with : "**how to install & load external objects**"  in to the HTML documentation.

It also changes the links colors to blue and without underline to make it more standard.

Here is a preview: http://lucarda.com.ar/pd-html-preview/index.htm (can be also nicely displayed on smartphones and tablets)

### CODE REVIEW

**Comment by porres** [comment]
yay! Not sure if you caught my latest edits that I'm now doing in a google docs file...

but I guess I can keep working on this now... and I guess we need to improve the quality of the pictures as well. Anyway, I don't really know of a good html editor or anything for macOS - never had to use any of this.

**Comment by porres** [comment]
some of the information on how to load externals is actually already addressed in https://github.com/pure-data/pure-data/blob/master/doc/1.manual/x3.htm

so including this information I developed separately should involve a more careful merge, where things don't get repetitive

**Comment by Lucarda** [comment]
>yay! Not sure if you caught my latest edits that I'm now doing in a google docs file...

No is not, is from about 8 hours ago

> I guess we need to improve the quality of the pictures as well

Sure (see below).

>I don't really know of a good html editor or anything for macOS - never had to use any of this.

open the .html file (`$pd/doc/1.manual/how-to-load-externals/index.html` in this case) with any plain-text editor, change it, save it, and hit refresh on the browser.
You can also make new images and save them with the same name and extension.

**Comment by porres** [comment]
> some of the information on how to load externals is actually already addressed in https://github.com/pure-data/pure-data/blob/master/doc/1.manual/x3.htm

I mean specifically "3.6. Preferences and startup options"

**Comment by porres** [comment]
> No is not, is from about 8 hours ago

I guess I'll keep working on google docs, and other people can help me there too, then in a few days I can come here and revise/update it.

**Comment by porres** [comment]
> I mean specifically "3.6. Preferences and startup options" and "3.7. How Pd searches for files"

these carry pretty old and outdated Pd screenshots, so it seems, probably best to update it, and maybe merge the whole thing I'm documenting in this very same section "3"

**Comment by Lucarda** [comment]
> these carry pretty old and outdated Pd screenshots, so it seems, probably best to update it, and maybe merge the whole thing I'm documenting in this very same section "3"

Sure, why not?
Let's wait for other's opinions.

**Comment by porres** [comment]
in "3.6. Preferences and startup options", where it says:

_

> The slots at top each specify a binary "library" for Pd to load on startup. These may be for Gem, pdp, zexy, iemlib, cyclone, and so on. Typically, a single binary object (an "extern") is left for Pd to load automatically; startup library loading is appropriate for collections of many objects specified by a single binary library.

_

maybe we can just point to the new documentation with a link, saying that this new section explains how to load externals in depth...

**Comment by porres** [comment]
Something like:

_The slots at top each specify a binary "library" for Pd to load on startup. Startup library loading is appropriate for collections of many objects specified by a single binary library, such as Gem, zexy, cyclone and others... See "xxxxxx" for more details._

**Comment by Lucarda** [comment]
>... such as Gem, zexy, cyclone and others... **See "xxxxxx" for more details**.

yep.

**Comment by porres** [comment]
"3.7. How Pd searches for files" looks trickier, as it's quite outdated as well. It'll require more hard work to think how to upgrade it and merge with the new information... and it would surely need some supervision of @millerpuckette  and other PD gurus...

**Comment by porres** [comment]
I guess what makes sense is this should come as #4, right after 3.6 and 3.7, and before "how to make externals" (which would then become #5!

**Comment by porres** [comment]
On second though, I can even see how that "writing Pd objects in C" could be merged into the new section. And this section must also contain several subsections and list them as "3." does.

It can be then just called "4. external objects", and the subsections could be indexed and detail what they discuss ("writing objects in C" / "internals vs externals" / "how to install" / "load", etc...)

**Comment by Lucarda** [comment]
> It can be then just called "4. external objects", and the subsections could be indexed

That's nice.

- external objects
  - writing Pd objects in C
  - how to install & load external objects

so the ch5 does not move to ch6.

**Comment by porres** [comment]
writing objects in C is basically just a pointer to @umlaeute 's tutorial... it could be one first item in the list for that. I'm thinking of this structure:

Screen Shot 2019-07-29 at 20 26 46

**Comment by porres** [comment]
or maybe this?
Screen Shot 2019-07-29 at 20 28 39

**Comment by Lucarda** [comment]
The second option looks good to me.
I will move everything to ch4.htm.

**Comment by millerpuckette** [comment]
Before you get too heavily into formatting details - I'm thinking of putting
the whole thing in markdown (to make it possible to put in equations and
eventually automate generating a table of contents) - the pilot project is
sitting in pd/md/ but I imagine this eventually expanding to generate a much
more expansive doc that would include the "manual" and many more "topics".

cheers
Miller

**Comment by Lucarda** [comment]
Ok, I'm stopping this PR. I will get Pandoc and start learning how to play with it as it looks further work will happen with markdown.

:)

**Comment by millerpuckette** [comment]
OTOH I can pull whatever changes you've proposed so far (I'd better look at
them :) - just be aware that reorganization might want to wait until there's
a pandoc/markdown structure figured out.

cheers
M

**Comment by Lucarda** [comment]
Closing this as the info can live as a pdf in puredata.info (as it currently does) and can later be included in the "markdown/pandoc reorganization".

**Comment by porres** [comment]
> (as it currently does) 

it doesnt, really

**Comment by porres** [comment]
> it doesnt, really

and I really, really, really, really think this should be a part of Pd's manual one way or another

**Comment by Lucarda** [comment]
Reopening. :)

**Comment by Lucarda** [comment]
Here's a preview  :http://lucarda.com.ar/pd-html-preview/index.htm

@millerpuckette this added info can pass when/if the "manual" is converted to markdown.

@porres : 
- can you provide new (better quality) images?
- can you push to this branch if there are corrections/edits?

**Comment by Lucarda** [comment]
@porres: I have updated the images using Linux and did corrections based on your current pdf.

It can be previewed [here.](http://lucarda.com.ar/pd-html-preview/x4.htm)

**Comment by porres** [comment]
Cool, this actualkly needs more work, but I can propose more changes to master now ;)

**Pull request merged**
