### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by porres**
This PR includes some documentation fixes and updates from newly added features

### CODE REVIEW

**Comment by porres** [comment]
sorry, I tried a few things to resolve conflicts and I just can't seem to update the pointer-help.pd file anymore. I had updated this before and now it just presents this resolving issue... 

@millerpuckette, hopefully you can manually include these commits. The documentation of the sort message was already included by the way. Besides that, what I have here is updates for:
- makefilename-help.pd
- pointer-help.pd
- help files of line/line~/vline~ 
- savestate-help.pd

**Comment by umlaeute** [comment]
the "sort" documentation was removed by you in 01be2915c397df4e083ef5796c4ee07b1a0bedd2.

as you have noticed, merging Pd-patches can be really tricky (this is the main reason why i avoid merging these changes into the `update/0.50` (or simile) branch - the possibility to get into hard to resolve merge conflicts is enormous).

however, you might simplify the task by minimising the diffs before committing them:

- e.g. many of your doc-cleanup commits just move the objects around slightly. this might be totally intended (nicer layout), or an unintentional side-product of editing the patch otherwise; or something inbetween.
    if the object-moving is not required, don't include them in the patch
- saving will usually move the any canvas slightly (that's a bug in Pd; good luck fixing it :-)); there is usually no reason to submit these changes (with the notable exception when a canvas used to be out-of-screen on a non-retina single-screen setup; here it is acceptable to move it back into well-behaved range)
- for typo fixes i find it is usually better to do the fix in a text-editor (ad not within Pd); this keeps the order of objects and connection indices intact, which can reduce the diff from a couple of hundred lines to just one.

you should *always* review the changes before submitting them.
that is: use some graphical interface (e.g. `git gui` or something more fancy)  to actually look at the diff. this makes it much easier to spot vanishing paragraphs.

you should *always* explain your intentions in the commit message.
`Update text-object-help.pd` doesn't tell us anything we don't already know by running `git show --name-only 01be2915c397df4e083ef5796c4ee07b1a0bedd2`.
But it doesn't tell us what the patch is supposed to fix. Looking at the diff (a couple of months later; with *my* brains in the head rather than *yours*) it seems that:
- you moved objects around (presumably to align them)
- changed the width of some number-boxes and comments
- removed the "sort" documentation
- removed some messages from the `search` documentation (???)

**Comment by porres** [comment]
> e.g. many of your doc-cleanup commits just move the objects around slightly. this might be totally intended (nicer layout), or an unintentional side-product of editing the patch otherwise; or something inbetween.
> if the object-moving is not required, don't include them in the patch

Such nicer layout was intentional before, but all of that has already been merged. These new documentation updates are only for adding data and fixing issues.

> you should always explain your intentions in the commit message.

This has been done in the commits here, up to https://github.com/pure-data/pure-data/pull/829/commits/3d1ae2cd5aff9e7303ee93ab790d84ba19790f51 then I just got into a mess trying to resolve conflicts.

But anyway, I see from your explanation what's happening here. The only issue is with pointer-help.pd where I documented the "equal" message. I'll try to add it to the file from master and just include that info (in a subpatch) without messing with much else. I see how changing something slightly as the patch window may ruin this.

**Comment by porres** [comment]
Ok, thanks to @umlaeute 's hints and tips, I was able to resolve conflicts (thanks!)

sorry for the noise with some unnecessary commits, but here's the aftermath so far, with details

- makefilename-help.pd => changes according to https://github.com/pure-data/pure-data/issues/549 (mainly change the description of %p)
- pointer-help.pd = > document "equal" message,  replaces https://github.com/pure-data/pure-data/pull/811
- help files of line/line~/vline~ => imporoved information on what the secondary inlets set, see discussion in https://lists.puredata.info/pipermail/pd-list/2020-03/127077.html
- savestate-help.pd => closes https://github.com/pure-data/pure-data/issues/934
- expr-help.pd => better explanation on how to deal with '$0'

I'm omitting the commit about documenting the sort message because that's already solved in master.

To avoid further issues, I'll emphasize this could be merged ASAP by @millerpuckette

**Comment by porres** [comment]
well, no idea why one of the tests failed :) I just changed the help file of makefilename

**Comment by porres** [comment]
as of https://github.com/pure-data/pure-data/pull/829/commits/978606e16d404eb99e935bec3b424f97b5c3673c I'm now updating the help files of iemguis as proposed in https://github.com/pure-data/pure-data/pull/937 to document the new way of setting colors. This has to be reviewed first so I can go on and do the same for other iemguis.

The new changes to https://github.com/pure-data/pure-data/pull/829/commits/1e2db7633e11ba9ea58955e77f7dc55f139a48e5 also need revision by the way

**Comment by porres** [comment]
ok, it's impossible to do any changes to out1~ I'm reverting the commits

**Comment by porres** [comment]
ok, it's impossible to do any changes to out1~ it always have conflicts, last time I was able to resolve them with a hint, not working now. Maybe miller can check on this abstraction and the changes/discussion I'm proposing to decide what to do anyway...

**Comment by Spacechild1** [comment]
tip: with `git revert` all commits stay in the history. if you want to get rid of the last N commits for good (erase them from history), you can do `git reset <last valid commit>` and then force push:
```
git reset 210b4c9
git push --force
``` 
This will erase all commits after 210b4c9.

By default, `git reset` will keep your local changes, while `git reset --hard` even gets rid of those.

**Comment by porres** [comment]
I was able to make a new commit with no conflicts in a new branched, where I merged this one into... so I'm closing this and now we can only have https://github.com/pure-data/pure-data/pull/1036 instead

**Pull request closed without merging**
