### PR TITLE
document "click" and "close" methods in [text define]

### PR DESCRIPTION
**Pull request by Spacechild1**

### CODE REVIEW

**Comment by porres** [comment]
I can't believe I just opened an issue suggesting to include such features and found out they already exist and weren't documented, what are the odds? :)

**Comment by porres** [comment]
oh, can you update your help files to sat "changed for Pd 0.48-2" and stuff?

**Comment by Spacechild1** [comment]
it already says "updated for Pd 0.48", no need to include the bugfix version number. [soundfiler], [noise~] etc. don't either.

**Comment by porres** [comment]
> no need to include the bugfix version number. [soundfiler], [noise~] etc. don't either.

well, I think they actually do or should, as I've seen many updated help files with bugfix version number, and I've also been explicitly suggesting and doing this with no resistance.  See the help of [midiin], [expr], for instance.

**Comment by Spacechild1** [comment]
OK, but I guess Miller will update the version number whenever he merges this.

**Comment by porres** [comment]
I wouldn't say that's guaranteed to happen, and probably easier and more guaranteed if you do it yourself. 

Now, I can't also be the one say what's the criteria for changing number versions on the help update. Is it supposed to mean the object was updated only? I figure and guess it could say either the documentation has (significantly) changed, the object, or both. But that's something for @millerpuckette  to answer

**Comment by umlaeute** [comment]
included in `update/0.48-2`

**Pull request closed without merging**
