### PR TITLE
revert audio settings behavior

### PR DESCRIPTION
**Pull request by Spacechild1**
This PR does the following:

1) Apply audio settings after argument parsing, so that objects will immediately see the specified sample rate or channel count, even if DSP hasn't been started yet.
A prominent example is `[samplerate~]`. A patch might precalcalculate things that are sample rate dependent. If the default sample rate is different from the saved sample rate, it would have to recalculate everything again after DSP has been started.
Other patches (wrongly) assume a fixed sample rate and only bang `[samplerate~]` once during load time. Starting with a different sample rate than the one saved by the user can break such patches.

2) Revert the default sample rate to 44100.
44100 Hz has been the default sample rate for ages and I don't think it is a good idea to change it without a very compelling reason.
Many patches rely on the default sample rate. Yes, they are probably buggy, but IMO we should still try to avoid breaking them if possible.
Also, certain patches can't be written in a sample rate independent manner. For example, `[readsf~]` can't resample, so it only works with the sample rate of the accompanying sound files. If you ship such a patch, you would now have to tell the user to change the sample rate or supply a script with starts Pd with "-r 44100". Older existing projects would simply break.

Fixes https://github.com/pure-data/pure-data/issues/1429

NOTE: I am fully aware that a well behaved Pd patch should dynamically react to sample rate changes, e.g. with `[r pd-dsp-started] -> [samplerate~]`, but in reality many people haven't been aware of the problem. I assume that there are *many* Pd patches that (wrongly) assume a fixed samplerate.

### CODE REVIEW

**Comment by Lucarda** [comment]
This VOTE took me some time and I don't want to be impartial.

"revert default samplerate to 44100"

+1

**Comment by reduzent** [comment]
I think that many patches (wrongly) assume a fixed samplerate and check it only once at launch time is a strong point. It would be friendly not to break them.

**Comment by millerpuckette** [comment]
ok - friendliness here trumps correctness :)

**Comment by Spacechild1** [comment]
will fix the merge conflict

**Pull request closed without merging**
