### PR TITLE
don't draw [vu]'s outlets

### PR DESCRIPTION
**Pull request by porres**
This is one solution that came up in #632 and closes it.

Another solution to that issue would be to add a send symbol and a new extra argument. But the discussion led to this solution as probbaly easier and more sensible.

In practice, this hides the outlets without removing them for backwards compatibility concerns. The object keeps its outlets, but these are undocumented and maybe no one ever used them anyway as there doesn't seem to be much of a point in using them...

If this PR is not accepted I can work on the other solution (adding a send symbol).

### CODE REVIEW

**Comment by umlaeute** [comment]
> but these are undocumented and maybe no one ever used them anyway as there doesn't seem to be much of a point in using them...

hmm, well. they used to be documented (before your PR). so why do you think that nobody is using them? and why do you think they were added (and even documented!) in the first place, if there's not point in using them?

anyhow: your patch could also be simplified *a lot* by just forcing `x->x_gui.x_fsf.x_snd_able = 1;` (either changing the 2 lines in `vu_dialog` and `vu_new`; or introducing a single new line somewhere in `vu_draw_io`).
personally i'm not a big fan of patches that just uncomment chunks of code (as this is the best way to accumulate cruft), but your mileage my vary.

**Comment by porres** [comment]
> why do you think they were added (and even documented!) in the first place

I never really said that

> hmm, well. they used to be documented (before your PR). so why do you think that nobody is using them? 

I agree this is ugly but it was one idea that felt best and was suggested to me in the discussion in https://github.com/pure-data/pure-data/issues/632

But now I have a new idea, which is just hide the outlets when you give it a send symbol.

**Comment by umlaeute** [comment]
> > why do you think they were added (and even documented!) in the first place
> 
> I never really said that

no of course not.

the course of action is more like:
- the outlets are currently (as in: Pd-0.49-0) drawn, so somebody must have added them
- the outlets are currently documented in the help-patch, so somebody must have written that documentation
- you said that there doesn't seem to a reason to use them ("there doesn't seem to be much of a point in using them...")
- I asked you, why you think that somebody made the effort to both write code to display them *and* to document that feature if they are useless.

just because you (or me, or somebody else) doesn't see an immediate benefit in a feature, doesn't mean that nobody reasoned about it (and came to a certain conclusion).

**Comment by porres** [comment]
closing this in favor of https://github.com/pure-data/pure-data/pull/654

**Pull request closed without merging**
