### PR TITLE
trackable print

### PR DESCRIPTION
**Pull request by Ant1r**
This allows to ctrl-click on the messages in the Pd console, to find to corresponding [print] object (e.g to remove [print]s scattered all over the patch...).

It needed to add a new public function "logpoststring()" in m_pd.h, that just prints the string (associated to the object address) without a newline.

### CODE REVIEW

**Comment by danomatika** [comment]
This branch is now up to date.

**Comment by umlaeute** [comment]
why couldn't you just use `logpost()` instead of `logpostprint()`?
at least here, i can do:

~~~
logpost(x, 2, "foo");
~~~

which is identical (but 5 letters less to type) to:

~~~
logpostprint(x, 2, "foo");
~~~

**Comment by umlaeute** [comment]
ah, re-reading i see this is about the newline.
i'd still recommend using a `printf()` like format string instead of only allowing a single `const char*`.
for consistency with already existing functions (`startpost()`, `endpost()`), I guess `logpostprint()` could be changed to:

~~~
EXTERN void startlogpost(void *object, const int level, const char *fmt, ...);
~~~

the `endlogpost()` could probably be emitted (clicking on a newline might be really hard).

**Comment by Ant1r** [comment]
Actually almost every "post" would need to have its equivalent:
```
void startlogpost(const char *fmt, ...);
void logpoststring(const char *s); //(this one could be avoided in that case, it wouldn't be used anymore by [print])
void logpostfloat(t_floatarg f);
void logpostatom(int argc, t_atom *argv);

``` 
I agree that it could be more consistent. I agree to amend this PR in this way, if you think so.

**Comment by Ant1r** [comment]
This branch has been brought up to date.

Not sure why Github reports conflict though; looks like someone (owning admin rights) just needs to push the `Mark as resolved` button in the `Resolve conflics` dialog (where the diff seems broken here)?

**Comment by Ant1r** [comment]
This branch has been updated (I had to solve a conflict again...).

**Comment by Ant1r** [comment]
@millerpuckette I think this small one could be good to have too ;-)

**Comment by millerpuckette** [comment]
Cool... I was meaning to go look for this and you saved me a search.  I want
to use this (or something similar) for reporting stack backtraces.

cheers
M

On Wed, Jul 14, 2021 at 03:00:12AM -0700, Antoine Rousseau wrote:
> @millerpuckette I think this small one could be good to have too ;-)
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pure-2Ddata_pure-2Ddata_pull_464-23issuecomment-2D879761297&d=DwICaQ&c=-35OiAkTchMrZOngvJPOeA&r=XprZV3Fxus2L1LCw80hE4Q&m=gUTux4d4ahGU_YMRRfXC11vo5DCCi6u4ts7BCnH_7DI&s=UomXmPvMcUb8W2jGiTosLxs3k3Z1pU_eTmf2b30RjAA&e= 

--

**Comment by millerpuckette** [comment]
It's in there... but I seem to have dome something wrong - ctrl-clicking
on "print" output does nothing for me yet.

cheers
M
On Wed, Jul 14, 2021 at 03:00:12AM -0700, Antoine Rousseau wrote:
> @millerpuckette I think this small one could be good to have too ;-)
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pure-2Ddata_pure-2Ddata_pull_464-23issuecomment-2D879761297&d=DwICaQ&c=-35OiAkTchMrZOngvJPOeA&r=XprZV3Fxus2L1LCw80hE4Q&m=gUTux4d4ahGU_YMRRfXC11vo5DCCi6u4ts7BCnH_7DI&s=UomXmPvMcUb8W2jGiTosLxs3k3Z1pU_eTmf2b30RjAA&e= 

--

**Comment by umlaeute** [comment]
works here (with f16dd5ec34d4ac2e508d4878676c8fa05512540b)

**Comment by Ant1r** [comment]
cool! I find this really useful (and I confirm it works here too using master branch).

BTW I'm wondering if ctrl-clicking on the console is promoted enough, I suspect many people don't know that, though IMO it's a great feature for developers.
Is it only documented somewhere?
Maybe @porres, the documentation doctor, knows about it?

cheers

**Comment by porres** [comment]
> BTW I'm wondering if ctrl-clicking on the console is promoted enough, I suspect many people don't know that, though IMO it's a great feature for developers.

what do you mean? :)

**Comment by Ant1r** [comment]
I mean, do you know if the feature:
 ctl-click a line in the Pd-console to find the object that printed this line
is documented somewhere, and sufficiently well known?

**Comment by porres** [comment]
well, I never knew you could do that :) I was assuming this is something you could do with this PR...

**Comment by Ant1r** [comment]
That's what I thought ;-)
I personally couldn't live without it!

**Comment by Ant1r** [comment]
This PR was about allowing this also for [print] messages to ( and potentially other "normal" messages from any object too). Previously only errors sent with pd_error() were trackable.
The tracking via "Find last error" is well known, because advertised in the console when it prints it's very first error, but right-clicking the error (including older ones) isn't advertised. 
Maybe we could just change this advertisment message.

**Comment by millerpuckette** [comment]
It would be a Good THing if trackable lines in the Pd window were diistinguished
graphically so that you'd know when/where you can usefully click.

cheers
M

On Thu, Jul 15, 2021 at 03:17:17PM -0700, Antoine Rousseau wrote:
> This PR was about allowing this also for [print] messages to ( and potentially other "normal" messages from any object too). Previously only errors sent with pd_error() were trackable.
> The tracking via "Find last error" is well known, because advertised in the console when it prints it's very first error, but right-clicking the error (including older ones) isn't advertised. 
> Maybe we could just change this advertisment message.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pure-2Ddata_pure-2Ddata_pull_464-23issuecomment-2D881046711&d=DwICaQ&c=-35OiAkTchMrZOngvJPOeA&r=XprZV3Fxus2L1LCw80hE4Q&m=efk3mf8xnCjxb2hKpOyBI7xw_6px3EJFtz2rXoiT_iY&s=a76_ZQvio7iJnDclGCoT9A8HHITo7pJiaDRrWNJnkg0&e= 

--

**Pull request merged**
