### PR TITLE
Update pt_br.po

### PR DESCRIPTION
**Pull request by porres**

### CODE REVIEW

**Comment by umlaeute** [comment]
oops, i accidentally merged this into `master` (as this was the *target* branch).

i've reverted (and force-pushed) this accidental commit, but this means that the PR is now closed.

I could of course just merge this PR manually into the `i18n` branch, but it conflicts.
it conflicts, because it is based on `master`, rather than `i18n`.
And `i18n` and `master` have a conflict because I manually merged #1774, resolving conflicts there.

I would like to avoid putting more extra work in this translation, so @porres could you pretty please follow the instructions in https://github.com/pure-data/pure-data/pull/1780#issuecomment-1281606057 (i know that I said "all is good", but it seems like I only had "item 2" in my mind when I said that) ?
and create *yet another* PR? (by now, I guess the translation work is almost automatic :-P)

sorry for all the trouble (but its also a bit exhausting for me)

**Comment by umlaeute** [comment]
> oops, i accidentally merged this into `master` (as _master_ was the _target_ branch, instead of _i18n_).
> 

that might also be the reason why you cannot create PRs:
you are working from the wrong base (`master`), and therefor your branch simply conflicts with `i18n`.
please use `i18n` as the starting point (or use weblate)

**Comment by porres** [comment]
I was using i18n as the base. I just made another revision from the latest commits in there. Here's what I get when trying to send the PR

Screen Shot 2022-10-18 at 14 03 53

Anyway, here's my new revision edit from poedit. Since it's all so hard and complicated right, would it work if you just got this file here and uploaded it?

[pt_br.po.zip](https://github.com/pure-data/pure-data/files/9813538/pt_br.po.zip)

**Comment by umlaeute** [comment]
You might just use the webinterface (like everyone else) instead of the app...

**Comment by Lucarda** [comment]
@porres you can go to your fork and create a pull request from there. Then adjust the branches:

pr

**Comment by porres** [comment]
> You might just use the webinterface

can I try next time? I think I'm really done for now and the file is up there and ready, I hope you can take it.

@Lucarda: I was in my fork

**Comment by Lucarda** [comment]
> I was in my fork

In your web interface? https://github.com/porres/pure-data/pulls

**Comment by Lucarda** [comment]
the pic from above is in the web interface.

**Comment by porres** [comment]
I'm not failing at making the PR, the fail is trying to push the commit. Anyway, I hope @umlaeute  can take the file in https://github.com/pure-data/pure-data/pull/1782#issuecomment-1282736863

**Comment by porres** [comment]
@Lucarda, if you have no problems making a proper PR, would you be able to get my file above and provide one?

**Comment by Ant1r** [comment]
1. go https://github.com/porres/pure-data
2. select pt_br branch
3. github says: "This branch is [1 commit ahead](https://github.com/porres/pure-data/compare/pure-data:pure-data:master...pt_br) of pure-data:master."
4. click "Contribute"/"Open Pull Request"
5. change target branch "base" to "i18n"
6. Create Pull Request
Capture d’écran du 2022-10-20 15-58-08

**BUT**: github says "Can't merge automatically" so it seems there is a conflict. Try to merge upstream/i18n to your local git repo to see what's going on.

**Comment by porres** [comment]
>  Try to merge upstream/i18n to your local git repo to see what's going on.

I already tried, I have the latest i18n in my repository... I don't know what's going on, but I have made such a new PR the way you suggested in  https://github.com/pure-data/pure-data/pull/1791 with yet a new commit with the last update work I had done...

**Comment by porres** [comment]
apparently there were some conflicts that I solved

**Comment by porres** [comment]
hmmm, weird, it seems that all the work I had done has already been actually merged as after resolving conflicts I see nothing really new... at least not much new.

**Comment by porres** [comment]
Well, ok, there's at least one important fix and it seems now that the translation is finally ok and 100% completed... please confirm if it is all ok @umlaeute 

thanks everyone

**Pull request merged**
