### PR TITLE
added es.po

### PR DESCRIPTION
**Pull request by fdch**
Hi everyone, here's a spanish version (following the steps of @porres, and @danomatika's recommendations on the list). 

I tested everything and it does seem to work fine. I'd suggest double-checking with spanish speaking users, just to be sure. I can make quick changes if anything, all done in OmegaT

Please, let me know if i messed something up or whatever. I couldn't find previous spanish versions.

### CODE REVIEW

**Comment by danomatika** [comment]
Can you make this to the update/test3-fixes branch? I think there are a few extra translation strings added there.

**Comment by fdch** [comment]
Shoot! I thought i was there, let me see now

**Comment by danomatika** [comment]
One you clone, you need to checkout the branch. Then when you commit & make the PR, select it as the target branch instead of master. We don't commit directly to master as Miller handles that upstream.

**Comment by fdch** [comment]
Thanks for that! I'm now in that branch, making changes, i'll push to that branch when i finish

**Comment by porres** [comment]
2017-07-20 22:03 GMT-03:00 Fede Camara Halac <notifications@github.com>:

> Hi everyone, here's a spanish version (following the steps of @porres
> <https://github.com/porres>,
>

what do you mean? hope you didn't get my translations as a basis, I'm still
100% unsure of many things ;)

**Comment by fdch** [comment]
Haha, no, your initiative ;)

Just to be sure, i am definitely on the branch now, since I just translated many deken strings.

now, all i do is "
git push -u origin update/test3-fixes 
" or is it something else?

**Comment by danomatika** [comment]
Assuming you're in your fork and did a checkout of the branch, all you should need to do is add the file, make a commit, then push.

Next, you'll want to close this PR and open a new one from your branch on GitHub.

**Comment by danomatika** [comment]
You can also see which branch you are on with:

    git branch

**Comment by fdch** [comment]
Huge thanks! git branch told me 
  master
* update/test3-fixes

so i just pushed.

**Pull request closed without merging**
