### PR TITLE
Fixed two typos

### PR DESCRIPTION
**Pull request by idonotfollowyou**

### CODE REVIEW

**Comment by porres** [comment]
I will create a new documentation branch PR and include this there, ok? I will let you know when that happens so you can close this, thanks!

**Comment by idonotfollowyou** [comment]
Ok. My git/github experience is minimal. I'm currently reading through the documentation and imagine I will uncover more stuff that could be fixed. I'm not sure how I should approach the next stuff.

**Comment by porres** [comment]
if I haven't yet created a new documentation PR (I will let you know when that happens) keep doing what you did here

**Comment by idonotfollowyou** [comment]
Changing workflow. Going to tidy up by closing this and #1810 
I will create another documentation typos PR

**Pull request closed without merging**
