### PR TITLE
live dialog updates

### PR DESCRIPTION
**Pull request by danomatika**
**_This is a reference PR. Do not merge._**

Updates to dialog boxes for live updates on OS X since the Apply button has been removed to better match Apple's Human Interface Guidelines. Also includes updates for better keyboard editing.

Approach:

* entry boxes apply changes when Return is pressed after editing
* checkbuttons & radio buttons send changes
* focus is removed from Ok button (aka Return to exit) when editing an entry box
* OK button takes focus when entry editing is finished
* remove widgets from focus list if they do not highlight on focus

TODO:

* find a way to highlight check buttons & radiobuttons when focused 

Dialogs done so far:

* dialog_atom.tcl
* dialog_canvas.tcl

Related discussion:

* [[PD-dev] Canvas Dialog Apply](http://lists.puredata.info/pipermail/pd-dev/2015-11/020478.html)
* [number and symbol atom properties dialog width text field not selected](http://sourceforge.net/p/pure-data/patches/565/)

[WIP screengrab video](https://www.youtube.com/watch?v=PZCjgIFMc9g):

[WIP screengrab video](http://www.youtube.com/watch?v=PZCjgIFMc9g)

### CODE REVIEW

**Comment by danomatika** [comment]
Closing this branch as I've merged this work with the iemgui-dialog-cleanup branch.

**Comment by umlaeute** [comment]
i deleted this branch (d93ae85be79dfdbc1599f98c9f46c0dfa77b86ce) as it has been merged into master and there is little use in keeping dangling branches around.

**Comment by danomatika** [comment]
Ok cool. I was waiting for Miller to say he already merged it.

**Comment by danomatika** [comment]
Whoops. Forgot to do that myself after the merge.

**Pull request closed without merging**
