### PR TITLE
Update pt_br.po

### PR DESCRIPTION
**Pull request by porres**

### CODE REVIEW

**Comment by Ant1r** [comment]
that failed: `po/pt_br.po:816: trailing whitespace.`

**Comment by porres** [comment]
yes, but I couldn't actually find the offending whitespace! I hope someone here can help me and get the work I've done in, @umlaeute ?

**Comment by porres** [comment]
> can you see (and access) the "details" link besides the checks? 

yup, and I had seen the details and that it complained about trailing whitespaces, but I couldn't find any so I couldn't fix it

**Comment by umlaeute** [comment]
however, what i find more concerning, is that the file is actually broken (as in: fails to build).

e.g. in https://github.com/porres/pure-data/blob/659ec76c8e8b10f9f8f2a42315fb9b900628a718/po/pt_br.po#L158-L160 the `msgstr` went missing.

do you edit these files by hand?
if so: you probably shouldn't, and instead use `poedit` (or the experimental [weblate](https://hosted.weblate.org/projects/pure-data/pure-data/).

and i have to fix the CI-runs so they actually check whether the translation files are faulty.

**Comment by umlaeute** [comment]
i fixed the CI so it now fails with broken translation files :-)

**Comment by umlaeute** [comment]
> but I couldn't find any so I couldn't fix it

the logs show the line with the trailing whitespace:
- https://github.com/porres/pure-data/blob/659ec76c8e8b10f9f8f2a42315fb9b900628a718/po/pt_br.po#L748
- https://github.com/porres/pure-data/blob/659ec76c8e8b10f9f8f2a42315fb9b900628a718/po/pt_br.po#L816

as usual, whitespace is hard to see (but if you select the `msgstr` + the following line it becomes apparent that there's a space.

**Comment by porres** [comment]
> do you edit these files by hand?

yeah, I did. And then I actually went here and edited the file itself from the repository and copied the text over it, because I wasn't being able to do a proper PR. I can't seen how editing the file in the repository breaks it...

> if you select the msgstr + the following line it becomes apparent that there's a space

I don't know what this means :/ I'm thrown off specially by 'msgstr'

one way or another, would you be able to 'fix' or get the text I worked on and have it in? Next time I'll make sure to use the proper tools

**Comment by umlaeute** [comment]
rebased, fixed and merged.

**Comment by porres** [comment]
ok, I'll revise it

**Comment by porres** [comment]
> ok, I'll revise it

@umlaeute it's here -> https://github.com/pure-data/pure-data/pull/1780

**Pull request closed without merging**
