### PR TITLE
stable development branch

### PR DESCRIPTION
**Pull request by umlaeute**
this is meant as a successor of the update/0.51 and similar PRs (where it was always a bit awkward to have the Pd target-version embedded).

the idea is to have a permanent branch develop that only gets curated, small, no-brainer changes that can be easily merged into master at any time.

PS: if anybody can explain how to create PRs that are kept open after merging (or at least: can be opened again after merging), that would be fantastic. (it's a bit boring to re-open this PR after each release ;-))

PPS: supersedes #1105

---

Fixes included (this list should get updated whenever a new fix is included. keep in mind that updating the list might be forgotten though...)
- GUI-stuff
  - #814 (tcl-error when updating a closed GOP)
  - #1152 (some keyboard shortcuts don't work with <kbd>CapsLock</kbd> on
  - #1158 (Tcl error and freezes when using an out-of-range value for setting the color of iemguis)
- audio stuff
  - #1163 (Pd hangs when quitting with a callback scheduler)
  - #1162 (Pd segfaults if jackd has a blocksize that is smaller than `DEFDACBLKSIZE`)
  - #1110 (not enough audio/midi devices displayed in the menu)
- compilation stuff
  - refined check for MSVC supporting `stdint.h`
  - allow building a fresh-clone with the non-autotools makefiles (#1161 , see also https://git.iem.at/pd/pure-data/-/pipelines for automatic builds on a number of OSs/architectures/build-systems)

### CODE REVIEW

**Comment by Lucarda** [comment]
> PS: if anybody can explain how to create PRs that are kept open after merging (or at least: can be opened again after merging), that would be fantastic. (it's a bit boring to re-open this PR after each release ;-))

I just wanted to delete a merged branch and next to the delete button there`s another to create another "pull request".

Also on my branches I have a button to create a new PR.

Both methods untested.

**Comment by Lucarda** [comment]
PS: I forget to mention that this buttons appears on the web interface.

**Comment by umlaeute** [comment]
well, this is what i'm already doing.
i was wondering how to keep the PR open once its merged, not how to create a new one (like *this*)

**Comment by millerpuckette** [comment]
Unless there's a reason not to, I'll just merge this now and call it 0.51-3test - I have a couple of pd~ and expr fixes that should go out soon, and some of these look like they should too.  (And none of them look dangerous at all :)

**Comment by umlaeute** [comment]
i think it's fine.
(after all, the this PR is supposed to always be mergeable as-is)

**Pull request merged**
