### PR TITLE
escape curlies

### LINKED ISSUE #615: [print] adds a backlash
Hi, when using '\' to escape a character like ',' or something, the [print] object actually adds another backlash that's not in there. I think this is a bug, right? Or is there a reason why it has to be this way?

Screen Shot 2019-05-02 at 13 41 01

### PR DESCRIPTION
**Pull request by umlaeute**
this PR is to allow the printout of objects/msgboxes/comments/symbolboxes that contain curly braces without locking up Pd.

A simple test-patch to lock up Pd is like this:

~~~
[123(
|
[list tosymbol]
|
[symbol\
~~~

this (displaying an open curly "`{`" on a patch-canvas) locks up the receiving thread in the GUI, until a matching `}` is received.
to the user it just locks up Pd.
if the patch is currently "dirty", Pd won't react on <kbd>Ctrl</kbd>-<kbd>Q</kbd> anymore (as this requires the GUI to pop up a window), although it would react on <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>Q</kbd> (but not everybody knows about this).

what the patch does:
- make the already existing `pdgui_strnescape()` non-static, so it can be used for escaping object-labels.
  - this also adds a new argument to the `strnescape()` function for the size of the destination buffer (rather than just assuming that the destionation buffer is big enough; you can still pass `0` as the size for the old behaviour)
 - as a quick recap: the `strnescape` function replaces `('{', '}', '\')` with `('\{', '\}', '\\')` and is already used for escaping curlies and backslashes for Pd-console messages.
- use this `pdgui_strnescape()` when creating/renaming objects (via `rtext_senditup()`)
   - i'm sure this could be done more efficiently, as `rtext_senditup` already mangles the buffer.
- once the label has been received successfully on the GUI-side, it is unescaped
   - this now also happens for messages to the Pd-console (prior, printouts where escaped before sending them up, but never unescaped; Closes #615).

### CODE REVIEW

**Comment by Spacechild1** [comment]
> use this pdgui_strnescape() when creating/renaming objects (via rtext_senditup())

does this mean we can type curly braces in object boxes and symbol atoms? (for some reason, you already can in [text define])

**Comment by umlaeute** [comment]
not that this PR does not fix #622, even though it is closely related. (i gave up, not wanting to put the same code again and again in about 60 or so places; iemguis ought to be modularized first)

**Comment by umlaeute** [comment]
@Spacechild1 this PR only fixes the display of curly braces. it's "unrelated" (well, it's a prerequisite) to the *input* of such characters.

so to answer your question: no.

**Comment by umlaeute** [comment]
merged with c037533e2f3515598f17c0a339f54e1258c32c0a

**Pull request closed without merging**
