### PR TITLE
bugfix: iemgui labels (display and dialog)

### PR DESCRIPTION
**Pull request by umlaeute**
this PR fixes various problems with iemgui labels:
- https://github.com/pure-data/pure-data/issues/622
- https://github.com/pure-data/pure-data/issues/1559
- https://github.com/pure-data/pure-data/issues/1562
- the various state buttons are now pulldown-menus, which makes it a lot clearer what the current state is and what the other possible states are.

while doing so, i couldn't refrain from cleaning up the iemgui code *a bit* (don't get overly excited):
- use understandable variable names (fix questions like: "What's `rng_sched`?" or: "Why does setting `var_iemgui_lin0_log1` to *1* show *`scale`* in a vu-meter?")
- use tcl-arrays rather for resolving per-window variables, rather than `eval` indirection
- use shared (but private) functions in the core for doing the same-same thing (like: opening up a dialog)

the iemgui dialog code is still ugly, but a bit less cringy (at least the tcl/tk part of it)

things unresolved so far:
- backslash in labels somehow gets lost when saving
- ~~the various state-buttons should be replaced with radiobuttons/pulldown-menus (i can *never* remember whether <kbd>linear</kbd> means  that the fader is currently in *linear* mode, or whether it's going to be linear if I click it. using buttons that change their labels also makes problems with the layout (as the label width changes)~~

---

this PR includes all the changes from #1633 (which closes about a dozen iemgui related issues)

---

this PR has merged the current master which includes [#1696 Refactor TCL-specific string handling into pdgui_vmess()](https://github.com/pure-data/pure-data/pull/1696), and has been updated to use the new `pdgui_vmess()` function for the communication with Pd-GUI.

### CODE REVIEW

**Comment by danomatika** [comment]
Yeah, I can never remember what state the damn push buttons are in. Radio, drop down, of checkbox would be better.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
ok, i've implemented the pulldown menu for states.
it still resizes dynamically here, depending on the length of the label of the selection, but that's not really a regression (aka: it did that before as well...)

**Comment by umlaeute** [comment]
i've retracted the PR to "draft" state as currently there's some regressions


- a sr-name with spaces (not that I would advise anybody to use *that*) like `foo bar` will be **displayed** as `foo\ bar` in the dialogs
  - a label with spaces (again `foo bar`) is displayed correctly
- a label with $args (e.g. `$0-foo` will be **saved** in the expanded form (e.g. `1003-foo`)
  - a sr-name with $args (again `$0-foo`) is saved correctly

**Comment by umlaeute** [comment]
the issues with $args in labels and spaces in send/receive names are now resolved, i'm thus marking this PR as ready to merge.

it has also been rebased on #1633 (as both PRs deal with iemguis, and they collided a bit)

**Comment by umlaeute** [comment]
no idea why github shows this as unmergeable: i've just merged the `improvement/merge-iemgui` branch into this branch and resolved all the conflicts manually with 6ade4c783d289ab6fd842aa9cff423a2be24d809 - this also includes a merge with today's `master` in the merge-commit 8812c1b090b0d41ed6b9e7ec9d862acbb2213e81, so there shouldn't be any conflict.


@millerpuckette i would prefer this PR to be merged in favour of #1633 (which is only a subset).

obviously, the merging would need to be done manually.

**Pull request merged**
