### PR TITLE
use more 'const' qualifiers in functions (and t_symbol)

### PR DESCRIPTION
**Pull request by umlaeute**
this PR adds `const` to a lot of exported functions, allowing the compiler to perform better optimisations and the userdev to write safer code.

it also declares the `s_name` member of t_symbol to be `const` (which it really is; i've seen crashing bugs in the last 15 years, because people would start to modify the string they get from a symbol)

### CODE REVIEW

**Comment by danomatika** [comment]
Sounds good. Eliminate failure sources *before* runtime...

**Comment by danomatika** [comment]
When this is further along, I should test it against libpd.

**Comment by pierreguillot** [comment]
Perhaps I'm wrong but if you change the prototype of the functions in *m_pd.h*, the externals that use these functions won't be compatible anymore. Am I right or wrong?

**Comment by danomatika** [comment]
The won't build only if they are trying to do things the API really shouldn't support, such as modifying const things.

**Comment by pierreguillot** [comment]
I have supposed that the loading results "unresolved external symbol" because the prototypes of the functions has changed so what you tell is that const doesn't make any difference for this.

**Comment by umlaeute** [comment]
@pierreguillot  the problem would only exist if the declaration where exported in a C++-context (where the names get mangled to hold a signature of the actually passed types in order to support polymorphism).
Since Pd's API is only C (and therefore all its symbols are explicitely *not* mangled for polymorphism), there shouldn't  be a problem.

**Comment by pierreguillot** [comment]
Thanks for the clarification :)

**Comment by danomatika** [comment]
Can we bring this up to date for the 0.49 release cycle?

**Comment by umlaeute** [comment]
it would probably be simpler to restart from scratch, but i might want to give it a try.

the problem with this patch is that it is quite evasive and thus fragile.

**Comment by millerpuckette** [comment]
merged.  This touched a lot of lines so will probably cause merge conflicts with other PRs, but if I delayed merging this it would be the other way around I think,

**Comment by umlaeute** [comment]
thanks for merging. indeed the touching of so many lines was the main problem with keeping this PR mergable in the first place.

**Pull request merged**
