### PR TITLE
Fix typo - help files

### PR DESCRIPTION
**Pull request by pierreguillot**
Fix the typo (and change the font size) of some help files, the name of the commits are explicits so you can do it manually if you prefer.
- [ ] operators-help.pd: funcitons -> functions
- [ ] abs~-help.pd: change font size from 10 to 12
- [ ] acoustics~-help.pd: THey -> They
- [ ] until-help.pd: change font size from 10 to 12

### CODE REVIEW

**Comment by danomatika** [comment]
Damn, I missed some. Thanks. Let us know when this PR is ready.

**Comment by umlaeute** [comment]
~~~
$ find * -type f -name "*.pd" -exec spellintian {} + | grep -v duplicate
doc/7.stuff/tools/testtone16.pd: wierd -> weird
doc/7.stuff/tools/testtone.pd: wierd -> weird
doc/5.reference/vradio-help.pd: COMPATIBILIY -> COMPATIBILITY
doc/5.reference/hslider-help.pd: COMPATIBILIY -> COMPATIBILITY
doc/5.reference/namecanvas-help.pd: itsef -> itself
doc/5.reference/delay-help.pd: miliseconds -> milliseconds
doc/5.reference/clone-help.pd: mumber -> number
doc/5.reference/hradio-help.pd: COMPATIBILIY -> COMPATIBILITY
doc/5.reference/readsf~-help.pd: channnel -> channel
doc/5.reference/vslider-help.pd: COMPATIBILIY -> COMPATIBILITY
doc/5.reference/toggle-help.pd: COMPATIBILIY -> COMPATIBILITY
doc/5.reference/drawpolygon-help.pd: teh -> the
doc/5.reference/qlist-help.pd: SUPRESSING -> SUPPRESSING
doc/5.reference/operators-help.pd: funcitons -> functions
doc/4.data.structures/01.scalars.pd: teh -> the
~~~

**Comment by umlaeute** [comment]
note: i've merged this PR into #113  (and also fixed the spelling errors discovered by spellintian)

**Comment by danomatika** [comment]
That's a useful one-liner. Maybe we should make a document/wiki page for development related stuff like this ... or at least consolidate on an existing page etc. I'm a believer of docs staying with the sources and have been thinking of a "DEVELOPING.txt" etc which explains some of the lower level things needed to get into working on the sources.

**Comment by pierreguillot** [comment]
Great! I guess I can close this PR?

**Comment by danomatika** [comment]
I think so. If you don't now, GH will later when the larger PR is merged.

**Pull request merged**
