### PR TITLE
[WIP] Pd-extended styling

### PR DESCRIPTION
**Pull request by danomatika**
This is a WIP/test PR for experimenting with porting the Pd-extended styling, font metrics, and object sizing into Pd vanilla.

So far, these changes are pulled from the extended source code by looking for meaningful differences with the pd vanilla source code in the "right places." Painful.

Note: The "Pd-extended styling" doesn't mean the coloring and filled object backgrounds, just that the coloring and styles become accessible. It is *not* my intention to change the default vanilla styling, but this is something that could become accessible via a plugin etc.

**Current Status: Not There Yet**

### CODE REVIEW

**Comment by porres** [comment]
Looks fine to me right now, how can I better test this?

By the way, I notice now that some abstractions with graph on parent can also have issues with the changes in 0.48. The picture below shows an external I did and use a lot that I cannot use in 0.48 unless I change it. So I'm keeping 0.47-1 for that matter. So, I tested with this branch's version, and it looks "OK" as the picture shows.

screen shot 2017-08-18 at 14 20 38

Anyway, I feel this should have a priority as a "fix" for the 0.48 release and I'd like to help as I can

thanks

**Comment by porres** [comment]
I have to say the current release 0.48-0 actually looks nicer and feels better to read, though - I wonder if we can have the cake and eat it too

**Comment by danomatika** [comment]
This is *far* from done and most likely not going to be finished very soon.

**Comment by danomatika** [comment]
Looks like the CEAMMC Pure Data fork has integrated the Pd-extended styling: https://github.com/uliss/pure-data

We can use this as a diff for this PR.

**Comment by porres** [comment]
> This is far from done and most likely not going to be finished very soon.

Well, I can test this in Mac, Linux, Windows, how can I help? And what are the problems we still have? Cause it looks good for the end user.

> Looks like the CEAMMC Pure Data fork has integrated the Pd-extended styling: https://github.com/uliss/pure-data

Yup, it does look good

> We can use this as a diff for this PR which could greatly speed things up.

Awesome

**Comment by danomatika** [comment]
I have the basic sizing updates working as a bug fix and put them in a separate branch: #227

**Comment by danomatika** [comment]
Closing as this has largely been superseded by #227.

**Pull request closed without merging**
