### PR TITLE
allow quotes (and spaces) in PdSettings-flags

### PR DESCRIPTION
**Pull request by umlaeute**
the parser for the flags in the PdSettings is currently very naive: it breaks the `flags` strings on each whitespace, and passes these tokens to `sys_argparse`.

Unfortunately, this gives ugly results, when people try to pass strings-with-spaces using their knowledge from the shell (https://github.com/pure-data/pure-data/issues/579):

E.g. while starting Pd with `pd -font-face "Latin Modern Mono Caps"` works nicely, adding the string `-font-face "Latin Modern Mono Caps"` to the *Startup Flags* via the <kbd>File</kbd>-><kbd>Preferences</kbd>-><kbd>Startup...</kbd> will not work at all:
Starting Pd will result in the following errors, indicating that Pd really splits the `"Latin Modern Mono Caps"` into 4 tokens, the 1st of which will be interpreted as the requested font-face, and the rest as patches to open:
```
WARNING: Font family '"Latin' not found, using default (DejaVu Sans Mono)
Using font: DejaVu Sans Mono bold
Modern: can't open
Mono: can't open
Caps": can't open
```

worse: when trying to fix the problem via the <kbd>File</kbd>-><kbd>Preferences</kbd>-><kbd>Startup...</kbd> menu, it will refuse to open with

~~~
(Tcl) UNHANDLED ERROR: extra characters after close-quote
    while executing
"pdtk_startup_dialog .gfxstub55ba2e3998f0 1 "-font-face "L"
    ("uplevel" body line 3)
    invoked from within
"uplevel #0 $docmds"
~~~

The proposed PR fixes all these issues by:
- using a better parser for the `flags` field of the PdSettings, that handles quotes (single, or double) and escapes similar to bash. so the string `-font-face "Latin Modern Mono Caps"` is really parsed into two tokens.
- by escaping the any quotes and curly braces in both `flags` and `font-face` whenever they are sent to the Pd-GUI (mostly `pdtk_startup_dialog` and `pdtk_pd_startup`)

Closes: https://github.com/pure-data/pure-data/issues/579

### CODE REVIEW

**Comment by umlaeute** [comment]
@millerpuckette i think this fixes a rather serious problem with the pdsttings parsers.
it would be cool to have this (or the alternative implementation in #1066) included in the next Pd-release

**Comment by Spacechild1** [comment]
@umlaeute I think your PR is better but it can be simplified with https://github.com/pure-data/pure-data/pull/1070

**Comment by Spacechild1** [comment]
@millerpuckette I think this PR is badly needed.

**Comment by chainjazz** [comment]
Just to add my experience. Flag parsing will accept backslash escaped spaces,. and accept equal signs as fillers between flagname and value.

**Comment by chainjazz** [comment]
After some consideration, why have command line flags in the GUI anyway?

**Pull request merged**
