### PR TITLE
pointing to github externals howto

### PR DESCRIPTION
**Pull request by x37v**
more up-to-date

### CODE REVIEW

**Comment by umlaeute** [comment]
closing, as the link in the documentation already redirects to github (and I prefer having the canonical URL not be owned by e-corp)

**Comment by x37v** [comment]
Redirect is good, I can't remember but I think when I made this change it wasn't a redirect, it was just a stale howto.

**Comment by umlaeute** [comment]
yes sure.

iirc, i implemented the redirect (back then) as a reaction to that issue.

**Comment by x37v** [comment]
great!

**Pull request closed without merging**
