### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by porres**
closes https://github.com/pure-data/pddp/issues/123
closes https://github.com/pure-data/pure-data/issues/1859
closes https://github.com/pure-data/pddp/issues/126
closes https://github.com/pure-data/pddp/issues/127
closes https://github.com/pure-data/pddp/issues/130
closes https://github.com/pure-data/pddp/issues/128

### CODE REVIEW

**Comment by porres** [comment]
@millerpuckette I just had to solve a conflict here on this branch because of the recent change to throw~/catch~ and it is now ok to be merged again. Please consider merging this ASAP as there aren't that much new things but I've been working on the new stuff already and I am afraid that if you take a bit longer this will have yet more conflicts soon that'll be kinda hard and messy to fix - especially if you're going to rename pack~/unpack~ soon.

**Comment by porres** [comment]
hmmm, don't kno why we have a build fail now as I'm only dealing with help files... @umlaeute / @Spacechild1 ?

**Comment by umlaeute** [comment]
afaict, this is due to a local issue on the AppVeyor side (unrelated to your changes).
i've restarted the job, and it know succeeded.

**Comment by millerpuckette** [comment]
OK, done and thanks for all this!

**Pull request merged**
