### PR TITLE
Documentation updates/fixes

### PR DESCRIPTION
**Pull request by porres**
Hi, I'm addressing some documentation issues here, and I'm also reorganizing patches so they look less messy (sorry, I suffer from severe OCD).

### CODE REVIEW

**Comment by porres** [comment]
i dont understand where these conflicts com from and how to resolve them

**Comment by porres** [comment]
I meant these conflicts that came up

Conflicting files
doc/5.reference/list-help.pd
doc/5.reference/out1~.pd
doc/5.reference/text-object-help.pd

And now I see these files got corrupted somehow, then they're generating conflicts. I guess I'll have to redo them :) 

and maybe check everything once again

**Comment by porres** [comment]
> The problem with pd-help.pd now 

actually, not "now", this is just simply as true as before... :)

**Comment by porres** [comment]
just opened an issue about that, as I don't think it's necessary to deal with this right now https://github.com/pure-data/pure-data/issues/701

**Comment by porres** [comment]
Just one example of the difference my edits made visually. One that seems to particularly stand out. That really took me some time to sort it out...

Maybe someone will just consider I wasted a lot of time for basically nothing, or maybe (and hopefully) someone appreciates my mental obsessive disorder :) 

Screen Shot 2019-07-28 at 02 35 05

**Comment by porres** [comment]
> Just one example of the difference my edits made visually.

So, I hope this doesn't give the idea I had to significantly intervene in every patch. Here's an example of one that I basically left in the same way. 
 
Screen Shot 2019-07-28 at 14 47 36

It's like, if I had to change something here, it would have to be drastic by changing the structure of the patch, and I always worked with the same original structure by not changing connections and stuff.

**Comment by porres** [comment]
I would say this other PR https://github.com/pure-data/pure-data/pull/707 is related to the work I've done here, mostly because I've taken care to make sure all of the documentation files have a font size of 12 (only a small minority had font 10 instead)

**Comment by umlaeute** [comment]
unfortunately this PR has not been merged before it started to conflict with "master".
resolving conflicts in Pd-patches is tedious and error-prone.

do you want to update this PR again? (or close/abandon it?)

**Comment by porres** [comment]
yeah, I tried to wave at Miller and ask him to take this one before to avoid such conflicts. Ok, I guess it's not that bad for me to resolve them anyway. It's just that I don't really know what's the best way .But I'll figure it out and try to solve them so it can get merged. Wait for it...

**Comment by porres** [comment]
Ok, I guess I solved the issues? I just replaced conflicting files with the ones from master that have been edited, and now I guess I'll add new commits to work again on these edited files ;)

And it seems one of the attempts to resolve issues made it worse and I'll take care of that too!

**Comment by porres** [comment]
Ok, builds fine now. Took care of the Travis error and worked again on the files/objects that had been updated. Namely: inlet~ / soundfiler / netsend / netreceive / oscformat / drawpolygon. Didn't really changed a thing but fixed some of the files that were not saying they were updated to 0.51

Well, I guess this is good to go now @umlaeute

**Comment by porres** [comment]
> Well, I guess this is good to go

Oops, new conflicts :)

**Comment by porres** [comment]
updated to master and reorganized the new file that has been updated (15.arrays)

**Comment by porres** [comment]
I worked on slop~ and pdcontrol, which I hadn't because they didn't exist when I opened this PR

I also realize I skipped the help of [text], this was one of the files that changed and that I have to work on again, but it's a quite big one, so give me a moment... and it should all be done when I push this last commit

**Comment by porres** [comment]
nah, I had missed out1~ as well... will see if nothing else got overlooked with the conflicts I tried to resolve

**Comment by porres** [comment]
So, a new conflict emerged with a recent merge with updates to [openpanel], and I already dealt with it. It seems I'll probably deal with one or two more before Miller gets to this PR in its chronological order, so I'm aware and waiting to act as needed.

> resolving conflicts in Pd-patches is tedious and error-prone.

I hear you. I'm dealing with how tedious and delicate this process is. But then, meticulously working cosmetic updates and realignment of EVERY documentation patch is also ver very tedious and I knew where I was getting into when I embraced this journey. I guess I suffer from OCD and that's it, tedious and meticulous processes are kind of my thing.

That is to say that I've been painstakingly checking for every detail in the conflicts that came up and don't worry about me overseeing 'errors'. I did what I had to do, I checked every patch file that changed in master since I started this and included the changes. One by one... twice...

**Comment by porres** [comment]
solved conflicts with the [value] object update

**Comment by porres** [comment]
thanks :) I'll keep my eye on further documentation changes

**Pull request merged**
