### PR TITLE
prevent iemguis from drawing when they're out of bounds in a 'GOP'

### PR DESCRIPTION
**Pull request by porres**
closes https://github.com/pure-data/pure-data/issues/1053

### CODE REVIEW

**Comment by porres** [comment]
reverted my last commit in favor of https://github.com/pure-data/pure-data/pull/627 - which feels like a much better way to handle this

**Comment by umlaeute** [comment]
thanks for reverting. i force-pushed the older-revision (so now this PR contains only the wanted commits, and lacks the obsolete commit and it's reversion - which i think is much cleaner).
make sure to update your local branch to the new HEAD, before committing again (lest d6d2218853a7a5f60201bc68f3ec8ad7549f3651 and e1410a327766efb49ab08f8fbd9362bdd5a4b149 creep in again)

**Comment by porres** [comment]
> thanks for reverting. i force-pushed the older-revision (so now this PR contains only the wanted commits

Ok, I wondered if we should do this, because I wanted to keep record that I also wanted to fix that in a different way. But it's alright if we keep the comments.

> make sure to update your local branch to the new HEAD, before committing again

Ok, sure, but this is quite certainly done ;)

**Comment by umlaeute** [comment]
afaict there's still some inconsistencies, e.g. when moving an iemgui out of the GOP-rectangle with `delta` or `pos` messages (which will keep drawing the iemgui even though it should not).

otoh, it might sometimes be useful to be able to spill over the GOP boundaries...

**Comment by porres** [comment]
> otoh, it might sometimes be useful to be able to spill over the GOP boundaries...

like when?

**Comment by umlaeute** [comment]
e.g. creating an abstraction that is the source of an in-canvas particle system (creative coding anybody?)

or more practical: a browser-style alert-box that "blanks" (hides) the surrounding patch while active.

**Comment by Spacechild1** [comment]
someone's bug is always someone else's feature ;-)

**Pull request closed without merging**
