### PR TITLE
Fix and update fr.po

### PR DESCRIPTION
**Pull request by Ant1r**
This fixes some annoying translation bugs, and harmless typos and misspelling (sorry Cyrille ;-).

### CODE REVIEW

**Comment by porres** [comment]
how do these translations take effect when using Pd? I can't get mine to work in brazilian portuguese... or any other so it seems...

**Comment by Ant1r** [comment]
I really don't know... For me it's in french out the box on various Linux boxes I have.

**Comment by avilleret** [comment]
oups that clashes with mine on #58 
after a quick review of yours, I think both have good things (mine add lots of new translation while yours is more accurate I think)
so we should merge the two I think, what's your opinion @Ant1r ?

**Comment by avilleret** [comment]
@porres translation language selection relies on local settings, so If your system is in portuguese, Pd should be in portuguese if available of course.
For example, you can override local settings temporarily with : 

    LANG=pt_PT.UTF-8 pd 
 
which will start Pd in Portuguese while my system remains in French (tested on Ubuntu 17.04)

**Comment by Ant1r** [comment]
Yep @avilleret  I did notice the clash.
I think (but I'm not sure...) that if you merge my mods into yours, then my PR could be merged first then yours without conflict.
OR: you could propose your fixes to my branch (https://github.com/Ant1r/pure-data/tree/update_fr.po) then I would accept it and my PR to Pd would be updated with your mods.
Maybe there could be a better (simpler) way...

**Comment by umlaeute** [comment]
@ant1r if @avilleret merges your changes into his branch, then your changes are a subset of #58 and merging that PR will automatically merge in your changes.

that is: the two PRs can be condensed into a single one that only needs to be accepted once (and the other PR should be closed)

**Comment by avilleret** [comment]
@umlaeute this have been done (merging @Ant1r changes into my branch) this morning. So this PR could be closed and #58 should be update-to-date.

**Comment by Ant1r** [comment]
I agree that this PR should be closed now.

**Pull request closed without merging**
