### PR TITLE
Add "Check for updates" menu

### PR DESCRIPTION
**Pull request by umlaeute**
this opens a webpage https://pdlatest.puredata.info/ which simply redirects to miller's homepage, where the user can see what the newest version of Pd is.

this is trivial from an implementation point of view, as we don't have to do complicated parsing of the http-response (or setup a page that does that for us).
this should also be OK from a privacy point of view, as it doesn't automatically "call home".

i'm using an indirection, as this makes it easier to redirect to some other page, if this is ever needed.

Closes: https://github.com/pure-data/pure-data/issues/1123

### CODE REVIEW

**Comment by aaaaalbert** [comment]
Note that the commit message promises the menu to link to an HTTPS site, but the pull request adds a link to the HTTP site instead.

(Ideally, the HTTP 302 would lead to an HTTPS site as well, but I can't seem to reach https://msp.ucsd.edu/ ).

**Comment by umlaeute** [comment]
hmm, well it's more complicated than that:
- clicking on the link opens http://pdlatest.puredata.info
- this redirects to https://pdlatest.puredata.info
- this in turn redirects to http://msp.ucsd.edu/software.html

one miller (or whoever is in charge for his website) enables `https://` the redirect from https://pdlatest.puredata.info would go to that site.

i'm a big fan of https-everywhere, though lately i started to hand-out `http://`-links rather than `https://` (with all my `http://` redirecting to `https://`) - mostly because i think that the actual security is an implementation detail (as long as it is string enough).

changing the actual link to https://pdlatest.puredata.info would of course be trivial.

**Comment by aaaaalbert** [comment]
I understand your concern. I would personally err on the side of more security, as in: less trivial to hijack etc.

Anyhow, my original comment meant to point out the discrepancy between HTTPS in the commit message and HTTP in the patch. It would fit better if either the patch followed the commit message, or the other way around. (I'm not taking sides :-)

**Comment by umlaeute** [comment]
> It would fit better if either the patch followed the commit message

yes. but that's hard to achieve in retrospect.

**Comment by aaaaalbert** [comment]
Not sure I get it. Add a second commit? Force-push with an amended commit message? Create another PR?

**Comment by umlaeute** [comment]
that seems slightly overkill to me.

**Comment by aaaaalbert** [comment]
Sure, just leave as is! Sorry for the noise.

**Comment by umlaeute** [comment]
at least i changed it in the PR-description ;-)

**Comment by umlaeute** [comment]
i've squashed and included this PR in #1353 and am therefore closing this in favour of the cleaned up one.

**Pull request closed without merging**
