### PR TITLE
filename extensions for double-precision externals (and removing system-specific quirks)

### PR DESCRIPTION
**Pull request by umlaeute**
This PR attempts to get rid of a number of system-specific quirks in the source code in favor of generic checks

### file extension

this is a draft implementation for filename extensions that includes the [deken-specifier](https://github.com/pure-data/deken/blob/main/developer/README.md#filename-format), in order to allow single-precision externals to coexist with double-precision externals.

The idea is to insert a string `.<os>-<arch>-<floatsize>` right before the (common) file-extension.
the "common file-extension" so far is the system's default extension for dynamic libraries (`.dll` on Windows; `.so` on Un*xes)

So an actual binary might look like `foobar.darwin-ppc-32.so`.
(There is still some discussion going on in #902 about the actual format.)

This scheme allows for generic and extendible names that adhere to standards, and can be predicted.

The actual code uses hardcoded values for common systems (Linux/macOS/Windows) and architectures (amd64, i386, arm, arm64,...) but has a mechanism to add new extensions as build options (e.g. for *BSD)

### header inclusion
traditionally, Pd's code is full of `#ifdef __OS__`  to cater for system-specific includes (like "include *this* header on macOS and *that* header on Windows").

Instead this PR attempts to detect the presence of such system-specifics (like headers) *before* compiling (in the `./configure` stage), and then use those headers that are required (like "include *this* header if it exists, otherwise include *that* header if it exists).

The autotools build-system (`./configure`) now does some elaborate checks on which headers are available and usable.
the simple `src/makefile.*` just adds the relevant defines to the system-specific makefiles.

### qsort_r

`qsort_r` is implemented differently on BSDs (including macOS) and GNU systems (Linux), and not available at all on other systems.
instead of enumerating the different beaviours of various OSs, we now do an active check whether `qsort_r` is available at all, and then check it's function prototype to see which variant is used.
based on this info, we can pick the correct sorting implementation reliably.

for the simple `src/makefile.*`, we just replicate the original OS-logic by adding the relevant defines to the system-specific makefiles.

### alloca

about 6 different source-code files use `alloca()` to do "stack-based allocation unless too much memory is required".
traditionally all 6 files would duplicate the same code (include the relevant headers, create some macros that handle the gory details), but many of them slightly different.
this PR unifies the code by providing a single re-usable implementation.

### audio backends

rather than assuming that certain audio-backends are only available on given platforms, we now check whether this is actually true (e.g. OSS exists on more than just Linux, but requires different headers and libraries to be linked; in the PortAudio case, the un*x specific code is no longer restricted to just Linux and macOS.

#### private header utilities
to keep code repetition at a minimum, there's a new header `m_private_utils.h` (only to be used by the Pd-buildsystem itself, and not by externals (including those in `extra/`)), that collects such gory details like
- including the correct headers to detect the endianness
- unify `ALLOCA` handling (include the correct headers, and provide a single macro to be used everywhere)
- redefines for POSIX functions for MSVC

#### BSD

all this was mainly triggered to support building on various BSD-variants.
as such, this PR also includes some simplifications in the BSD handling (no longer special casing the OpenBSD case) and adds build-instruction for this platform.

this PR also closes a few BSD-related bugs:

Closes: https://github.com/pure-data/pure-data/issues/1596
Closes: https://github.com/pure-data/pure-data/issues/1598
Closes: https://github.com/pure-data/pure-data/issues/1597

#### configure options

there's also some new configure options to override file-extensions for externals and the deken-specifier.
this allows us to drop some more OS-specific defines for exotic OSs.
e.g. there's no need to add extra code to allow `.pd_freebsd` on FreeBSD, if this is practically unused. instead, the few people that need it can configure Pd with `--with-external-extension=pd_freebsd`.
Alternatively (or additionally), they could configure Pd with `--with-deken-os=FreeBSD` which will also use `.freebsd-amd64-32.so` as a valid externals extension.

---
This is a reboot of https://github.com/pure-data/pure-data/pull/1599 and includes #1614, so now BSD-support is reached by making the code more general rather than adding additional special-casings.

### CODE REVIEW

**Comment by Spacechild1** [comment]
> any idea what's wrong with the [MSVC build](https://ci.appveyor.com/project/umlaeute/pure-data/builds/43056367)?

`s_inter.c` is missing
```
#ifdef _MSC_VER  /* This is only for Microsoft's compiler, not cygwin, e.g. */
#define snprintf _snprintf
#endif
```

The error message for the 32-bit build
`s_inter.obj : error LNK2019: unresolved external symbol _snprintf referenced in function _sys_deken_specifier`
is a bit confusing because it seems like it's looking for `_snprintf` already. However, the actual symbol name would be `__snprintf` (2 underscores!) because 32-bit PE files use leading underscores for all external symbols.

The error message for the 64-bit build is more obvious:
`s_inter.obj : error LNK2019: unresolved external symbol snprintf referenced in function sys_deken_specifier`

**Comment by umlaeute** [comment]
:facepalm: i checked and double-checked `s_loader.s` instead of `s_inter.c`...

**Comment by Spacechild1** [comment]
Fun fact: `_snprintf` is actually not safe because it doesn't guarantee null-termination.

Visual Studio 2015 finally has a proper `snprintf` - only 16 years after the release of the C99 standard...

But that's not the topic of this PR :-) For now let's continue pretending that `_snprintf` is safe.

**Comment by umlaeute** [comment]
@millerpuckette what do you think about this? is this something that you do not want in principle? or that ought to be implemented differently? that needs more thinking?

has the ship sailed for new features in Pd-0.53?

(this PR is really trying to simplify things; but then i'm aware that i tend to overengineer things a bit)

**Comment by umlaeute** [comment]
ping @millerpuckette

**Pull request merged**
