### PR TITLE
stable development branch

### PR DESCRIPTION
**Pull request by umlaeute**
(just merged, and here it is again)

this is the permanent branch develop that only gets curated, small, no-brainer changes that can be easily merged into master at any time.
(as a general rule-of-thumb we shouldn't include changes to Pd-files in this PR, as it is just too easy to end up with unresolvable file conflicts)

it supersedes https://github.com/pure-data/pure-data/pull/1963

---

### core
- Closes: https://github.com/pure-data/pure-data/issues/1980

### documentation
- Closes: https://github.com/pure-data/pure-data/issues/1976

### CODE REVIEW

**Comment by porres** [comment]
doesnt https://github.com/pure-data/pure-data/pull/1973/commits/c80512f343e89a8b16b9fe119c4679261c3df204 also close https://github.com/pure-data/pure-data/issues/1976 ?

**Comment by umlaeute** [comment]
> doesnt [c80512f](https://github.com/pure-data/pure-data/commit/c80512f343e89a8b16b9fe119c4679261c3df204) also close #1976 ?

yes, and they both will conflict :-/
when I became aware of https://github.com/pure-data/pure-data/commit/c80512f343e89a8b16b9fe119c4679261c3df204 it was already too late.
apart from that: I'm not aware of any PR that actually includes c80512f343e89a8b16b9fe119c4679261c3df204...

**Comment by porres** [comment]
@Lucarda can yuo avoid the conflict?

**Comment by umlaeute** [comment]
> @Lucarda can yuo avoid the conflict?

what's the point of this?
i mean: if @Lucarda 's  `smallfix3` branch was already in *any* PR, we might consider trying to fix the conflict - but it is not.
since the current `develop` branch obsoletes the `Lucarda/smallfix3`, I don't see a reason to spend time resolving issues.

or am I missing something?

**Comment by porres** [comment]
he sent me a fix in my docs branch and I dont want it to have conflicts so they cant be merged

**Comment by umlaeute** [comment]
ah, i missed that it was included in #1973

**Comment by Lucarda** [comment]
Ok i'll do a `git revert` and send a PR to `porres/Documentation`

**Comment by Lucarda** [comment]
I think it not necessary as @umlaeute force pushed?

**Comment by Lucarda** [comment]
@umlaeute tell me if I need to do `git revert` on `porres/Documentation`

**Comment by umlaeute** [comment]
> I think it not necessary as @umlaeute force pushed?

indeed.
i undid my changes and used yours instead, so it should now be possible to merge both `develop` and `porres/Documentation` into `master` without any further action required from your side.
sorry for the confusion.

**Pull request merged**
