### PR TITLE
Fix the bug with the size of subpatches

### PR DESCRIPTION
**Pull request by pierreguillot**
The bug is explained in the issue #100.
I'm not sure that's the best approach, the loading of pd files is a bit opaque to me. 
I solved the problem by checking if the canvas is loading in `canvas_f()`. If not, it means that the size must be applied to this canvas and not to one of his objects.

### CODE REVIEW

**Comment by umlaeute** [comment]
i think this doesn't work correctly if:
- the subpatch gets resized via the mouse (e.g. `, f 42`)
- and after that the subpatch gets GOP enabled.

the result will ignore the GOP-width and instead use the `, f` width.

~~~pd
#N canvas 6 59 759 309 10;
#N canvas 552 90 450 300 (subpatch) 0;
#X coords 0 -1 1 1 80 40 1 100 100;
#X restore 166 125 pd, f 50;
~~~

**Comment by pierreguillot** [comment]
I think this is a second bug that already occurs on the master branch. Here is what I got on the master (tell me if it's a different problem):
ezgif com-video-to-gif

The only difference on my PR is that the the **f** width of the GOP is preserved after reopening the patch (that's not on the video due to size of the GIF). What I can try is to add another correction for this 2nd bug.

PS: Here is a patch will almost all the possibilities I suppose (GOP or not, resized with mouse or not)
[test-size-subpatch.pd.txt](https://github.com/pure-data/pure-data/files/1481539/test-size-subpatch.pd.txt)

**Comment by pierreguillot** [comment]
After investigation, it seems that this second bug is caused by another part of the code (in **graph_getrect()** when **canvas_showtext()** is true). What is corrected by this actual PR is a problem of reading and interpreting the patch in its textual form (see #100). In my opinion, it would be better to correct this bug first in this specific PR and to correct the others with other PR because they are related to size checking etc. and not with the reading of the text file.

For this other PR: Here is another other bugs due to the size of objects and subpatches (#82). One solution is here (#99). Another bug is, for example, if you rewrite the name of the subpatch, the text can exceed the limits of the rectangle and you have to move the GOP to update the rectangle boundaries.

**Comment by millerpuckette** [comment]
I think this is fixed now.

**Pull request closed without merging**
