### PR TITLE
Fix radio buttons

### LINKED ISSUE #730: [vradio] and [hradio] store initial value even when set to No init.
[vradio] and [hradio] store initial value even when set to No init.

Here's how to test this issue:

1) create an empty patch.
2) create the following objects.
[loadbang]
|
[hradio]
|
[print]
3) select the last segment in [hradio]. It will print `7` on the Pd window.
4) Save and close the patch.
5) If you reopen the patch, you will see  the `7` printed in the Pd window although the GUI indicates the first segment is selected.

If you open the patch using the text editor, you can check that `7` is stored as the GUI parameter although it is set to `No init`.

```
#X obj 141 81 hradio 15 1 0 8 empty empty empty 0 -8 0 10 -262144 -1
-1 7;
```

I used `Pd-0.50-test1` on macOS.

### PR DESCRIPTION
**Pull request by porres**
- https://github.com/pure-data/pure-data/pull/831/commits/4693f00dd966b8cf28373a8e395bb4cdf115caac closes #730
- https://github.com/pure-data/pure-data/pull/831/commits/a28e85c1dd826dc7a43ccb9492fbd1f22dc8f7a2 closes https://github.com/pure-data/pure-data/issues/1021

### CODE REVIEW

**Comment by porres** [comment]
can't understand why this build is failing :(

**Comment by porres** [comment]
it wasn't my last commit that failed the build test, it's something with the test itself, but I'll make a new PR for my last (now reverted) commit

**Comment by Spacechild1** [comment]
If you click on "Details", you can see why the build is failing. https://travis-ci.org/github/pure-data/pure-data/jobs/702943215 will shows the following error message:

```
The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall libtool; brew install libtool; fi" failed and exited with 1 during 
```
which means it's not your fault. @umlaeute might have an idea what's going on.

PS: do `git reset 9af8144` and then `git push --force` to get rid of the last commit (2e27864).

**Comment by porres** [comment]
closing this in favor of https://github.com/pure-data/pure-data/pull/1633 which includes both fixes already

**Pull request closed without merging**
