### PR TITLE
regression fixes for launching Pd through GUI

### PR DESCRIPTION
**Pull request by umlaeute**
this PR fixes the regressions that prevent Pd from opening patches in already running instances.

- [x] MSW: opening a Pd-patch through the `pd-gui.tcl` will first check whether there's already a Pd-GUI instance running, and if so, use that one to open the patch (instead of starting a new instance of Pd); this already works on Linux.
- [x] MSW: allow to open patches by calling `pd-gui.tcl <file1> <file2>...` instead of requiring `pd-gui.tcl -open <file1> -open <file2>` (it somehow worked on Linux, not on W32)
- [x] MSW: make the is-app-running detector work per installation
- [ ] check Darwin

related issues #479 and #480

### CODE REVIEW

**Comment by umlaeute** [comment]
@Lucarda, @Spacechild1 please check whether this does something meaningful...

@danomatika include it into `update/0.49`??

**Comment by Spacechild1** [comment]
works for me! patches opened via the gui (`./bin/wish85.exe ./tcl/pd-gui.tcl mypatch.pd`) go to the current instance.

**Comment by Lucarda** [comment]
@umlaeute 

See my first post on #480

**Comment by Lucarda** [comment]
check line 113 shoud be:

    WriteRegStr HKCR "PureData\DefaultIcon" "" "$INSTDIR\bin\pd.exe"``

104:

```
; Care must be taken with this wrapping ' '.
    CreateShortCut "$SMPROGRAMS\Pd-${ARCHI}bit\Pd-${ARCHI}bit.lnk" "$INSTDIR\bin\wish85.exe" '"$INSTDIR\tcl\pd-gui.tcl"' "$INSTDIR\tcl\pd.ico"
```

107:

```
Section "${COMPONENT_DESKTOPSHORTCUT_TEXT}" DesktopShortcut
  ; Care must be taken with this wrapping ' '.
    CreateShortCut "$Desktop\Pd-${ARCHI}bit.lnk" "$INSTDIR\bin\wish85.exe" '"$INSTDIR\tcl\pd-gui.tcl"' "$INSTDIR\tcl\pd.ico"
  SectionEnd
```

121:

 `   WriteRegStr HKCR "PureData\shell\open\command" "" '"$INSTDIR\bin\wish85.exe" "$INSTDIR\tcl\pd-gui.tcl" "%1"'`

**Comment by umlaeute** [comment]
@Lucarda i'm not sure i understand (as in: what do you want that is not already there?)

could you please add your comments directly to the sourcecode via [github's wewbinterface](https://github.com/pure-data/pure-data/pull/481/files)

**Comment by millerpuckette** [comment]
Would it be a good idea for me to merge this now and worry about the remaining questions in another PR later?  Or should I wait until the urrent conversation seems to have been concluded?

**Comment by millerpuckette** [comment]
OK then... perhaps your last comments could be the basis of a separate PR now?

**Comment by Lucarda** [comment]
Yes sure. If needed I'll do another PR. :)

**Pull request merged**
