### PR TITLE
add object to test gpointers for equality

### PR DESCRIPTION
**Pull request by Spacechild1**
output 1 if pointer to left inlet and stored pointer (right inlet) point to the same thing.
otherwise output 0.

alternative implementation: https://github.com/pure-data/pure-data/pull/436

EDIT: we could also create this object via a special constructor argument to [pointer], e.g. [pointer ==]. the thing is that this would break patches which have a struct called "==". maybe it is so unlikely that we can ignore it. after all, Miller reserved "text" for [text], accepting that it *might* cause a regression in someone's patch.

### CODE REVIEW

**Comment by danomatika** [comment]
I think #436 is a better version.

**Comment by Spacechild1** [comment]
NOTE: we could also create this object via a special constructor of [pointer], e.g. [pointer ==]. the thing is that this would break patches which have a struct called "==". maybe it is so unlikely that we can ignore it. after all, Miller reserved "text" for [text], accepting that it *might* cause a regression in someone's patch.

**Comment by umlaeute** [comment]
i'd also prefer if the pointer-related objects lived in their own namespace. `[equal]`, `[compare]` (and `[gem]` and `[set]`) are just way too generic names.

**Comment by Spacechild1** [comment]
me too! the problem is that [pointer] already takes symbols as creation arguments. do you think [pointer ==] would be acceptable?
what are your thoughts about #436 (message version)?

**Comment by Spacechild1** [comment]
closing because alternative PR https://github.com/pure-data/pure-data/pull/436 got merged

**Pull request closed without merging**
