### PR TITLE
Minor change to comment on D12.sampler.bis.pd example patch

### PR DESCRIPTION
**Pull request by maftkd**
The comment made a mistake in describing the passage of data from [route] to [pack] via the message containing $2.

The previous comment claimed the $2 contained amplitude, but actually it contains the poly voice number.

### CODE REVIEW

**Comment by maftkd** [comment]
@porres Did I do this right? You mentioned I should submit these kinds of PR's to the documentation branch: https://forum.pdpatchrepo.info/topic/14684/abstraction-issue-with-d02-adsr-pd-d05-envelope-pitch-pd/2

But this being my first PR, I would appreciate a second set of eyes to make sure things look ok.

**Comment by porres** [comment]
let's try again, let me rebase the branch and reboot the PR, there are a lot of noise and unnecessary commits

**Comment by porres** [comment]
well, it looks like it's already rebased

**Comment by porres** [comment]
I think you just need to sync with current master so things look cleaner!

**Comment by maftkd** [comment]
Thanks for taking a look @porres 
I'm not sure what you mean by:
> I think you just need to sync with current master so things look cleaner!

Do you mind clarifying?
Do you mean I should change the base branch from Documentation to master?

**Comment by porres** [comment]
> Do you mean I should change the base branch (of this PR) from Documentation to master?

documentation is now up to date with master, I think.

You can try by just creating a new branched based on master if you don't know how to sync this one with master and try again. I usually just sync with the web interface

**Comment by maftkd** [comment]
Ok - easiest thing for me then is to just try again in a new PR (after syncing up), and close this PR. Does that sound ok?

**Comment by porres** [comment]
sure

**Pull request closed without merging**
