### PR TITLE
expand $0 to canvas id in messages

### PR DESCRIPTION
**Pull request by danomatika**
Back by popular demand....

~~~
[loadbang]
|
[ $0 <
|
[print]

-----------
print: 1003
~~~

Pulled from Pd-l2ork, so has been tested in the wild. This also includes a compatibility check to be safe, although the only issue would be for people "expecting" a 0 from $0 within a message which I doubt there are any. (Philosophical $ selector design issues aside...)

EDIT: I also updated the message help patch:

screen shot 2018-04-05 at 9 26 23 pm

### CODE REVIEW

**Comment by Spacechild1** [comment]
here's an alternative implementation: https://github.com/pure-data/pure-data/pull/347

**Comment by danomatika** [comment]
Closing this for now in favor of #347.

**Comment by umlaeute** [comment]
@danomatika should we delete this branch?

**Comment by danomatika** [comment]
Here's the relevant commit from the Purr Data implementation: https://git.purrdata.net/jwilkes/purr-data/merge_requests/200

I wonder if there is some advantage over this approach to that of Purr Data?

**Comment by Spacechild1** [comment]
personally, I'm not a big fan of Jonathan's solution (canvas_dollarzero taking a t_pd * argument and checking if it's messresponder_class), I rather took the chance to get rid of some global state in binbuf_realizedollarsym and binbuf_eval. Performance wise there shouldn't be any significant difference (I haven't measured, though!), so I think it's rather a matter of taste.

**Pull request closed without merging**
