### PR TITLE
[WIP] OS X retina support

### PR DESCRIPTION
**Pull request by danomatika**
**_This is a reference PR. Do not merge._**

Some small additions to enable crisp rendering on high dpi displays in OSX. Basically use Tk 8.5 and a newer Wish Shell.app (included) and add a key to the Info.plist.

Some comparison screenshots.

Non retina:

testtone no retina

Retina:

testtone retina

**TODO**
- The only hiccup so far is that the canvas font is now a bit too thin at the default size, IMO.

### CODE REVIEW

**Comment by danomatika** [comment]
Updating to TCL/TK 8.5 also fixes the duplicate Preferences entry.

screen shot 2015-12-09 at 3 04 12 pm

**Comment by eighthave** [comment]
wow a blast from the past.  This kind of stuff was fixed in pd-extended
5 years ago...

**Comment by danomatika** [comment]
Yup. Trying to get some of it in vanilla in *very* small chunks.

**Comment by danomatika** [comment]
@eighthave Also, do you have any notes on TK 8.5? I'm finding the menu accelerators and global bindings are causing events to happen twice now. That and the canvas loses focus after a menu event so an object created from the Put menu doesn't follow the mouse when you move back to the canvas.

**Comment by danomatika** [comment]
@eighthave Also+, the font is two thin on retina. Is there a way to reenable antialiasing on the canvas? I know ::tk::mac::antialiasing is on but that only seems to affect general Tk widgets.

**Comment by eighthave** [comment]
I remember addressing that stuff, but I don't remember the details.  Try
Pd-extended, and if it works, then you know where to look for the code :)

**Comment by danomatika** [comment]
@eighthave I've been working with the vanilla & extended tcl dirs side by side. *Alot* is the same thanks your work merging in the gui updates. I haven't looked into anything on the C side yet as I'm not sure how to compile Pd as port audio seems *really* outdated on the latest OSX.

**Comment by danomatika** [comment]
Figure out the thin font is due to the default being Monaco. It just renders *really* thin at that size, probably since it's a higher resolution font file that comes with OSX. Changing the font to Courier yields a Pd that looks more "normal".

**Comment by danomatika** [comment]
@eighthave So it seems like you fixed all of these by using a non-broken TK build. The built in TK 8.5 that comes with OS X is 8.5.9 which seems to have a number of problems (lots of noise in the python community due to problems with IDLE). Looking in to Pd-extended, you were bundling Tcl & TK as frameworks within the app bundle. I'm looking into doing that again, at least as an option.

**Comment by eighthave** [comment]
yes, including a recent Tcl/Tk bulid with the OSX Pd.app has been
working for 10+ years

**Comment by danomatika** [comment]
Ok cool. I started by digging into vanilla first, so I'm basically reverse engineering what y'all did with extended.

Building Tcl/TK is easy at least. Here's a screenshot of Pd running Tcl/Tk 8.5.19. It looks like the font rendering was improved for retina screens (looks great!):

screen shot 2016-05-10 at 3 30 04 pm

**Comment by danomatika** [comment]
...and all the double bindings & a few other problems are now fixed. Great.

**Comment by danomatika** [comment]
@umlaeute @millerpuckette 

Ok, I've ironed out pretty much all of the issues with TK Cocoa as well as a number of bugs. The number of commits looks large mainly since I've been merging the autootols_updates branch with this one.

Summary so far:

* retina support is enabled in the Info.plist
* added helper script to download & build a Wish.app with embedded tcl/tk frameworks (8.5, 8.6, +)
* TK Cocoa fixes:
  * fixed apple & help menus
  * fixed Shift bindings requiring lowercase letters 
  * added required focus calls to focus windows
  * use default Cocoa key bindings & window list 
  * changed keybindings reserved by TK Cocoa
  * fixed raise/lower Pd window focus issues
  * reenabled checkboxes & radio button focus as TK 8.6 now highlights controls when tabbing through with the keyboard, values are changed with the spacebar
* added key bindings & menu accelerators for Send Message, Tidy Up, Graph, & Array
* fixed help browser not actually closing via key binding
* open dialog popups centered over their buttons to facilitate keyboard menu interaction

The biggest overall changes are to the keybindings:

* Send Message: Mod+M/Mod+Shift+M -> Mod+Shift+K
* HSlider: Mod+Shift+H -> Mod+Shift+J
* Tidy Up: Mod+Shift+R
* Graph: Mod+Shift+G
* Array: Mod+Shift+A

With the newer TK Cocoa backend on OS X (TK 8.5+), comes the default keybindings native to all mac apps. There doesn't seem to be a way to disable or override Minimize (CMD+M / CMD+Shift+M) or Hide (CMD+H / CMD+Shift+H), so I elected to change those particular bindings. The question now is to change them to match on all platforms, or just on Mac. I decided on the former option for consistency at the expense of having to (re)learn two key combinations. What do you think?

Detailed list:

* reenable focus on checkboxes & radio buttons as there is a highlight on TK 8.6
* disable highlight on active focus buttons
* added global variable for whether shift bindings need caps or not
* dialog_find: bindings using lowercase caps with shift
* help browser: destroy window when closing with key binding otherwise it
    remains in the window list
* pd_bindings: proc name cleanups, check if window exists before sending
    close message
* added dialog_font title
* dialog_gatom: reenable radiobutton focus
* dialog_iemgui: open font popup over font button
* dialog_midi: alsamidi dialog now uses -class DialogWindow, don't force
    dialog location for now
* dialog_startup now uses -class DialogWindow, small startup entry width
    fix
* pd_menus: disable Font dialog menu for dialogs
* focus dialogs after raising if reopening; open audio & midi source menu centered over button for keyboard traversal
* dialog_message: added close window key binding
* key binding fixes: shift+key bindings need to be lowercase for TK Cocoa; reorg some bindings; added key bindings for tidy up, graph, & array; added menu accelerator for message dialog
* focus dialogs after raising
* dialog_iem: set color swatch label width to 1 as it's too wide in Tk 8.6 on Mac
* black foreground for text in dialog popups as it was rendering light grey on Mac w/ Tk 8.5+
* don't call verifyquit on ::tk::mac::quit in Tk 8.5 as global binding already does this, also add small sleep for Tk 8.4 to avoid pdsend socket error
* if a window is 1x1, call update to finish it's creation; replaces previous scrollbar fix
* don't manually update window list on Mac Tk 8.5 as Tk Cocoa does this automatically
* added menu_objectlist proc to show help-intro.pd instead as List objects... menu entry was being disabled due missing return value in command
* don't manually bind window minimize & next window in TK Cocoa
* fixed menu_raise_pdwindow bugginess in Tk Cocoa via explict raise/lower & focus relative to current window stack

**Comment by danomatika** [comment]
Test builds located here: http://docs.danomatika.com/pdbuilds

**Comment by millerpuckette** [comment]
accepted with extreme prejudice

**Comment by umlaeute** [comment]
@danomatika given that this has been merged (despite the WIP), should/can we delete the `osx-retina-support` branch?

**Pull request closed without merging**
