### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by porres**
so far:
- add reference to 'pd-messages' in [pdcontrol]
- improve [send~]/[receive~] help file
- closes https://github.com/pure-data/pddp/issues/152

### CODE REVIEW

**Comment by millerpuckette** [comment]
I didn't try to merge our conflicting updates to throw~/catch~ and send~/receive help patches...  you might want to re-propose yours if you think they're better than mine :)

**Comment by porres** [comment]
> you might want to re-propose yours if you think they're better than mine :)

I will repropose because it needs a small change where I'm using a helper abstraction now in many files and this one missed it, for knowing wether dsp is already on or off

**Comment by porres** [comment]
It also misses information for the inlet of catch...

**Comment by porres** [comment]
a new PR is up but hold on as I always find more details and things around

**Comment by porres** [comment]
ok, made important changes for the test release that are ready to go https://github.com/pure-data/pure-data/pull/2001

**Pull request merged**
