### PR TITLE
Shipping and using DejaVu font on Ms-Windows Improved

### PR DESCRIPTION
**Pull request by Lucarda**
This PR includes the fonts and TWAPI on "pdprototype.tgz"  included on the [MSW folder] https://github.com/pure-data/pure-data/tree/master/msw 

Fonts are placed on the pd/bin 
TWAPI and resources on pd/lib

The fonts are loaded on pd-gui.tcl and protected with a catch clause if TWAPI is not present.

This is an improved #269

### CODE REVIEW

**Comment by Lucarda** [comment]
@umlaeute 
Thanks for reviewing!

I will do a w32 build to re-test.

**Comment by umlaeute** [comment]
a rebuild is probably unnecessary, as you are not touching any files that need to be *compiled* (aka "built").

of course, testing the generated "application bundle" (that is, the zip-file and the installer as would be shipped by miller) would be a good thing.

**Comment by Lucarda** [comment]
Ok, I build this branch just to test. I'm using Christof's #258 makefiles.

He unpacks "pdprototype.tgz" in a way similar to Miller I think:

```
tar -xzf $(pd_src)/msw/pdprototype.tgz -C $(pd_src)/msw
cp -r $(pd_src)/msw/pd/bin/* $(bindir)/
cp -r $(pd_src)/msw/pd/lib/* $(libdir)
```

The resulting build includes properly the fonts and twapi. So the “compiled Pd dir” is working. 

I cant test the “Installer” but I guess it will just work.

I can't find the package “mingw32-nsis” for windows needed in https://github.com/pure-data/pure-data/blob/master/msw/build-nsi.sh.  I'm using MinGW  Msys1.

I think the installer will work as it copies from the already "compiled Pd dir".
: - )

**Comment by Lucarda** [comment]
If someone one want to test functionality here's a Zip version:

http://lucarda.com.ar/x/dejavu/pd-dejavu-test-w32.zip

It must be tested on a windows machine with no dejavu font installed. 

**Note:** sign out of windows if you uninstalled the font. 

This has been built with MinGW Msys1.0. These 2 extra files on the pd/bin folder are not necessary on Miller's builds.:

pthreadGC-3.dll
libgcc_s_dw2-1.dll


I used Christof Ressi's makefiles https://github.com/pure-data/pure-data/pull/258 with the “install” option.

**Comment by Lucarda** [comment]
I'm closing this PR because something better is comming here:

https://github.com/pure-data/pdfontloader

**Pull request closed without merging**
