### PR TITLE
Update README.txt

### PR DESCRIPTION
**Pull request by tiagomoraismorgado**
Update README.txt

### CODE REVIEW

**Comment by porres** [comment]
I guess this could be merged into my documentation branch

**Comment by tiagomoraismorgado** [comment]
thanks for the compliment. let me know if there is something to fix

**Comment by Lucarda** [comment]
Hi tiagomoraismorgado,

I appreciate your good will but note that there's no need to change the "numbers of lines" of these files. Especially on `1.introduction.txt`. this file is parsed by `tcl/tk` and gets displayed when you do menu: `help/about Pd`. So the lines formatting in this file is very important.

**Comment by Spacechild1** [comment]
I'm not sure if this is really an "update" or an improvement over the original. There is a sibling PR for SuperCollider: https://github.com/supercollider/supercollider/pull/6014. Has this PR also been made with ChatGPT?

**Comment by porres** [comment]
Can @tiagomoraismorgado describe what changed in this PR? Like I said, usually simple changes like this can go into my documentation branch

**Pull request closed without merging**
