### PR TITLE
swap new modes of openpanel

### PR DESCRIPTION
**Pull request by porres**
This is a tiny revision of https://github.com/pure-data/pure-data/pull/592

closes https://github.com/pure-data/pure-data/issues/816

### CODE REVIEW

**Comment by Spacechild1** [comment]
what are all those commits? you only need the last one.

**Comment by porres** [comment]
> what are all those commits? you only need the last one.

yeah, I know! But hey, I just had my branch and kept syncing with master, then when I sent this PR they all came with it. You know I just use github desktop on a mac and I couldn't figure out how to have control over this thing yet

**Comment by Spacechild1** [comment]
Check out how to use git from the command line, it's much better! 

Anyway, just copy the help patch, reset your branch, paste the help patch and then force push - done.

**Comment by porres** [comment]
> Check out how to use git from the command line, it's much better!

yeah, must be about time :)

I changed the code too, not just the help file, this order of modes seemed more intuitive to me, what do you think?

**Comment by Spacechild1** [comment]
> what do you think?

I don't mind.

BTW, `git gui` is a small but powerful GUI editor for managing commits. Usually, it comes together with git.

**Pull request closed without merging**
