### PR TITLE
Feature/knb3

### PR DESCRIPTION
**Pull request by Ant1r**
This is a reboot of https://github.com/pure-data/pure-data/pull/938, targeted to the `bugfix/iemgui_dialog` branch.

closes https://github.com/pure-data/pure-data/issues/911
Here is a proposal to add a new knob GUI, associated to "Shift+Ctrl+K" key accelerator.

Originally imported from moonlib/mknob, it has now gained several features, such as:

-    optional arc drawing
-    configurable angular area
-    optional ticks
-    removable cursor
-    +/- mode
-   angular, horizontal, vertical or horizontal+vertical movement control

Capture d’écran du 2022-06-15 14-48-53

### CODE REVIEW

**Comment by Spacechild1** [comment]
@umlaeute Did you close this PR by accident?

**Comment by porres** [comment]
I was gonna ask the same thing :)

**Comment by umlaeute** [comment]
I didn't really close it, so yes.

I think the reason why it was closed is, that the target branch was deleted (which I did, because the PR associated with the branch was merged)

I was not aware of the consequences...

**Comment by Ant1r** [comment]
It's ok, it should be easy to re-target to master now. I'll do it asap.

**Pull request closed without merging**
