### PR TITLE
Update m_pd.c

### PR DESCRIPTION
**Pull request by LGoodacre**
Just fixin' a typo that's been bothering me.

### CODE REVIEW

**Comment by danomatika** [comment]
I don't think that's a typo. I think the meaning is "this symbol has been multiply defined" aka "define multiple times."

**Comment by LGoodacre** [comment]
I don't think that "multiply" is an adverb, but I guess it's not worth loosing sleep over.

**Comment by porres** [comment]
apparently it is

screen shot 2017-09-27 at 13 43 13

source: https://www.merriam-webster.com/dictionary/multiply

**Comment by umlaeute** [comment]
- i do think that `multiply` is an adverb (although I'm not a native speaker either and have wondered myself in the past; but then I trust merriam-webster and the [oxford dictionary](https://en.oxforddictionaries.com/definition/multiply#multiply_Adverb_200))
- please don't do commit messages like `updated foo.h`. it's quite obvious that you did change `foo.h` by only throwing a quick glance on the the actual commit. instead describe what the change actually does (or is supposed to do). there are numerous [guides to good commit messages](https://chris.beams.io/posts/git-commit/) out there...

anyhow, closing this because of the closing a non-bug :-)

**Pull request closed without merging**
