### PR TITLE
Don't apply "stretch" in font dialog when selecting different font sizes

### PR DESCRIPTION
**Pull request by sebshader**
In the 2nd commit, an "Apply" button was added to the stretch labelframe to apply the stretch. Then the "OK" button just closes the dialog.

### CODE REVIEW

**Comment by umlaeute** [comment]
which problem is this trying to fix?

**Comment by sebshader** [comment]
@umlaeute currently when using the font dialog, the "stretch" entry field value is applied to the canvas whenever a radiobutton is selected, and when the "OK" button is clicked. This is very unintuitive. This PR would change it so that selecting the font size radiobutton only changes the font size, and then there is a separate "Apply" button for applying the "stretch" ratio to the canvas.

**Comment by umlaeute** [comment]
thanks, makes sense.

probably the `OK` button could be renamed to `Close`, as it has nothing to do with consent to the changes (as the name might imply).

**Comment by umlaeute** [comment]
i've squashed and included this PR in #1353 and am therefore closing this in favour of the cleaned up one.

**Pull request closed without merging**
