### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by umlaeute**
this is the permanent PR for documentation, maintained by @porres

(as a general rule-of-thumb this should **only** include changes to the documentation (help-patches, HTML); other changes should either go into the `develop` branch or in specific feature-branches)

it supersedes #2121

---

- Closes https://github.com/pure-data/pddp/issues/170
- Closes https://github.com/pure-data/pddp/issues/172
- Closes https://github.com/pure-data/pddp/issues/177
- closes https://github.com/pure-data/pddp/issues/182
- closes https://github.com/pure-data/pddp/issues/183
- closes https://github.com/pure-data/pddp/issues/184
- closes https://github.com/pure-data/pddp/issues/179
- closes https://github.com/pure-data/pddp/issues/171

### CODE REVIEW

**Comment by porres** [comment]
this is the permanent PR for documentation, maintained by me, thanks to @umlaeute invitation.

(as a general rule-of-thumb this should only include changes to the documentation (help-patches, HTML); other changes should either go into the develop branch or in specific feature-branches)

it supersedes https://github.com/pure-data/pure-data/pull/2121

Closes https://github.com/pure-data/pddp/issues/170
Closes https://github.com/pure-data/pddp/issues/172
Closes https://github.com/pure-data/pddp/issues/177

**Comment by porres** [comment]
> since I have created this PR, I don't really know whether @porres can update the description by themselves, so I've done this for now.

it seems I can, will try next time

**Comment by porres** [comment]
@umlaeute / @Spacechild1 ; I tried merging master into documentation and couldn't do it, can you help me?

Screen Shot 2024-03-14 at 14 06 01

**Comment by porres** [comment]
do I need more super powers? can you do this for me?

**Comment by umlaeute** [comment]
done.

**Comment by porres** [comment]
Ok, I see you made a PR, right? But can I be trusted with powers to do this or do I have to ask it all the time? :)

**Pull request merged**
