### PR TITLE
0.48 test feedback bug fixes

### PR DESCRIPTION
**Pull request by danomatika**
This is a larger development branch / PR for feedback bug fixes from the 0.48.0 test1 release.

* [x] undo/redo menu tcl errors
* [x] window position issue on Linux
* [x] help browser double click not working
* [ ] prefs save/load not reloading dialogs?
* [ ] prefs paths prepending a + on close/reopen
* [x] spelling errors

### CODE REVIEW

**Comment by danomatika** [comment]
I added a TODO list of what we have so far. Feel free to add new issues/check off others they are fixed in this PR.

**Comment by danomatika** [comment]
I discovered that the system was automatically storing contextual info (open pane location, sizing, etc) to the default domain on macOS. I'm thinking we want to keep the core settings separate from any GUI specific settings like this, so I changed the app bundle domain to org.puredata.pd.pd-gui so the system uses the GUI only settings instead. This should have no discernible effect to users.

**Comment by danomatika** [comment]
In looking into the Path dialog, adding a new Path, closing the window, & reopening prepends a + character to the path.

**Comment by danomatika** [comment]
The + prepared is coming from saving the tcl $::sys_searchpath global in pd string encoding. This isn't really needed as the list can be encoded when using pdsend. I'm seeing the same issue with the listbox entries in the startup dialog ie. being (re)encoded each time the dialog is closed. I have a fix for this and it should be fine as long as other parts of the GUI don't rely on this encoding. From a what my search have pulled up, they don't.

We still need to get these values from pd when loading preferences.

**Comment by danomatika** [comment]
Still missing one Todo: $::sys_search paths in tcl is not being populated from the core when loading preferences, AFAICT.

**Comment by danomatika** [comment]
$::sys_searchpaths issue now fixed in #116

**Comment by umlaeute** [comment]
jeez, i stumbled upon this in #120 and have been debugging it for the last 30 minutes.
only to find out it's already fixed...

**Comment by danomatika** [comment]
Sorry :) Does that fix the -path issue? I was digging around yesterday and didn't;t find what was going on. Today I did a source text search for sys_searchpaths and that showed up...

**Comment by umlaeute** [comment]
yes, it fixes the issue...

**Pull request merged**
