### PR TITLE
intelligent patching amendments

### LINKED ISSUE #548: [feature request] making inserted object immediately editable (intelligent patching)
Once I insert an object in between two connected objects I usually need to edit it right after.

I think it would be useful to have the inserted object box text immediately available for edit. So you can:

-   Select the cord
-   Hit  <kbd>CMD + T </kbd>
-   Start typing the object name...

### LINKED ISSUE #648: triggerize position only correct for left-most iolets
e.g. triggerizing the connection in the following patch:

~~~
[unpack]
       |
       |
       |
[pack  ]
~~~

will yield something like:

~~~
[unpack]
      /
  +--+
 /
[t a ]
 \
  +-+
     \
[pack ]
~~~

rather than the expected:

~~~
[unpack]
       |
       [t a]
       |
[pack  ]
~~~

### PR DESCRIPTION
**Pull request by umlaeute**
some people are a bit unhappy with intelligent patching (#568, #574,...).

this PR is attempting to fix those concerns (and probably add new ones).
the PR is based on [`updates/0.50`](#508).

### fixes and features
 (this list is being updated as new things are added)
- [x] only do multi-connections when pressing a modifier-key (<kbd>Shift</kbd>); Closes:#568
- [x] allow to "deselect all" by pressing <kbd>Esc</kbd>; Closes: #547
- [x] fix insert-object for non-first connections; Closes: #573
- [x] use iolet-positions to better calculate the position of the inserted object; Closes #648 
- [x] made inserted object to be immediately editable; Closes #548 
- [x] have *Duplicate* and *Save-Abstractions* not interfere with the Copy-Paste Buffer; Closes: #644 #643 
- [x] allow fan-out of signal-outlets when connecting objects with <kbd>Ctrl</kbd>-<kbd>k</kbd>; Closes: #501 
- [x] use <kbd>Tab</kbd> to cycle the selected object/line (and <kbd>Shift</kbd>+<kbd>Tab</kbd> for reverse cycling)
- [x] while connecting, the <kbd>Tab</kbd> key cycles the outlets of the source object, resp. the inlets of the sink object (if there *is* a sink object under the mouse; inlet-cycling doesn't work on OSX yet)
- [x] fixed re-doing triggerized [trigger] (#649)
- [x] Regression: <kbd>Tab</kbd>-cycling broken in properties

### demos

https://vimeo.com/showcase/5289665/video/340437816

### experimental builds

those who cannot (or don't want to) compile Pd themselves, can try the experimental [CI-builds](https://git.iem.at/pd/pure-data/pipelines):
- [Win/32bit](https://git.iem.at/pd/pure-data/builds/artifacts/intellipatch2/download?job=w32_snapshot)
- [Win/64bit](https://git.iem.at/pd/pure-data/builds/artifacts/intellipatch2/download?job=w64_snapshot)
- [OSX/64bit](https://git.iem.at/pd/pure-data/builds/artifacts/intellipatch2/download?job=Darwin_snapshot)

these builds include some more features, including the recent changes to the `master` and the `update/0.50` branches.

### CODE REVIEW

**Comment by Ant1r** [comment]
works great for me, all points are valuable enhancements or fixes, congrats!

- point 1 (only multi-connect when shift) is a bit disturbing (since Shift is also used to select/deselect and to connect on-the-fly, the multi-select sequence is now a bit tricky...) but I see no better way to solve the original issue.
- copy-paste buffer restoration saves many bad surprises...
- Tab additions will be much useful

thanks!

**Comment by umlaeute** [comment]
> point 1 (only multi-connect when shift) is a bit disturbing (since Shift is also used to select/deselect and to connect on-the-fly, the multi-select sequence is now a bit tricky...) but I see no better way to solve the original issue.

that <kbd>Shift</kbd> is used to modify an existing selection by adding/removing single items never seemed to clash with the multi-connect enabler in my tests.

it does slightly interfere with connect-on-the-fly, but only slightly:
- if you want multiple multi-connections, well this is what you get :-)
- if you only want a *single* multi-connection, then the connect-on-the-fly is not a big deal: just stop after the first connection
- if you only want multiple single-connections, then you are out of luck and must unselect first.

the last part is the uglies one, but you are already in a very similar situation with the *current* state of intelligent patching, so i think we have a net improvement.

**Comment by fdch** [comment]
I am loving the new feats!

Two things I have to say so far, one might be a regression, the other wishful thinking :)

First, somehow <kbd>Tab</kbd> has stopped working inside iemgui property dialog. This happens at least on macos (tried my own compilation and the darwin snapshot on the pd-list) 

Second, I think making the inserted object immediately editable is a great thing, and I also think it calls for yet another action. So, when you
-  click a cord to select it
-  then edit the new object... and without clicking outside to fully create the object, you
-  type <kbd>Cmd</kbd>+<kbd>t</kbd> (again)

I expect another object to be created below, between the newly created one and the original target connected to it. Instead, a new (second) cord is created with an object in between the two original connected objects, which seems rather useless and redundant. I believe this is because the focus remains on the original cord, but that is now really unnecessary. I think the focus can just advance itself behind the scenes to the newly created cord so that you can continue stacking inserted objects, but I don't know how this is handled under the hood.

Anyway, I will keep on posting things if I find any. If you'd like me to make separate issues, let me know! Keep up these changes cause they are just making patching more exciting every time!

Best,

f

**Comment by umlaeute** [comment]
> First, somehow Tab has stopped working inside iemgui property dialog. This happens at least on macos (tried my own compilation and the darwin snapshot on the pd-list)

it seems like <kbd>Tab</kbd> stopped working for all properties. please do create a new/separate ticket about this.

**Comment by millerpuckette** [comment]
merged to master

**Pull request merged**
