### PR TITLE
Fixes typos in x4.htm

### PR DESCRIPTION
**Pull request by idonotfollowyou**

### CODE REVIEW

**Comment by umlaeute** [comment]
ping @porres and @Lucarda

**Comment by porres** [comment]
yup, on it... @idonotfollowyou you can keep using a single PR for fixing typos, it's better. When I recover from my hangover celebrating lula's election I'll create a PR for manual revision and you can collaborate to that too later on

**Comment by idonotfollowyou** [comment]
Closing. See: #1809

**Comment by Lucarda** [comment]
> When I recover from my hangover celebrating lula's election I'll ... 

&#127881;

@umlaeute  could you create an `htmldocs` branch similar to `develop` ?

@porres @idonotfollowyou me and others use that target branch. This makes html editing better as we can pull `htmldocs` to our PR (we can't pull each others branches from different forks)

@idonotfollowyou once the new `htmldocs` branch is created you can do another PR sarting from your current `idonotfollowyou:typos` but this time targeting `htmldocs` instead of `master

from the web you can target branches accordingly see pic below


pr

**Comment by Lucarda** [comment]
@umlaeute could you create an `htmldocs` branch ?

**Comment by umlaeute** [comment]
@Lucarda should i remove the `htmldocs` branch (as there has been opposition to the concept of such a branch; and it has been already merged into `master`; so if it is no longer needed, i would like to clean up)

**Comment by Lucarda** [comment]
@umlaeute yes go ahead. `htmldocs` is no longer needed.

**Pull request closed without merging**
