### PR TITLE
A canvas object to query information on canvases

### PR DESCRIPTION
**Pull request by porres**
A couple of years ago @danomatika thought about including [getdir] => see https://github.com/pure-data/pure-data/pull/150#issuecomment-318883169

But then the idea was that we'd create a new 'canvas info' object instead.

I also suggested we could port canvasinfo from Purr Data, but I now think it's best we do one from scratch! https://github.com/pure-data/pure-data/issues/273 - here's canvasinfo for reference, anyway, we could still get inspired to get some of the functions in it https://github.com/pd-l2ork/pd/blob/master/pd/src/x_interface.c#L174

So I started working on such object but, so far, I have only included the 'canvas dir' function. This is because I think this is the most crucial feature that we need in vanilla right now.

Issues that depend on a vanilla solution for this is found here: https://github.com/porres/pd-cyclone/issues/412

and also here: https://github.com/pure-data/pure-data/issues/557 

I'm now thinking of other functions to add.

cheers

### CODE REVIEW

**Comment by porres** [comment]
I got my eyes on  '[canvas mouse]: get/send mouse interaction' that @danomatika suggests, seems like [canvasreceive] from iemguts lays all the grounds for that :) 

But I have great hopes for a [canvas arg] object, pretty much based on [canvasargs] as well. This would be crucially important to design vanilla abstractions in a more powerful way, being able to manage given args more flexibly

**Comment by HenriAugusto** [comment]
Indeed those are welcome additions to vanilla. Some functionalities are very useful for creating more powerful GUIs, while _getdir_ and _canvas args_ are great for the reasons mentioned on #273 and #557

**Comment by umlaeute** [comment]
could you please fix the issues reported by the appveyor build? (grep the code for `snprintf` to see how it is handled otherwhere)

**Comment by porres** [comment]
> thanks for your efforts.

welcome :) and thanks back ;)

> could you please fix the issues reported by the appveyor build? (grep the code for snprintf to see how it is handled otherwhere)

sorry, I wanna figure this out, but I just can't seem to do it yet and need help. 

I can see in the details that the problem is the sprintf function, but I googled the error code around and couldn't find something enlightening.

I checked elsewhere how a similar sprintf function is used in Pd and copied from this https://github.com/pure-data/pure-data/blob/a9fd832e9b2ad355292b5eb1ecdb94139e08f2a7/src/s_print.c#L45

but I don't know why this code fails.

I also don't know how to 'grep the code' - at this point you might realise that me trying to do stuff here is actually a big effort :)

**Comment by Spacechild1** [comment]
you have to add
```
#ifdef _MSC_VER  /* This is only for Microsoft's compiler, not cygwin, e.g. */
#define snprintf _snprintf
#endif
```
somewhere at the top, have a look at s_loader.c for example.

**Comment by porres** [comment]
Yay! Thanks.

**Comment by Spacechild1** [comment]
> I also don't know how to 'grep the code'

`grep "snprintf" /path/to/pure-data/src/*.c`

this will list all occurances of snprintf in the C files in Pd's source folder, so you can check what they're doing differently.

**Comment by Spacechild1** [comment]
(sorry, somehow Github only allowed me to do single comments instead of a review)

BTW, the diff of x_misc.c shows several changes in formatting which are not related to your code. maybe your editor does some auto formatting? if you use a GUI tool (e.g. git gui) you can see your changes in advance and you can only stage what you really *want* to commit :-)

**Comment by danomatika** [comment]
>if you use a GUI tool (e.g. git gui) you can see your changes in advance and you can only stage what you really want to commit :-)

Or a decent text editor plus prodigious reviews with `git diff` before committing anything. Sublime Text is good about showing tabs and space character marks which is useful in fixing style & formatting issues.

**Comment by Spacechild1** [comment]
@umlaeute do you know what's going with our code comments? I can only make single comments and they won't show the referenced section of the source code...

**Comment by umlaeute** [comment]
@Spacechild1 full review works for me if I navigate to the [PR's commit](https://github.com/pure-data/pure-data/pull/617/commits/c874927fa42e7553439ee6fef34b36e422688b26) rather than [just the commit](https://github.com/pure-data/pure-data/commit/c874927fa42e7553439ee6fef34b36e422688b26)

**Comment by porres** [comment]
Yeah, I'm just using XCode, and also saw now how the formatting changed, bummer... will look into that

**Comment by porres** [comment]
> the beauty of something like $@ in contrast to [canvas args] is that you can pass the complete argument list down to several abstractions (e.g. [canvas-abstraction $@] will receive all arguments of the parent patch)

I remembered I opened an issue about it https://github.com/pure-data/pure-data/issues/503

**Comment by umlaeute** [comment]
triggered by the discussion #660, it came to my attention that the `[canvas]` object mixes concepts of "abstractions" (with sub-commands like `dir` and `args`) and "canvases" (aka "windows"; with sub-command like `mouse`).

in order to avoid future confustion, i'd suggest to keep these concepts separate (that is: have different objects for interacting with different concepts).

**Comment by porres** [comment]
please, can you elaborate more on how the concepts are defined and differ?

**Comment by umlaeute** [comment]
- a *canvas* is contained within a single window (that is: either a subpatch (`[pd ...]`) or an abstraction)
- an *abstraction* is an object instance based on a `.pd` file.

Assuming you have an object `[foo 1 2 3]`, which is implemented by a file *foo.pd* living in the folder *~/Documents/Pd/* (so it's really an abstraction). This object contains another object `[pd bar zupi]` (that is: a subpatch).
Let the subpatch contain three objects `[canvas args]`, `[canvas dir]` and `[canvas mouse]`.
Furthermore, let the abstraction `[foo]` also contain instances of `[canvas args]`, `[canvas dir]` and `[canvas mouse]` directly.

- What's the output of `[canvas args]` that directly lives in `[foo 1 2 3]`? What's the output of `[canvas args]` that lives in the `[pd bar zupi]` subpatch of `[foo 1 2 3]`? What is "thing" that `[canvas]` refers to when calculating *args*?
- What's the output of `[canvas dir]` that directly lives in `[foo 1 2 3]`? What's the output of `[canvas dir]` that lives in the `[pd bar zupi]` subpatch of `[foo 1 2 3]`? What is "thing" that `[canvas]` refers to when calculating the *dir*?

however:

- What's the output of `[canvas mouse]` that directly lives in `[foo 1 2 3]`? What's the output of `[canvas mouse]` that lives in the `[pd bar zupi]` subpatch of `[foo 1 2 3]`? What is "thing" that `[canvas]` refers to when calculating the *mouse*?

**Comment by porres** [comment]
I see!

[canvas mouse] refers to 'canvases', while [canvas arg] and [canvas dir] refer to 'abstraction' or, to use a technical term under the hood in the Pd code, to an "environment".

> i'd suggest to keep these concepts separate (that is: have different objects for interacting with different concepts).

What would you suggest to call the new object? I see a problem with calling it [abstraction] because you can have the 'dir' function not in an abstraction. On the other hand, the 'args' function only makes sense in an abstraction.

Calling it something like [environment] would make more sense, then, maybe.. the thing is that no one seems to know what that term refers to (I can't say I know it either and I might just saying something silly now).

Maybe [patch]?

**Comment by porres** [comment]
Ok, now that I browse through the code, what I see is something called 'canvas environment'.

such as "/* --------- functions to handle the canvas environment ----------- */"

in https://github.com/pure-data/pure-data/blob/05178840f844e1e0411c1ce9a165613b3542f4fe/src/g_canvas.c

So there seems to be a convergence between these concepts in the code of Pd itself. Maybe we could just reorganize and revise the concept of a canvas and document it in the object or in the Pd documentation as well. By the way, is there a definition of the 'canvas' concept in Pd anywhere?

**Comment by umlaeute** [comment]
the problem at hand is, that the `[canvas]` object relates to different things when using different verbs. which i think is counter-intuitive.

just split it into two objects (on for each "thing")

**Comment by porres** [comment]
hey, I see now Miller has a new [pdcontrol] object that queries the directory of a patch! So [canvas dir] just became redundanct

**Comment by porres** [comment]
maymiller says he can think of many other functionalities this [pdinfo] object could have. Maybe getting arguments can be another...

**Comment by porres** [comment]
> BTW, the beauty of something like $@ in contrast to [canvas args] is that you can pass the complete argument list down to several abstractions (e.g. [canvas-abstraction $@] will receive all arguments of the parent patch)

hey, you can also achieve this with [canvas args], just put it in [canvas-abstraction] and have it ask for the parent's aerguments. What's the difference and the use case?

Anyway, this functionality may also just be part of the new [pd control] object - at least getting the arguments list, for setting the arguments, miller reasoned [savestate] can already handle something like that!

**Comment by Spacechild1** [comment]
> hey, you can also achieve this with [canvas args], just put it in [canvas-abstraction] and have it ask for the parent's aerguments. What's the difference and the use case?

that's true!

**Comment by Spacechild1** [comment]
actually, for this to work, the abstractions needs to know that it should get arguments from the parent. on the other hand, [myabs $@] is transparent. the use case is that some projects use a large number of nested abstractions where each abstraction *possibly* inherits parts of its arguments from its parent. but that's probably an edge case.

**Comment by porres** [comment]
> but that's probably an edge case.

that could probably have another workaround, huh?

**Comment by umlaeute** [comment]
i don't think it's an edge case at all.

oh, and btw: what's the difference between `[canvas args]` and `[canvasargs]`?

**Comment by porres** [comment]
> what's the difference between [canvas args] and [canvasargs]?

the way depth is handled is different, I'm using "environment" and that seemed like an issue on why this was a confusing aspect of the canvas concept. If I recall correctly, canvas args is able to change the name of the abstraction, this one only changes the actual arguments, and also some code changes, but I'd have to look closely side by side to give you more details. I just simplified the code of else/args, which can also break arguments if you give it a breaking character, such as "-" so you can route "flags".

**Comment by porres** [comment]
if this gets in https://github.com/pure-data/pure-data/pull/689 it makes this object almost obsolete...

all left would be the [canvas mouse], so we'd need to rethink what functionalities we're still missing for vanilla that we want, and if they could be in the new [pdcontrol] object, or into a new [canvas] object, or a [path] or whatever

**Comment by porres** [comment]
Closing this for now, as both 'dir' and 'args' are now handled by the new [pdcontrol] object, see https://github.com/pure-data/pure-data/pull/689#event-2531097238

**Comment by porres** [comment]
[canvas mouse], the thing that was still left here, can pretty much just reside in an external library like 'else', or I don't know, maybe we pick up on this discussion of what a new [canvas] object should be and present it with more options/functions.

**Pull request closed without merging**
