### PR TITLE
re-including paf~ in "extra"

### PR DESCRIPTION
**Pull request by porres**
paf~ is a complex and useful external, and it is still referred to in the audio examples (F13 example)

but it really seems it needs a revision, and I guess I shouldn't be the one to do that :/

### CODE REVIEW

**Comment by danomatika** [comment]
I fixed some whitespace issues with this (makefile targets *must* use tabs for indentation).

This is ready to go if you want to look at it @millerpuckette.

**Comment by umlaeute** [comment]
afaict this should be closed for now, see https://github.com/pure-data/pure-data/pull/290#issuecomment-419738348

**Comment by danomatika** [comment]
Ok, make sense.

**Comment by porres** [comment]
Hi, I tried compiling this to test the object, didn't work, maybe did something wrong?

errors:


paf~.c:201:2: error: -- no machine architecture definition?
#error -- no machine architecture definition?
 ^
paf~.c:223:14: error: unknown type name 'int32'
    volatile int32 *hackptr = ((int32 *)(phasehackp)) + HIOFFSET, hackval;
             ^
paf~.c:223:40: error: expected expression
    volatile int32 *hackptr = ((int32 *)(phasehackp)) + HIOFFSET, hackval;
                                       ^
paf~.c:223:33: error: use of undeclared identifier 'int32'
    volatile int32 *hackptr = ((int32 *)(phasehackp)) + HIOFFSET, hackval;
                                ^
paf~.c:223:57: error: use of undeclared identifier 'HIOFFSET'
    volatile int32 *hackptr = ((int32 *)(phasehackp)) + HIOFFSET, hackval;
                                                        ^
paf~.c:224:14: error: unknown type name 'int32'
    volatile int32 *lowptr = ((int32 *)(phasehackp)) + LOWOFFSET, lowbits;
             ^
paf~.c:224:39: error: expected expression
    volatile int32 *lowptr = ((int32 *)(phasehackp)) + LOWOFFSET, lowbits;
                                      ^
paf~.c:224:32: error: use of undeclared identifier 'int32'
    volatile int32 *lowptr = ((int32 *)(phasehackp)) + LOWOFFSET, lowbits;
                               ^
paf~.c:224:56: error: use of undeclared identifier 'LOWOFFSET'
    volatile int32 *lowptr = ((int32 *)(phasehackp)) + LOWOFFSET, lowbits;
                                                       ^
paf~.c:232:5: error: use of undeclared identifier 'hackval'
    hackval = *hackptr;
    ^
paf~.c:236:16: error: use of undeclared identifier 'hackval'
    *hackptr = hackval;
               ^
paf~.c:257:16: error: use of undeclared identifier 'hackval'
    *hackptr = hackval;
               ^
paf~.c:288:13: error: use of undeclared identifier 'hackval'
        *hackptr = hackval;
                   ^
paf~.c:302:13: error: use of undeclared identifier 'hackval'
        *hackptr = hackval;
                   ^
paf~.c:306:13: error: use of undeclared identifier 'hackval'
        *hackptr = hackval;
                   ^
paf~.c:353:2: error: use of undeclared identifier 'lowbits'
        lowbits = *lowptr;
        ^
paf~.c:359:13: error: use of undeclared identifier 'hackval'
        *hackptr = hackval;
                   ^
paf~.c:362:23: error: use of undeclared identifier 'lowbits'; did you mean
      'lowptr'?
        p = paf_table + (lowbits >> (32 - LOGTABSIZE));
                         ^~~~~~~
                         lowptr
paf~.c:224:21: note: 'lowptr' declared here
    volatile int32 *lowptr = ((int32 *)(phasehackp)) + LOWOFFSET, lowbits;
                    ^
paf~.c:362:31: error: invalid operands to binary expression ('volatile int *'
      and 'int')
        p = paf_table + (lowbits >> (32 - LOGTABSIZE));

**Comment by danomatika** [comment]
The first error is telling you where to look. I see what Miller means about needing to clean this up...

**Comment by porres** [comment]
I thought you meant this was compiling and everything by "ready to go", so yeah, it does need a cleanup :/ 

anyway, if not in Pd, having somewhere in deken is a good solution, I can put it up, but needed help :/

**Comment by danomatika** [comment]
"ready to go" means the merge can be applied cleanly. I did not test the actual build.

**Comment by millerpuckette** [comment]
Before you lose any time on that wait for me to go find my working source...  I've kept a copy privately that I think is usable.

**Comment by danomatika** [comment]
This PR will need to be merged with the current master, in the meantime.

**Comment by umlaeute** [comment]
> This PR will need to be merged with the current master, in the meantime.

what for?

**Comment by danomatika** [comment]
>>This PR will need to be merged with the current master, in the meantime.
>what for?

I made an assumption based on the red CI "x" and I was recently making small edits to a few makefiles already.

**Pull request closed without merging**
