### PR TITLE
update midi-help.pd and fix help-intro.pd

### PR DESCRIPTION
**Pull request by porres**
https://github.com/pure-data/pure-data/pull/214 has been merged and it removes the [midiclkcin] object. 

This PR updates the help-intro.pd file to remove this object from the list, so we don't get an error saying we couldn't create the object.

I've also updated the help file of midi-help.pd, in this new version I'm adding for information and details, because I've seen people (students) getting confused and not quite grasping how the objects work. Anyway, I only added more info and details, and kept the former structure of the help file as much as I could.

### CODE REVIEW

**Comment by porres** [comment]
by the way, this was part of an older Pull Request I had made, see https://github.com/pure-data/pure-data/pull/187

But then it got closed because https://github.com/pure-data/pure-data/pull/214 has been merged. So now I have this PR just to change and update the documentation.

**Comment by danomatika** [comment]
I hope you checked the help file first as I believe I already removed that object as well as added some info and aligned the object positioniom better.

**Comment by porres** [comment]
I did check it, and saw you had it removed, but I couldn't spot the info that was added as it looked pretty much the same, sorry. I'll give it a closer and more careful look and include what I'm missing.

**Comment by danomatika** [comment]
I didn't say I had added whatever info you had, only that I added a few things beyond what was there before. I just wanted to make sure we get *both* changes together.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment]
> I didn't say I had added whatever info you had, only that I added a few things beyond what was there before. I just wanted to make sure we get *both* changes together.

Sure, I know.

Well, I added a new commit, I was missing the info where [midiin] also does not output sysex messages. Other than that, it was fine. But I could also spot an error with the documentation from https://github.com/pure-data/pure-data/pull/214 , where the help file of midiin says "these four" where it should say "these three", as [midiclkin] has been removed.

Anyway, other than that, all I'm doing is adding a bit more details and examples.

**Comment by porres** [comment]
> I was missing the info where [midiin] also does not output sysex messages.

Can this be confirmed anyway, please? I don't have how to test it now

**Comment by danomatika** [comment]
It doesn't.

I wrote a test program that generates all MIDI message types when I was working on the update. It's linked on the "midifixes" PR.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment]
perfect, thanks

**Comment by danomatika** [comment]
Also, I added my miditester patch in the docs manual "stuff" folder.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment]
cool, I see it now

but why is this subpatch to "filter" sysex messages from [midiin]? I dont get it

screen shot 2017-12-04 at 03 01 49

**Comment by danomatika** [comment]
The raw syses bytes are passed through while the start and stop bytes are not. I'll look into changing this so the full sysex message *only* comes through the [sysexin] object.

**Comment by danomatika** [comment]
Actually no, I'm wrong. Looks like with my update, [midiin] gives you *all* the bytes including sysex and realtime.

@millerpuckette Did I get this wrong? Should sysex and realtime bytes go *only* to their respective objects? I think it says so in the help patch, so I'll provide a fix.

**Comment by danomatika** [comment]
I think what is slightly confusing is that there are [sysexin] and [sysrealtimein] objects while only a [midiout] object. My original thinking was that [sysexin] & [sysrealtimein] are like [notein], [ctclin], etc and [midiin] & [midiout] receive/send *all* bytes.

I have an update which makes [midiin] only output non-realtime or sysex bytes but I want to make sure this is the expected behavior...

**Comment by danomatika** [comment]
In looking at the help patch again, it states that [midiin] handles all bytes *but* realtime, so I think that is pretty clear:

screen shot 2017-12-04 at 12 36 55 pm

The behavior as it is in the current master is what is expected in the help patch, so I think we are good unless we want to change this behavior.

>but why is this subpatch to "filter" sysex messages from [midiin]? I dont get it

To be clear:

* sysex messages are sent to *both* [midiin] and [sysexin]. The miditester patch filters the raw sysex bytes since they are already printed in the system subpath from the [sysexin] object.

**Comment by porres** [comment]
> I think what is slightly confusing is that there are [midiin], [sysexin], [sysrealtimein]

you meant [midirealtimein], right? :)

**Comment by danomatika** [comment]
>you meant [midirealtimein], right? :)

Yes.

**Comment by porres** [comment]
hi, it seems these commits have been merged, but not the PR itself, so it should be closed.

Now, I had updated the help file to include the information that [midiin] did not send sysex messages, but this is wrong, right? So I guess I need to create a new commit without that wrong information.

**Comment by porres** [comment]
> I need to create a new commit without that wrong information.

and here's the new commit to fix that https://github.com/pure-data/pure-data/pull/263/commits/80edb17a1f88e34677cd4719ab156bc26af39875

**Comment by umlaeute** [comment]
closing this, as it think it has been accepted with 612f47b22fae1bb2d0e80d396aca00225fa3fd12 (please shout out if not).

btw, this PR makes the files `midi-help.pd` and `help-intro.pd` executable (`chmod +x`)
Please try to not do this in the future.

**Comment by porres** [comment]
what hasn't been settled from this yet is the fact that the documentation has just changed, and I think it nows reports a wrong information.

I had updated the help file to include the information that [midiin] did not send sysex messages, but this is wrong, right? So I guess I need to create a new PR to fix this!

**Pull request closed without merging**
