### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [pure-data/Interface](https://hosted.weblate.org/projects/pure-data/pure-data/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by porres** [comment]
@umlaeute I think we should remove at least "toggle" and "bang" from the put menu for translations. Some people are translating this and others are complaining on facebook :)

**Comment by umlaeute** [comment]
rather than complain, they should head over to the weblate project and fix the translations.

**Comment by porres** [comment]
one did edit it back as. I suggested and I approved it, but don't you think we should remove some of these? Bang for sure! I'd add 'toggle' and 'canvas'

**Comment by umlaeute** [comment]
>  but don't you think we should remove some of these?

no

**Comment by porres** [comment]
ok

btw, I see some missing strings to translate. Other software in my computer do translate these... 

Captura de Tela 2024-04-23 às 18 53 58

Captura de Tela 2024-04-23 às 18 54 30

Captura de Tela 2024-04-23 às 18 55 32

Captura de Tela 2024-04-23 às 18 53 38

**Comment by porres** [comment]
For reference, all this is translated for me in chrome 

Captura de Tela 2024-04-23 às 18 53 23

**Comment by porres** [comment]
Captura de Tela 2024-04-23 às 19 14 58

"Cancel", "No", "Yes"

**Comment by umlaeute** [comment]
Most (all?) of these are provided by the system. 
Which means that macOS is not fully aware that it should translate Pd. Apple guys to the rescue...


iirc "Standard (portaudio)" is somewhat special, as this is a string we maintain on the Pd-core side where we typically do not do translations...

**Comment by danomatika** [comment]
As IOhannes says, those are provided by the system. It's not a case of missing strings.Fundamentally, I think there might be a missing locale key in the app bundle Info.plist which cues the system to do this for us. When I updated the translation stuff some years ago, I also put this in place but I remember Miller disabling it for som reason and I didn't look further.In any case, I can't look at this today as work is busy.enohp ym morf tnes-----------Dan Wilcoxdanomatika.comrobotcowboy.comOn Apr 24, 2024, at 6:28 AM, porres ***@***.***> wrote:﻿

Apple guys to the rescue...

who else besides @danomatika ?

**Comment by umlaeute** [comment]
just some additional info:
- [Apple's docs](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundlelocalizations) localization in Info.plist (this seems to not contain anything useful though)
- it seems that miller [hasn't touched](https://github.com/pure-data/pure-data/commits/master/mac/stuff/Info.plist) the `Info.plist` file since it was added to the repository (just saying; he might well have changed something before adding the file to the repo)

**Comment by umlaeute** [comment]
i think the discussion about untranslated strings on macOS is off-topic for this PR (which is about *translations*, not *translatables*), so I've moved (well: copied, with attribution) it to https://github.com/pure-data/pure-data/issues/2269

**Pull request merged**
