### PR TITLE
stable development branch

### PR DESCRIPTION
**Pull request by umlaeute**
(just merged, and here it is again)

this is the permanent branch develop that only gets curated, small, no-brainer changes that can be easily merged into master at any time.
(as a general rule-of-thumb we shouldn't include changes to Pd-files in this PR, as it is just too easy to end up with an unresolvable file conflict)

it supersedes #1498

---

fixes so far (this list should be manually updated whenever new fixes are pushed):

- use C89-style declarations (preventing variable declaration in mid-code) everywhere (we somehow missed [src/s_midi_alsa.c](https://github.com/pure-data/pure-data/blob/621fb52400df4d5a964e9c2606ec06f9d9a2c59d/src/s_midi_alsa.c#L135))
- drop executable bit from `.pd` and `.txt` files
- use consistent line-endings

### CODE REVIEW

**Comment by millerpuckette** [comment]
Anything else to do before calling it 0.52-0? Once this is merged it looks ready to me.

**Comment by Spacechild1** [comment]
To me it looks good. AFAICT, the only remaining regression is https://github.com/pure-data/pure-data/issues/1459, but this one isn't really a show stopper and can wait for the next bugfix release.

I completely lost track of the macOS wish thing. Is this solved now?

**Comment by millerpuckette** [comment]
I _think_ the MacOS Wish thing is OK now.  The remaining problem is that I should probably include compiled wish 8.6.10 with
Iohannes's patches, but I think he has a workaround for the CI system and I'm afraid of introducing bugs, so would rather put that off for after 0.52 if that's workable for everyone.

**Comment by porres** [comment]
here are a couple of regression bugs, no show stoppers either but I have provided a fix https://github.com/pure-data/pure-data/pull/1515

I'm also done with https://github.com/pure-data/pure-data/pull/1517 did work today on revising 7.stuff/soundfile-tools

**Comment by umlaeute** [comment]
> I _think_ the MacOS Wish thing is OK now.

This is basically my understanding as well.

>  The remaining problem is that I should probably include compiled wish 8.6.10 with
>Iohannes's patches,

Somewhat.
My patches are for 8.6.12, and my wish was to have a pre-compiled (and patched) Wish-8.6.12 included...


> but I think he has a workaround for the CI system

but this is correct from my POV: the iem-ci builds use a pre-compiled Wish-8.6.12(universal amd64+arm64) that is hosted on the iem-ci infrastructure (so it is a different binary from the one included with Pd)

**Pull request merged**
