### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by porres**
This is the permanent PR for documentation, maintained/curated by me.

As a general rule-of-thumb this should only include changes to the documentation (help-patches, HTML); other changes should either go into the develop branch or in specific feature-branches

--------

for now, some minor edtis to the manual

### CODE REVIEW

**Comment by Spacechild1** [comment]
Regarding commits like [769623d](https://github.com/pure-data/pure-data/pull/2291/commits/769623d07256332dc7ca565a21d4bd84ddfca89c): are you aware that you can always amend your last commit (and force push)?

In general, your documentation updates create *lots* of commits, many of which are fixups of previous commits. IMO this clutters Pd's commit history quite a bit. Therefore I would suggest that @millerpuckette always squash/merges the documentation branch. @umlaeute @danomatika Objections?

**Comment by porres** [comment]
> Regarding commits like [769623d](https://github.com/pure-data/pure-data/pull/2291/commits/769623d07256332dc7ca565a21d4bd84ddfca89c): are you aware that you can always amend your last commit (and force push)?

yeah, I've been doing it and was about to do it, but was trying to first take care of the relaese notes

and now I don't understand why there is a conflict and I can't fix it... I will try to revert and do it again

**Comment by porres** [comment]
Or maybe I won't try to revert and do it again, cause I believe it won't work... damn... maybe I'll try a whole new branch R for ir... 

I keep hitting my face in this restriction of not being able to update to master...

**Comment by porres** [comment]
@millerpuckette my intent here was to make some changes to the release notes in the hope of making it before the test release, but you would need to first merge what we have here... then things will be in sync so I can make another commit for the release notes (see https://github.com/pure-data/pddp/issues/199)

**Comment by porres** [comment]
I know the strategy to 'sync' I tried here was 'not good', I mentioned it in the last doc PR before doing it and one thing is that it creates pollution. I minimized this now by squashing  and force pushing the commits on this PR, so it can be merged without squashing it all...

And I can also keep squashing redundanct edits and fixes, but I don't think it's a good idea to squash it all, as most times I'm doing separate commits for different issues on https://github.com/pure-data/pddp/ and I think it's good to keep them isolated.

What I would hope anyway is that maybe you @Spacechild1 or @umlaeute could help me sync this branch to master, so I can make my desired commit to improve the release notes. If I can't do it just now, can you do it so I can make the commit? Feels weird to create a new PR just for that

**Comment by porres** [comment]
closing in favor of https://github.com/pure-data/pure-data/pull/2292

**Comment by porres** [comment]
that's nice @Spacechild1 I will have a look at it, and I can see how the several edits back and forth with me and @ben-wes in the manual can't get messy. Sorry. 

Now, what's really really really worrying me is how it's impossible for me to sync the documentation branch to master. I know @umlaeute did this once for me and now it must be done again or else I can't do anything else on it.

I have asked on many occasions if you can help me and let me do that when I need it, or tell me why that would be a problem. If it's a problem, let me know at least why and please just sync it for me again.

thanks

**Comment by Spacechild1** [comment]
I hear you! Unfortunately, I don't really understand what's going on myself.

> I know @umlaeute did this once for me and now it must be done again or else I can't do anything else on it.

If @umlaeute managed to do this, you should be too! Did he explain to you what he did?

If the no-merge-commits policy turns out to be too restrictive and awkward, we should probably lift it. I did not put it in place, so I can't go ahead and do it myself...

**Comment by porres** [comment]
> If @umlaeute managed to do this, you should be too!

I can't @Spacechild1  . Like I said, I tried syncing, I tried rebasing, it doesn't work. I also couldn't even force push until you allowed me, so I think I need some more super powers. Can you do it by the way? Can you grant me this ability? Me and @ben-wes are getting ready for more manual updates.

> But if the no-merge-commits policy turns out to be too restrictive and awkward, we should probably lift it.

it's manageable most of the time, but it can be quite a pain in the ass in some cases. I still don't quite know what it is supposed to be useful for. Anyway, you and @umlaeute are the ones to tell why I guess...

**Comment by Spacechild1** [comment]
Personally, I always rebase my PRs and never had a problem.

I currently don't have time to look into much detail, but I *think* what happens is that you have merged PRs into the *remote* `documentation` branch; if your *local* branch is ahead of the remote and you do `git pull`, you will get a merge commit. There are two solutions:
1. fetch the remote branch with `git fetch`, then rebase your local branch onto the (updated) remote branch with `git rebase <remote>/documentation`. This can actually be done in a single step with `git pull --rebase`.

2. fetch the PR branch, rebase it onto your local `documentation` branch and finally merge it.

Keep in mind that `git push` performs a merge by default. To prevent accidental merge commits, you can do `git pull --ff-only` (= fast-forward only). There is also a global option to configure `git pull` to do `--ff-only` by default.

Generally, I think that PRs should always be rebased and merge commits avoided if possible. The only exceptions are branches where several people commit concurrently, e.g. the `develop` branch. However, I am not sure why a strict no-merge-commit policy should be applied specifically to your branch... @umlaeute can probably answer this.

That being said, I did not put the policy in place! If you keep running into troubles, it's probably better to lift the restriction... Of course, you should still try to adhere to the policy even if it is not enforced.

**Comment by ben-wes** [comment]
> Keep in mind that `git push` performs a merge by default.

should probably be "`git pull`" here.

**Comment by Spacechild1** [comment]
@ben-wes d'oh! Edited.

**Comment by porres** [comment]
> I currently don't have time to look into much detail, but I think what happens is that you have merged PRs into the remote documentation branch; if your local branch is ahead of the remote and you do git pull, you will get a merge commit.

no, that is not the case, which is just trying to sync, update and rebase the current state of the documentation branch to the current master. I can't for the life of me and it is because it complains that '**This branch must not contain merge commits.**'; I reported this a few times now and no alternative given can do the trick.

Ok, I'm not a git master, but @ben-wes is quite well versed and has been trying to help me with this for quite a while now and he can confirm that it's just all impossible. No known way for us can make it work, perhaps some very weird and obscure hackery... we tried many many many things as he can also tell you, and he can also say he thinks you just need to lift the merge commit policy unless miller also does not create merge commits... (more details from ben).

Now, while getting on with the tests today, we realized that the documentation branch had been synced and updated, as I was requesting here, but no one said so and we couldn't have guesses :) have you done that @umlaeute ? 

Anyway, luckily, some new commits have been made to master, so we were behind a bit and tried things over and over again, looked for new solutions, and nothing could be done...

The branch is good for new PRs and I have a new branch in my repo perfectly in sync with current documentation. We will work there now and make a PR eventually with new manual updates. So it's all good now...

But I have to say I'm getting a bit tired of asking about this and I'm feeling kinda ignored regarding my inquires why this has to be the way it is, why i can't be allowed to sync easily, what are the concerns, and how are we supposed to work eventually, when the branch needs to be in sync.

**Comment by Spacechild1** [comment]
> unless miller also does not create merge commits... (more details from ben).

That has been my initial suspicion actually.

> But I have to say I'm getting a bit tired of asking about this and I'm feeling kinda ignored regarding my inquires why this has to be the way it is,

I totally understand. @umlaeute Can we lift the restriction? Looks like this just creates unnecessary roadblocks.

**Comment by ben-wes** [comment]
adding to this: i wouldn't call myself well versed with git. but i surely don't see what the correct workflow here should be.

i initially assumed that the problem was caused by merge commits that @porres created. but after just rebasing the current version of `documentation` onto `master`, it can't be pushed. so obviously, the latest merge commits in the `master` history cause the issue here.

it would certainly be nice to have a clean history and i think there's still some potential in the `documentation` branch. but to me it sounds relatable that @porres needs the option to sync with `master` (and possibly more often with `develop`) in order to adapt changes in help files that were added or edited there. ideally, those syncs should be done via rebasing, of course, and not cause more merge commits.

it's well possible that i lack relevant understanding here - but imho, the force-push option is more risky than the merge commits. :)

**Pull request closed without merging**
