### PR TITLE
stable development branch

### LINKED ISSUE #980: Audio device with japanese characters causes Tcl error
A student of mine with a Japanese laptop couldn't open the audio settings in Pd because the device names would cause a Tcl error:
```
(Tcl) UNHANDLED ERROR: extra characters after close-brace
    while executing
"lappend audio_indevlist {MMIO:Microsoft TEh }"
    ("uplevel" body line 2)
    invoked from within
"uplevel #0 $docmds"
```
The offending audio device has the name `Microsoft サウンド　マッパー`, which is `Microsoft Soundmapper` written in Katakana.

Happened with Pd 0.50-2 64-bit on Windows 8.

### PR DESCRIPTION
**Pull request by Spacechild1**
this PR only contains curated, small, no-brainer changes for the upcoming Pd 0.52 release.

Content (should be updated after each push):

* [regression] fix extra verbose `-stderr` print out
* [regression] fix crash in `[pd~]` subprocess (Closes: #1418)
* [regression] fix compilation error with `-DPDINSTANCE`
* [regression] fix Windows audio backend/settings
* [regression] fix broken `[cputime]` on Windows
* fix occasional wrong usage of `PDINSTANCE` define
* get rid of redundant `x_ctl` member in filter objects
* add missing files to build system
* update HTML docs
* fix some typos
* allow devices with non-ASCII filenames on Windows (hello :cn: , :jp:,...; Closes #980)
* [regression] fix crash when using `[framp~]` without instantiating an `[sqrt~]` object first (Closes: #1432)
* fix connection-lines when resizing new list gatom (Closes: #1407)
* Fix copy-and-paste error for "--enable-libpd-*" flags
* on macOS always link against the CoreFoundation framework (even if no audio backend is selected)
* `[soundfiler]`: fix `-ascii` not overriding the `.txt` extension
* fix `-r` command line option
* fix sized of zoomed labels of gatoms

### CODE REVIEW

**Comment by millerpuckette** [comment]
commit 4eb7dcb doesn't seem to suppress those "verbose()" messages when running -stderr.  I haven't looked yet to figure out why.

**Comment by Spacechild1** [comment]
> commit 4eb7dcb doesn't seem to suppress those "verbose()" messages when running -stderr. I haven't looked yet to figure out why.

Hmmm... certainly works here.

```
./pd-0.52.0/bin/pd.exe -stderr

        ♡♡♡
        ♡ the zexy external  2.3.1
        ♡ (c) 1999-2012 IOhannes m zmölnig
        ♡       forum::für::umläute
        ♡       iem  @  kug
        ♡  compiled  May 30 2020
        ♡ send me a 'help' message
        ♡♡♡

matchbox: OSC-pattern matching code (c) Matt Wright, CNMAT
```

VS

```
 ./pd-0.52.0/bin/pd.exe -stderr -verbose
Pd-0.52.0 ("test1") compiled 21:01:27 Nov  2 2021
float precision = 32 bits
port 52267
Waiting for connection request...
... connected
verbose(4): tried ./zexy.m_i386 and failed
verbose(4): tried ./zexy.dll and failed
verbose(4): tried ./zexy/zexy.m_i386 and failed
verbose(4): tried ./zexy/zexy.dll and failed
verbose(4): tried ./zexy.pd and failed
verbose(4): tried ./zexy.pat and failed
verbose(4): tried ./zexy/zexy.pd and failed
verbose(4): tried C:/Pd/abs/zexy.m_i386 and failed
verbose(4): tried C:/Pd/abs/zexy.dll and failed
verbose(4): tried C:/Pd/abs/zexy/zexy.m_i386 and failed
verbose(4): tried C:/Pd/abs/zexy/zexy.dll and failed
verbose(4): tried C:/Pd/abs/zexy.pd and failed
verbose(4): tried C:/Pd/abs/zexy.pat and failed
verbose(4): tried C:/Pd/abs/zexy/zexy.pd and failed
verbose(4): tried C:/Users/Christof/AppData/Roaming/Pd/zexy/zexy.m_i386 and failed
verbose(4): tried C:/Users/Christof/AppData/Roaming/Pd/zexy/zexy.dll and succeeded

        ♡♡♡
        ♡ the zexy external  2.3.1
        ♡ (c) 1999-2012 IOhannes m zmölnig
        ♡       forum::für::umläute
        ♡       iem  @  kug
        ♡  compiled  May 30 2020
        ♡ send me a 'help' message
        ♡♡♡

verbose(4): warning: class 'abs~' overwritten; old one renamed 'abs~_aliased'
matchbox: OSC-pattern matching code (c) Matt Wright, CNMAT
```

**Comment by millerpuckette** [comment]
yep.  Running in linux from command line:

$ pd -stderr ~/z.pd 
verbose(4): running at normal (non-real-time) priority.

verbose(4): priority 6 scheduling enabled.
... [dozens more lines]

**Comment by millerpuckette** [comment]
Aha..  "pd -noprefs" fixes it.  So somehow the line "verbose 0" in .pdsettings apparently sets off the verbosity.

**Comment by millerpuckette** [comment]
... no, that wasn't it after all (user error:)

**Comment by umlaeute** [comment]
@millerpuckette to be honest, i think we should get rid of *all* `verbose(%d)` specifiers in the `-stderr` output - i see practically no merit in them but a lot of useless verbosity: i can't remember that i ever needed to filter the output for different verbosities (which couldn't be done by adjusting the verbosity in the first place).

i would simply discard them (but have actually thought about replacing them with colour-codes to get similar output as in the Pd-console - at least if the stderr is not redirected)

**Comment by millerpuckette** [comment]
Maybe this is a bad idea but I committed a change to suppress _all_ verbosity unless sys_verbose is on - this is to cover up a threading problem in sfplay~ and sfrecord~ that I'm scared to try to actually fix just now.

**Comment by Spacechild1** [comment]
> Maybe this is a bad idea but I committed a change to suppress _all_ verbosity unless sys_verbose is on

That is actually the expected behavior! We want to avoid spamming the Pd GUI channel with hundreds or thousands of log messages unless we really need them. The problem was just that `logpost` has been broken all the time and it only has been discovered after Pd started to use `logpost` instead of `verbose` internally. In fact, https://github.com/pure-data/pure-data/pull/1428/commits/4eb7dcb7cdd2dc603d8eb5dd1dd07d2c93b72c8c already fixes this very problem :-)

Just like with `verbose`, I've put the check in `logpost` and `startlogpost` to avoid filling a string buffer that we wouldn't need anyway. So your check in `dologpost` would be redundant, but it doesn't hurt to have it there :-)

**Pull request merged**
